GuildShoppingList_AlchemyRecipes  = {
    ["Recipe: Blackmouth Oil"] = { spellId = 0, reagents = { { name = "Oily Blackmouth", count = 2 } } },
    ["Recipe: Catseye Elixir"] = { spellId = 0, reagents = { { name = "Goldthorn", count = 1 }, { name = "Fadeleaf", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Discolored Healing Potion"] = { spellId = 0, reagents = { { name = "Discolored Worg Heart", count = 1 }, { name = "Peacebloom", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Elixir of Agility"] = { spellId = 0, reagents = { { name = "Stranglekelp", count = 1 }, { name = "Goldthorn", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Elixir of Defense"] = { spellId = 0, reagents = { { name = "Wild Steelbloom", count = 1 }, { name = "Stranglekelp", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Elixir of Detect Lesser Invisibility"] = { spellId = 0, reagents = { { name = "Khadgar's Whisker", count = 1 }, { name = "Fadeleaf", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Elixir of Detect Undead"] = { spellId = 0, reagents = { { name = "Elixir of Detect Undead", count = 1 }, { name = "Arthas' Tears", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Elixir of Firepower"] = { spellId = 0, reagents = { { name = "Fire Oil", count = 2 }, { name = "Kingsblood", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Elixir of Fortitude"] = { spellId = 0, reagents = { { name = "Wild Steelbloom", count = 1 }, { name = "Goldthorn", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Elixir of Frost Power"] = { spellId = 0, reagents = { { name = "Dragon's Teeth", count = 2 }, { name = "Khadgar's Whisker", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Elixir of Giant Growth"] = { spellId = 0, reagents = { { name = "Deviate Fish", count = 1 }, { name = "Earthroot", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Elixir of Greater Defense"] = { spellId = 0, reagents = { { name = "Wild Steelbloom", count = 1 }, { name = "Goldthorn", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Elixir of Greater Water Breathing"] = { spellId = 0, reagents = { { name = "Ichor of Undeath", count = 1 }, { name = "Purple Lotus", count = 2 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Elixir of Lesser Agility"] = { spellId = 0, reagents = { { name = "Wild Steelbloom", count = 1 }, { name = "Swiftthistle", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Elixir of Lion's Strength"] = { spellId = 0, reagents = { { name = "Earthroot", count = 1 }, { name = "Silverleaf", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Elixir of Minor Accuracy"] = { spellId = 0, reagents = { { name = "Fire Oil", count = 1 }, { name = "Bruiseweed", count = 2 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Elixir of Minor Agility"] = { spellId = 0, reagents = { { name = "Swiftthistle", count = 1 }, { name = "Silverleaf", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Elixir of Minor Defense"] = { spellId = 0, reagents = { { name = "Silverleaf", count = 2 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Elixir of Minor Fortitude"] = { spellId = 0, reagents = { { name = "Earthroot", count = 2 }, { name = "Peacebloom", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Elixir of Ogre's Strength"] = { spellId = 0, reagents = { { name = "Earthroot", count = 1 }, { name = "Kingsblood", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Elixir of Water Breathing"] = { spellId = 0, reagents = { { name = "Stranglekelp", count = 1 }, { name = "Blackmouth Oil", count = 2 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Elixir of Wisdom"] = { spellId = 0, reagents = { { name = "Mageroyal", count = 1 }, { name = "Briarthorn", count = 2 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Fire Oil"] = { spellId = 0, reagents = { { name = "Firefin Snapper", count = 2 } } },
    ["Recipe: Fire Protection Potion"] = { spellId = 0, reagents = { { name = "Small Flame Sac", count = 1 }, { name = "Fire Oil", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    --["Recipe: Flask of Blinding Light"] = { spellId = 0, reagents = { { name = "Fel Lotus", count = 1 }, { name = "Mana Thistle", count = 3 }, { name = "Netherbloom", count = 7 }, { name = "Crystal Vial", count = 1 } } },
    --["Recipe: Flask of Fortification"] = { spellId = 0, reagents = { { name = "Fel Lotus", count = 1 }, { name = "Mana Thistle", count = 3 }, { name = "Ancient Lichen", count = 7 }, { name = "Crystal Vial", count = 1 } } },
    --["Recipe: Flask of Mighty Restoration"] = { spellId = 0, reagents = { { name = "Fel Lotus", count = 1 }, { name = "Mana Thistle", count = 3 }, { name = "Dreaming Glory", count = 7 }, { name = "Crystal Vial", count = 1 } } },
    --["Recipe: Flask of Pure Death"] = { spellId = 0, reagents = { { name = "Fel Lotus", count = 1 }, { name = "Mana Thistle", count = 3 }, { name = "Nightmare Vine", count = 7 }, { name = "Crystal Vial", count = 1 } } },
    --["Recipe: Flask of Relentless Assault"] = { spellId = 0, reagents = { { name = "Fel Lotus", count = 1 }, { name = "Mana Thistle", count = 3 }, { name = "Terocone", count = 7 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Free Action Potion"] = { spellId = 0, reagents = { { name = "Blackmouth Oil", count = 2 }, { name = "Stranglekelp", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Frost Oil"] = { spellId = 0, reagents = { { name = "Dragon's Teeth", count = 1 }, { name = "Khadgar's Whisker", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Frost Protection Potion"] = { spellId = 0, reagents = { { name = "Dragon's Teeth", count = 1 }, { name = "Goldthorn", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Goblin Rocket Fuel"] = { spellId = 0, reagents = { { name = "Firebloom", count = 1 }, { name = "Volatile Rum", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Gold Bar"] = { spellId = 0, reagents = { { name = "Iron Bar", count = 1 } } },
    ["Recipe: Great Rage Potion"] = { spellId = 0, reagents = { { name = "Large Fang", count = 1 }, { name = "Kingsblood", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Greater Mana Potion"] = { spellId = 0, reagents = { { name = "Khadgar's Whisker", count = 1 }, { name = "Goldthorn", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Gurubashi Mojo Madness"] = { spellId = 0, reagents = { { name = "Gurubashi Mojo Madness", count = 3 } } },
    ["Recipe: Healing Potion"] = { spellId = 0, reagents = { { name = "Bruiseweed", count = 1 }, { name = "Briarthorn", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Holy Protection Potion"] = { spellId = 0, reagents = { { name = "Bruiseweed", count = 1 }, { name = "Swiftthistle", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Lesser Healing Potion"] = { spellId = 0, reagents = { { name = "Minor Healing Potion", count = 1 }, { name = "Briarthorn", count = 1 } } },
    ["Recipe: Lesser Invisibility Potion"] = { spellId = 0, reagents = { { name = "Fadeleaf", count = 1 }, { name = "Wild Steelbloom", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Lesser Mana Potion"] = { spellId = 0, reagents = { { name = "Mageroyal", count = 1 }, { name = "Stranglekelp", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Lesser Stoneshield Potion"] = { spellId = 0, reagents = { { name = "Mithril Ore", count = 1 }, { name = "Goldthorn", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Magic Resistance Potion"] = { spellId = 0, reagents = { { name = "Purple Lotus", count = 1 }, { name = "Khadgar's Whisker", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Mana Potion"] = { spellId = 0, reagents = { { name = "Stranglekelp", count = 1 }, { name = "Kingsblood", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Mighty Troll's Blood Elixir"] = { spellId = 0, reagents = { { name = "Liferoot", count = 1 }, { name = "Bruiseweed", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Minor Healing Potion"] = { spellId = 0, reagents = { { name = "Peacebloom", count = 1 }, { name = "Silverleaf", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Minor Magic Resistance Potion"] = { spellId = 0, reagents = { { name = "Mageroyal", count = 3 }, { name = "Wild Steelbloom", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Minor Mana Potion"] = { spellId = 0, reagents = { { name = "Mageroyal", count = 1 }, { name = "Silverleaf", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Minor Rejuvenation Potion"] = { spellId = 0, reagents = { { name = "Mageroyal", count = 2 }, { name = "Peacebloom", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Nature Protection Potion"] = { spellId = 0, reagents = { { name = "Liferoot", count = 1 }, { name = "Stranglekelp", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Oil of Immolation"] = { spellId = 0, reagents = { { name = "Goldthorn", count = 1 }, { name = "Firebloom", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Philosopher's Stone"] = { spellId = 0, reagents = { { name = "Iron Bar", count = 4 }, { name = "Black Vitriol", count = 1 }, { name = "Purple Lotus", count = 4 }, { name = "Firebloom", count = 4 } } },
    ["Recipe: Potion of Curing"] = { spellId = 0, reagents = { { name = "Large Venom Sac", count = 1 }, { name = "Bruiseweed", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Rage Potion"] = { spellId = 0, reagents = { { name = "Sharp Claw", count = 2 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Recipe: Elixir of Brute Force"] = { spellId = 0, reagents = { { name = "Gromsblood", count = 2 }, { name = "Sorrowmoss", count = 2 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Recipe: Elixir of Dream Vision"] = { spellId = 0, reagents = { { name = "Purple Lotus", count = 3 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Recipe: Elixir of Giants"] = { spellId = 0, reagents = { { name = "Sungrass", count = 1 } } },
    ["Recipe: Recipe: Elixir of Greater Firepower"] = { spellId = 0, reagents = { { name = "Fire Oil", count = 3 } } },
    ["Recipe: Recipe: Elixir of the Mongoose"] = { spellId = 0, reagents = { { name = "Mountain Silversage", count = 2 }, { name = "Sorrowmoss", count = 2 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Recipe: Elixir of the Sages"] = { spellId = 0, reagents = { { name = "Dreamfoil", count = 1 }, { name = "Sorrowmoss", count = 2 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Recipe: Flask of Distilled Wisdom"] = { spellId = 0, reagents = { { name = "Dreamfoil", count = 30 }, { name = "Icecap", count = 10 }, { name = "Black Lotus", count = 1 }, { name = "Crystal Vial", count = 1 }  } },
    ["Recipe: Recipe: Flask of Supreme Power"] = { spellId = 0, reagents = { { name = "Dreamfoil", count = 30 }, { name = "Mountain Silversage", count = 10 }, { name = "Black Lotus", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Recipe: Flask of the Titans"] = { spellId = 0, reagents = { { name = "Gromsblood", count = 30 }, { name = "Stonescale Oil", count = 10 }, { name = "Black Lotus", count = 1 }, { name = "Crystal Vial", count = 1 }  } },
    ["Recipe: Recipe: Flask of Petrification"] = { spellId = 0, reagents = { { name = "Stonescale Oil", count = 30 }, { name = "Mountain Silversage", count = 10 }, { name = "Black Lotus", count = 1 }, { name = "Crystal Vial", count = 1 }  } },
    ["Recipe: Recipe: Flask of Chromatic Resistance"] = { spellId = 0, reagents = { { name = "Icecap", count = 30 }, { name = "Mountain Silversage", count = 10 }, { name = "Black Lotus", count = 1 }, { name = "Crystal Vial", count = 1 }  } },
    ["Recipe: Recipe: Ghost Dye"] = { spellId = 0, reagents = { { name = "Ghost Dye", count = 1 }, { name = "Ghost Mushroom", count = 2 }, { name = "Purple Dye", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Recipe: Gift of Arthas"] = { spellId = 0, reagents = { { name = "Arthas' Tears", count = 1 }, { name = "Blindweed", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Recipe: Greater Arcane Elixir"] = { spellId = 0, reagents = { { name = "Dreamfoil", count = 3 }, { name = "Mountain Silversage", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Recipe: Greater Arcane Protection Potion"] = { spellId = 0, reagents = { { name = "Dream Dust", count = 1 }, { name = "Dreamfoil", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Recipe: Greater Dreamless Sleep Potion"] = { spellId = 0, reagents = { { name = "Greater Dreamless Sleep Potion", count = 1 } } },
    ["Recipe: Recipe: Greater Fire Protection Potion"] = { spellId = 0, reagents = { { name = "Elemental Fire", count = 1 }, { name = "Dreamfoil", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Recipe: Greater Frost Protection Potion"] = { spellId = 0, reagents = { { name = "Elemental Water", count = 1 }, { name = "Dreamfoil", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Recipe: Greater Nature Protection Potion"] = { spellId = 0, reagents = { { name = "Elemental Earth", count = 1 }, { name = "Dreamfoil", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Recipe: Greater Shadow Protection Potion"] = { spellId = 0, reagents = { { name = "Shadow Oil", count = 1 }, { name = "Dreamfoil", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Recipe: Greater Stoneshield Potion"] = { spellId = 0, reagents = { { name = "Stonescale Oil", count = 3 }, { name = "Thorium Ore", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Recipe: Invisibility Potion"] = { spellId = 0, reagents = { { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Recipe: Limited Invulnerability Potion"] = { spellId = 0, reagents = { { name = "Blindweed", count = 2 }, { name = "Ghost Mushroom", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Recipe: Living Action Potion"] = { spellId = 0, reagents = { { name = "Living Action Potion", count = 1 } } },
    ["Recipe: Recipe: Mageblood Elixir"] = { spellId = 0, reagents = { { name = "Mageblood Elixir", count = 1 } } },
    ["Recipe: Recipe: Major Mana Potion"] = { spellId = 0, reagents = { { name = "Dreamfoil", count = 3 }, { name = "Icecap", count = 2 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Recipe: Major Rejuvenation Potion"] = { spellId = 0, reagents = { { name = "Heart of the Wild (crafting reagent)", count = 1 }, { name = "Golden Sansam", count = 4 }, { name = "Dreamfoil", count = 4 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Recipe: Major Troll's Blood Potion"] = { spellId = 0, reagents = { { name = "Major Troll's Blood Elixir", count = 1 } } },
    ["Recipe: Recipe: Mighty Rage Potion"] = { spellId = 0, reagents = { { name = "Gromsblood", count = 3 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Recipe: Potion of Petrification"] = { spellId = 0, reagents = { { name = "Stonescale Oil", count = 7 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Recipe: Transmute Air to Fire"] = { spellId = 0, reagents = { { name = "Essence of Fire", count = 1 } } },
    ["Recipe: Recipe: Transmute Earth to Life"] = { spellId = 0, reagents = { { name = "Essence of Earth", count = 1 } } },
    ["Recipe: Recipe: Transmute Earth to Water"] = { spellId = 0, reagents = { { name = "Essence of Water", count = 1 } } },
    ["Recipe: Recipe: Transmute Elemental Fire"] = { spellId = 0, reagents = { { name = "Elemental Fire", count = 3 } } },
    ["Recipe: Recipe: Transmute Life to Earth"] = { spellId = 0, reagents = { { name = "Living Essence", count = 1 } } },
    ["Recipe: Recipe: Transmute Undeath to Water"] = { spellId = 0, reagents = { { name = "Essence of Undeath", count = 1 } } },
    ["Recipe: Recipe: Transmute Water to Undeath"] = { spellId = 0, reagents = { { name = "Essence of Water", count = 1 } } },
    ["Recipe: Restorative Potion"] = { spellId = 0, reagents = { { name = "Elemental Earth", count = 1 }, { name = "Goldthorn", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Shadow Oil"] = { spellId = 0, reagents = { { name = "Fadeleaf", count = 4 }, { name = "Grave Moss", count = 4 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Shadow Protection Potion"] = { spellId = 0, reagents = { { name = "Grave Moss", count = 1 }, { name = "Kingsblood", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Strong Troll's Blood Elixir"] = { spellId = 0, reagents = { { name = "Bruiseweed", count = 2 }, { name = "Briarthorn", count = 2 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Super Rejuvenation Potion"] = { spellId = 0, reagents = { { name = "Mana Thistle", count = 2 }, { name = "Dreaming Glory", count = 1 }, { name = "Netherbloom", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Superior Healing Potion"] = { spellId = 0, reagents = { { name = "Sungrass", count = 1 }, { name = "Khadgar's Whisker", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Swiftness Potion"] = { spellId = 0, reagents = { { name = "Swiftthistle", count = 1 }, { name = "Briarthorn", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Swim Speed Potion"] = { spellId = 0, reagents = { { name = "Swiftthistle", count = 1 }, { name = "Blackmouth Oil", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Truesilver Bar"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 1 } } },
    ["Recipe: Weak Troll's Blood Elixir"] = { spellId = 0, reagents = { { name = "Peacebloom", count = 1 }, { name = "Earthroot", count = 2 }, { name = "Crystal Vial", count = 1 } } },
    ["Recipe: Wildvine Potion"] = { spellId = 0, reagents = { { name = "Wildvine", count = 1 }, { name = "Purple Lotus", count = 1 }, { name = "Crystal Vial", count = 1 } } },
}
