GuildShoppingList_AlchemyRecipes  = {
    ["Blackmouth Oil"] = { spellId = 0, reagents = { { name = "Oily Blackmouth", count = 2 } } },
    ["Catseye Elixir"] = { spellId = 0, reagents = { { name = "Goldthorn", count = 1 }, { name = "Fadeleaf", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Discolored Healing Potion"] = { spellId = 0, reagents = { { name = "Discolored Worg Heart", count = 1 }, { name = "Peacebloom", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Elixir of Agility"] = { spellId = 0, reagents = { { name = "Stranglekelp", count = 1 }, { name = "Goldthorn", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Elixir of Defense"] = { spellId = 0, reagents = { { name = "Wild Steelbloom", count = 1 }, { name = "Stranglekelp", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Elixir of Detect Lesser Invisibility"] = { spellId = 0, reagents = { { name = "Khadgar's Whisker", count = 1 }, { name = "Fadeleaf", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Elixir of Detect Undead"] = { spellId = 0, reagents = { { name = "Elixir of Detect Undead", count = 1 }, { name = "Arthas' Tears", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Elixir of Firepower"] = { spellId = 0, reagents = { { name = "Fire Oil", count = 2 }, { name = "Kingsblood", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Elixir of Fortitude"] = { spellId = 0, reagents = { { name = "Wild Steelbloom", count = 1 }, { name = "Goldthorn", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Elixir of Frost Power"] = { spellId = 0, reagents = { { name = "Dragon's Teeth", count = 2 }, { name = "Khadgar's Whisker", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Elixir of Giant Growth"] = { spellId = 0, reagents = { { name = "Deviate Fish", count = 1 }, { name = "Earthroot", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Elixir of Greater Defense"] = { spellId = 0, reagents = { { name = "Wild Steelbloom", count = 1 }, { name = "Goldthorn", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Elixir of Greater Water Breathing"] = { spellId = 0, reagents = { { name = "Ichor of Undeath", count = 1 }, { name = "Purple Lotus", count = 2 }, { name = "Crystal Vial", count = 1 } } },
    ["Elixir of Lesser Agility"] = { spellId = 0, reagents = { { name = "Wild Steelbloom", count = 1 }, { name = "Swiftthistle", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Elixir of Lion's Strength"] = { spellId = 0, reagents = { { name = "Earthroot", count = 1 }, { name = "Silverleaf", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Elixir of Minor Accuracy"] = { spellId = 0, reagents = { { name = "Fire Oil", count = 1 }, { name = "Bruiseweed", count = 2 }, { name = "Crystal Vial", count = 1 } } },
    ["Elixir of Minor Agility"] = { spellId = 0, reagents = { { name = "Swiftthistle", count = 1 }, { name = "Silverleaf", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Elixir of Minor Defense"] = { spellId = 0, reagents = { { name = "Silverleaf", count = 2 }, { name = "Crystal Vial", count = 1 } } },
    ["Elixir of Minor Fortitude"] = { spellId = 0, reagents = { { name = "Earthroot", count = 2 }, { name = "Peacebloom", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Elixir of Ogre's Strength"] = { spellId = 0, reagents = { { name = "Earthroot", count = 1 }, { name = "Kingsblood", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Elixir of Water Breathing"] = { spellId = 0, reagents = { { name = "Stranglekelp", count = 1 }, { name = "Blackmouth Oil", count = 2 }, { name = "Crystal Vial", count = 1 } } },
    ["Elixir of Wisdom"] = { spellId = 0, reagents = { { name = "Mageroyal", count = 1 }, { name = "Briarthorn", count = 2 }, { name = "Crystal Vial", count = 1 } } },
    ["Fire Oil"] = { spellId = 0, reagents = { { name = "Firefin Snapper", count = 2 } } },
    ["Fire Protection Potion"] = { spellId = 0, reagents = { { name = "Small Flame Sac", count = 1 }, { name = "Fire Oil", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    --["Flask of Blinding Light"] = { spellId = 0, reagents = { { name = "Fel Lotus", count = 1 }, { name = "Mana Thistle", count = 3 }, { name = "Netherbloom", count = 7 }, { name = "Crystal Vial", count = 1 } } },
    --["Flask of Fortification"] = { spellId = 0, reagents = { { name = "Fel Lotus", count = 1 }, { name = "Mana Thistle", count = 3 }, { name = "Ancient Lichen", count = 7 }, { name = "Crystal Vial", count = 1 } } },
    --["Flask of Mighty Restoration"] = { spellId = 0, reagents = { { name = "Fel Lotus", count = 1 }, { name = "Mana Thistle", count = 3 }, { name = "Dreaming Glory", count = 7 }, { name = "Crystal Vial", count = 1 } } },
    --["Flask of Pure Death"] = { spellId = 0, reagents = { { name = "Fel Lotus", count = 1 }, { name = "Mana Thistle", count = 3 }, { name = "Nightmare Vine", count = 7 }, { name = "Crystal Vial", count = 1 } } },
    --["Flask of Relentless Assault"] = { spellId = 0, reagents = { { name = "Fel Lotus", count = 1 }, { name = "Mana Thistle", count = 3 }, { name = "Terocone", count = 7 }, { name = "Crystal Vial", count = 1 } } },
    ["Free Action Potion"] = { spellId = 0, reagents = { { name = "Blackmouth Oil", count = 2 }, { name = "Stranglekelp", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Frost Oil"] = { spellId = 0, reagents = { { name = "Dragon's Teeth", count = 1 }, { name = "Khadgar's Whisker", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Frost Protection Potion"] = { spellId = 0, reagents = { { name = "Dragon's Teeth", count = 1 }, { name = "Goldthorn", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Goblin Rocket Fuel"] = { spellId = 0, reagents = { { name = "Firebloom", count = 1 }, { name = "Volatile Rum", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Gold Bar"] = { spellId = 0, reagents = { { name = "Iron Bar", count = 1 } } },
    ["Great Rage Potion"] = { spellId = 0, reagents = { { name = "Large Fang", count = 1 }, { name = "Kingsblood", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Greater Mana Potion"] = { spellId = 0, reagents = { { name = "Khadgar's Whisker", count = 1 }, { name = "Goldthorn", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Gurubashi Mojo Madness"] = { spellId = 0, reagents = { { name = "Gurubashi Mojo Madness", count = 3 } } },
    ["Healing Potion"] = { spellId = 0, reagents = { { name = "Bruiseweed", count = 1 }, { name = "Briarthorn", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Holy Protection Potion"] = { spellId = 0, reagents = { { name = "Bruiseweed", count = 1 }, { name = "Swiftthistle", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Lesser Healing Potion"] = { spellId = 0, reagents = { { name = "Minor Healing Potion", count = 1 }, { name = "Briarthorn", count = 1 } } },
    ["Lesser Invisibility Potion"] = { spellId = 0, reagents = { { name = "Fadeleaf", count = 1 }, { name = "Wild Steelbloom", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Lesser Mana Potion"] = { spellId = 0, reagents = { { name = "Mageroyal", count = 1 }, { name = "Stranglekelp", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Lesser Stoneshield Potion"] = { spellId = 0, reagents = { { name = "Mithril Ore", count = 1 }, { name = "Goldthorn", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Magic Resistance Potion"] = { spellId = 0, reagents = { { name = "Purple Lotus", count = 1 }, { name = "Khadgar's Whisker", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Mana Potion"] = { spellId = 0, reagents = { { name = "Stranglekelp", count = 1 }, { name = "Kingsblood", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Mighty Troll's Blood Elixir"] = { spellId = 0, reagents = { { name = "Liferoot", count = 1 }, { name = "Bruiseweed", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Minor Healing Potion"] = { spellId = 0, reagents = { { name = "Peacebloom", count = 1 }, { name = "Silverleaf", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Minor Magic Resistance Potion"] = { spellId = 0, reagents = { { name = "Mageroyal", count = 3 }, { name = "Wild Steelbloom", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Minor Mana Potion"] = { spellId = 0, reagents = { { name = "Mageroyal", count = 1 }, { name = "Silverleaf", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Minor Rejuvenation Potion"] = { spellId = 0, reagents = { { name = "Mageroyal", count = 2 }, { name = "Peacebloom", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Nature Protection Potion"] = { spellId = 0, reagents = { { name = "Liferoot", count = 1 }, { name = "Stranglekelp", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Oil of Immolation"] = { spellId = 0, reagents = { { name = "Goldthorn", count = 1 }, { name = "Firebloom", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Philosopher's Stone"] = { spellId = 0, reagents = { { name = "Iron Bar", count = 4 }, { name = "Black Vitriol", count = 1 }, { name = "Purple Lotus", count = 4 }, { name = "Firebloom", count = 4 } } },
    ["Potion of Curing"] = { spellId = 0, reagents = { { name = "Large Venom Sac", count = 1 }, { name = "Bruiseweed", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Rage Potion"] = { spellId = 0, reagents = { { name = "Sharp Claw", count = 2 }, { name = "Crystal Vial", count = 1 } } },
    ["Elixir of Brute Force"] = { spellId = 0, reagents = { { name = "Gromsblood", count = 2 }, { name = "Sorrowmoss", count = 2 }, { name = "Crystal Vial", count = 1 } } },
    ["Elixir of Dream Vision"] = { spellId = 0, reagents = { { name = "Purple Lotus", count = 3 }, { name = "Crystal Vial", count = 1 } } },
    ["Elixir of Giants"] = { spellId = 0, reagents = { { name = "Sungrass", count = 1 } } },
    ["Elixir of Greater Firepower"] = { spellId = 0, reagents = { { name = "Fire Oil", count = 3 } } },
    ["Elixir of the Mongoose"] = { spellId = 0, reagents = { { name = "Mountain Silversage", count = 2 }, { name = "Sorrowmoss", count = 2 }, { name = "Crystal Vial", count = 1 } } },
    ["Elixir of the Sages"] = { spellId = 0, reagents = { { name = "Dreamfoil", count = 1 }, { name = "Sorrowmoss", count = 2 }, { name = "Crystal Vial", count = 1 } } },
    ["Flask of Distilled Wisdom"] = { spellId = 0, reagents = { { name = "Dreamfoil", count = 30 }, { name = "Icecap", count = 10 }, { name = "Black Lotus", count = 1 }, { name = "Crystal Vial", count = 1 }  } },
    ["Flask of Supreme Power"] = { spellId = 0, reagents = { { name = "Dreamfoil", count = 30 }, { name = "Mountain Silversage", count = 10 }, { name = "Black Lotus", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Flask of the Titans"] = { spellId = 0, reagents = { { name = "Gromsblood", count = 30 }, { name = "Stonescale Oil", count = 10 }, { name = "Black Lotus", count = 1 }, { name = "Crystal Vial", count = 1 }  } },
    ["Flask of Petrification"] = { spellId = 0, reagents = { { name = "Stonescale Oil", count = 30 }, { name = "Mountain Silversage", count = 10 }, { name = "Black Lotus", count = 1 }, { name = "Crystal Vial", count = 1 }  } },
    ["Flask of Chromatic Resistance"] = { spellId = 0, reagents = { { name = "Icecap", count = 30 }, { name = "Mountain Silversage", count = 10 }, { name = "Black Lotus", count = 1 }, { name = "Crystal Vial", count = 1 }  } },
    ["Ghost Dye"] = { spellId = 0, reagents = { { name = "Ghost Dye", count = 1 }, { name = "Ghost Mushroom", count = 2 }, { name = "Purple Dye", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Gift of Arthas"] = { spellId = 0, reagents = { { name = "Arthas' Tears", count = 1 }, { name = "Blindweed", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Greater Arcane Elixir"] = { spellId = 0, reagents = { { name = "Dreamfoil", count = 3 }, { name = "Mountain Silversage", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Greater Arcane Protection Potion"] = { spellId = 0, reagents = { { name = "Dream Dust", count = 1 }, { name = "Dreamfoil", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Greater Dreamless Sleep Potion"] = { spellId = 0, reagents = { { name = "Greater Dreamless Sleep Potion", count = 1 } } },
    ["Greater Fire Protection Potion"] = { spellId = 0, reagents = { { name = "Elemental Fire", count = 1 }, { name = "Dreamfoil", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Greater Frost Protection Potion"] = { spellId = 0, reagents = { { name = "Elemental Water", count = 1 }, { name = "Dreamfoil", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Greater Nature Protection Potion"] = { spellId = 0, reagents = { { name = "Elemental Earth", count = 1 }, { name = "Dreamfoil", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Greater Shadow Protection Potion"] = { spellId = 0, reagents = { { name = "Shadow Oil", count = 1 }, { name = "Dreamfoil", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Greater Stoneshield Potion"] = { spellId = 0, reagents = { { name = "Stonescale Oil", count = 3 }, { name = "Thorium Ore", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Invisibility Potion"] = { spellId = 0, reagents = { { name = "Crystal Vial", count = 1 } } },
    ["Limited Invulnerability Potion"] = { spellId = 0, reagents = { { name = "Blindweed", count = 2 }, { name = "Ghost Mushroom", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Living Action Potion"] = { spellId = 0, reagents = { { name = "Living Action Potion", count = 1 } } },
    ["Mageblood Elixir"] = { spellId = 0, reagents = { { name = "Mageblood Elixir", count = 1 } } },
    ["Major Mana Potion"] = { spellId = 0, reagents = { { name = "Dreamfoil", count = 3 }, { name = "Icecap", count = 2 }, { name = "Crystal Vial", count = 1 } } },
    ["Major Rejuvenation Potion"] = { spellId = 0, reagents = { { name = "Heart of the Wild (crafting reagent)", count = 1 }, { name = "Golden Sansam", count = 4 }, { name = "Dreamfoil", count = 4 }, { name = "Crystal Vial", count = 1 } } },
    ["Major Troll's Blood Potion"] = { spellId = 0, reagents = { { name = "Major Troll's Blood Elixir", count = 1 } } },
    ["Mighty Rage Potion"] = { spellId = 0, reagents = { { name = "Gromsblood", count = 3 }, { name = "Crystal Vial", count = 1 } } },
    ["Potion of Petrification"] = { spellId = 0, reagents = { { name = "Stonescale Oil", count = 7 }, { name = "Crystal Vial", count = 1 } } },
    ["Transmute Air to Fire"] = { spellId = 0, reagents = { { name = "Essence of Fire", count = 1 } } },
    ["Transmute Earth to Life"] = { spellId = 0, reagents = { { name = "Essence of Earth", count = 1 } } },
    ["Transmute Earth to Water"] = { spellId = 0, reagents = { { name = "Essence of Water", count = 1 } } },
    ["Transmute Elemental Fire"] = { spellId = 0, reagents = { { name = "Elemental Fire", count = 3 } } },
    ["Transmute Life to Earth"] = { spellId = 0, reagents = { { name = "Living Essence", count = 1 } } },
    ["Transmute Undeath to Water"] = { spellId = 0, reagents = { { name = "Essence of Undeath", count = 1 } } },
    ["Transmute Water to Undeath"] = { spellId = 0, reagents = { { name = "Essence of Water", count = 1 } } },
    ["Restorative Potion"] = { spellId = 0, reagents = { { name = "Elemental Earth", count = 1 }, { name = "Goldthorn", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Shadow Oil"] = { spellId = 0, reagents = { { name = "Fadeleaf", count = 4 }, { name = "Grave Moss", count = 4 }, { name = "Crystal Vial", count = 1 } } },
    ["Shadow Protection Potion"] = { spellId = 0, reagents = { { name = "Grave Moss", count = 1 }, { name = "Kingsblood", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Strong Troll's Blood Elixir"] = { spellId = 0, reagents = { { name = "Bruiseweed", count = 2 }, { name = "Briarthorn", count = 2 }, { name = "Crystal Vial", count = 1 } } },
    ["Super Rejuvenation Potion"] = { spellId = 0, reagents = { { name = "Mana Thistle", count = 2 }, { name = "Dreaming Glory", count = 1 }, { name = "Netherbloom", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Superior Healing Potion"] = { spellId = 0, reagents = { { name = "Sungrass", count = 1 }, { name = "Khadgar's Whisker", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Swiftness Potion"] = { spellId = 0, reagents = { { name = "Swiftthistle", count = 1 }, { name = "Briarthorn", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Swim Speed Potion"] = { spellId = 0, reagents = { { name = "Swiftthistle", count = 1 }, { name = "Blackmouth Oil", count = 1 }, { name = "Crystal Vial", count = 1 } } },
    ["Truesilver Bar"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 1 } } },
    ["Weak Troll's Blood Elixir"] = { spellId = 0, reagents = { { name = "Peacebloom", count = 1 }, { name = "Earthroot", count = 2 }, { name = "Crystal Vial", count = 1 } } },
    ["Wildvine Potion"] = { spellId = 0, reagents = { { name = "Wildvine", count = 1 }, { name = "Purple Lotus", count = 1 }, { name = "Crystal Vial", count = 1 } } },
}
