GuildShoppingList_BlacksmithingPlans  = {
    ["Copper Bracers"] = { spellId = 0, reagents = { { name = "Copper Bar", count = 2 } } },
    ["Rough Copper Vest"] = { spellId = 0, reagents = { { name = "Copper Bar", count = 4 } } },
    ["Rough Sharpening Stone"] = { spellId = 0, reagents = { { name = "Rough Stone", count = 1 } } },
    ["Copper Mace"] = { spellId = 0, reagents = { { name = "Copper Bar", count = 6 }, { name = "Weak Flux", count = 1 }, { name = "Linen Cloth", count = 2 } } },
    ["Copper Axe"] = { spellId = 0, reagents = { { name = "Copper Bar", count = 6 }, { name = "Weak Flux", count = 1 }, { name = "Linen Cloth", count = 2 } } },
    ["Copper Chain Boots"] = { spellId = 0, reagents = { { name = "Copper Bar", count = 8 } } },
    ["Copper Shortsword"] = { spellId = 0, reagents = { { name = "Copper Bar", count = 6 }, { name = "Weak Flux", count = 1 }, { name = "Linen Cloth", count = 2 } } },
    ["Rough Grinding Stone"] = { spellId = 0, reagents = { { name = "Rough Stone", count = 2 } } },
    ["Copper Claymore"] = { spellId = 0, reagents = { { name = "Copper Bar", count = 10 }, { name = "Weak Flux", count = 2 }, { name = "Rough Grinding Stone", count = 1 }, { name = "Light Leather", count = 1 } } },
    ["Copper Dagger"] = { spellId = 0, reagents = { { name = "Copper Bar", count = 6 }, { name = "Weak Flux", count = 1 }, { name = "Rough Grinding Stone", count = 1 }, { name = "Light Leather", count = 1 } } },
    ["Copper Battle Axe"] = { spellId = 0, reagents = { { name = "Copper Bar", count = 12 }, { name = "Weak Flux", count = 2 }, { name = "Malachite", count = 2 }, { name = "Rough Grinding Stone", count = 2 }, { name = "Light Leather", count = 2 } } },
    ["Copper Chain Belt"] = { spellId = 0, reagents = { { name = "Copper Bar", count = 6 } } },
    ["Copper Chain Vest"] = { spellId = 0, reagents = { { name = "Copper Bar", count = 8 }, { name = "Rough Grinding Stone", count = 2 } } },
    ["Heavy Copper Longsword"] = { spellId = 0, reagents = { { name = "Copper Bar", count = 10 }, { name = "Tigerseye", count = 1 }, { name = "Rough Grinding Stone", count = 2 } } },
    ["Runed Copper Gauntlets"] = { spellId = 0, reagents = { { name = "Copper Bar", count = 8 }, { name = "Rough Grinding Stone", count = 2 } } },
    ["Runed Copper Pants"] = { spellId = 0, reagents = { { name = "Copper Bar", count = 8 }, { name = "Fine Thread", count = 2 }, { name = "Rough Grinding Stone", count = 3 } } },
    ["Gemmed Copper Gauntlets"] = { spellId = 0, reagents = { { name = "Copper Bar", count = 8 }, { name = "Tigerseye", count = 1 }, { name = "Malachite", count = 1 } } },
    ["Heavy Copper Maul"] = { spellId = 0, reagents = { { name = "Copper Bar", count = 12 }, { name = "Weak Flux", count = 2 }, { name = "Light Leather", count = 2 } } },
    ["Thick War Axe"] = { spellId = 0, reagents = { { name = "Copper Bar", count = 10 }, { name = "Weak Flux", count = 2 }, { name = "Silver Bar", count = 2 }, { name = "Rough Grinding Stone", count = 2 }, { name = "Light Leather", count = 2 } } },
    ["Runed Copper Belt"] = { spellId = 0, reagents = { { name = "Copper Bar", count = 10 } } },
    ["Runed Copper Breastplate"] = { spellId = 0, reagents = { { name = "Copper Bar", count = 12 }, { name = "Shadowgem", count = 1 }, { name = "Rough Grinding Stone", count = 2 } } },
    ["Runed Copper Bracers"] = { spellId = 0, reagents = { { name = "Copper Bar", count = 10 }, { name = "Rough Grinding Stone", count = 3 } } },
    ["Heavy Copper Broadsword"] = { spellId = 0, reagents = { { name = "Copper Bar", count = 14 }, { name = "Weak Flux", count = 2 }, { name = "Tigerseye", count = 2 }, { name = "Medium Leather", count = 2 } } },
    ["Rough Bronze Boots"] = { spellId = 0, reagents = { { name = "Bronze Bar", count = 6 }, { name = "Rough Grinding Stone", count = 6 } } },
    ["Ironforge Breastplate"] = { spellId = 0, reagents = { { name = "Bronze Bar", count = 16 }, { name = "Tigerseye", count = 2 }, { name = "Rough Grinding Stone", count = 3 } } },
    ["Silver Skeleton Key"] = { spellId = 0, reagents = { { name = "Silver Bar", count = 1 }, { name = "Rough Grinding Stone", count = 1 } } },
    ["Thick Bronze Darts"] = { spellId = 0, reagents = { { name = "Bronze Bar", count = 6 }, { name = "Rough Grinding Stone", count = 2 }, { name = "Medium Leather", count = 1 } } },
    ["Silver Rod"] = { spellId = 0, reagents = { { name = "Silver Bar", count = 1 }, { name = "Rough Grinding Stone", count = 2 } } },
    ["Big Bronze Knife"] = { spellId = 0, reagents = { { name = "Bronze Bar", count = 6 }, { name = "Weak Flux", count = 4 }, { name = "Rough Grinding Stone", count = 2 }, { name = "Tigerseye", count = 1 }, { name = "Medium Leather", count = 1 } } },
    ["Rough Bronze Leggings"] = { spellId = 0, reagents = { { name = "Bronze Bar", count = 6 } } },
    ["Pearl-Handled Dagger"] = { spellId = 0, reagents = { { name = "Bronze Bar", count = 6 }, { name = "Strong Flux", count = 1 }, { name = "Small Lustrous Pearl", count = 2 }, { name = "Coarse Grinding Stone", count = 2 } } },
    ["Bronze Mace"] = { spellId = 0, reagents = { { name = "Bronze Bar", count = 6 }, { name = "Weak Flux", count = 4 }, { name = "Medium Leather", count = 1 } } },
    ["Bronze Axe"] = { spellId = 0, reagents = { { name = "Bronze Bar", count = 7 }, { name = "Weak Flux", count = 4 }, { name = "Medium Leather", count = 1 } } },
    ["Patterned Bronze Bracers"] = { spellId = 0, reagents = { { name = "Bronze Bar", count = 5 }, { name = "Coarse Grinding Stone", count = 2 } } },
    ["Bronze Shortsword"] = { spellId = 0, reagents = { { name = "Bronze Bar", count = 5 }, { name = "Weak Flux", count = 4 }, { name = "Medium Leather", count = 2 } } },
    ["Deadly Bronze Poniard"] = { spellId = 0, reagents = { { name = "Bronze Bar", count = 4 }, { name = "Strong Flux", count = 1 }, { name = "Swiftness Potion", count = 1 }, { name = "Shadowgem", count = 2 }, { name = "Coarse Grinding Stone", count = 2 }, { name = "Medium Leather", count = 2 } } },
    ["Bronze Warhammer"] = { spellId = 0, reagents = { { name = "Bronze Bar", count = 8 }, { name = "Strong Flux", count = 1 }, { name = "Medium Leather", count = 1 } } },
    ["Heavy Grinding Stone"] = { spellId = 0, reagents = { { name = "Heavy Stone", count = 3 } } },
    ["Heavy Bronze Mace"] = { spellId = 0, reagents = { { name = "Bronze Bar", count = 8 }, { name = "Strong Flux", count = 1 }, { name = "Moss Agate", count = 1 }, { name = "Shadowgem", count = 1 }, { name = "Coarse Grinding Stone", count = 2 }, { name = "Medium Leather", count = 2 } } },
    ["Silvered Bronze Boots"] = { spellId = 0, reagents = { { name = "Bronze Bar", count = 6 }, { name = "Silver Bar", count = 1 }, { name = "Coarse Grinding Stone", count = 2 } } },
    ["Bronze Greatsword"] = { spellId = 0, reagents = { { name = "Bronze Bar", count = 12 }, { name = "Strong Flux", count = 2 }, { name = "Medium Leather", count = 2 } } },
    ["Silvered Bronze Gauntlets"] = { spellId = 0, reagents = { { name = "Bronze Bar", count = 8 }, { name = "Silver Bar", count = 1 }, { name = "Coarse Grinding Stone", count = 2 } } },
    ["Bronze Battle Axe"] = { spellId = 0, reagents = { { name = "Bronze Bar", count = 14 }, { name = "Strong Flux", count = 1 }, { name = "Medium Leather", count = 2 } } },
    ["Iridescent Hammer"] = { spellId = 0, reagents = { { name = "Bronze Bar", count = 10 }, { name = "Strong Flux", count = 1 }, { name = "Iridescent Pearl", count = 1 }, { name = "Coarse Grinding Stone", count = 2 }, { name = "Medium Leather", count = 2 } } },
    ["Green Iron Boots"] = { spellId = 0, reagents = { { name = "Iron Bar", count = 6 }, { name = "Coarse Grinding Stone", count = 2 }, { name = "Green Dye", count = 1 } } },
    ["Mighty Iron Hammer"] = { spellId = 0, reagents = { { name = "Iron Bar", count = 6 }, { name = "Strong Flux", count = 2 }, { name = "Elixir of Ogre's Strength", count = 1 }, { name = "Lesser Moonstone", count = 2 }, { name = "Coarse Grinding Stone", count = 2 }, { name = "Medium Leather", count = 2 } } },
    ["Golden Skeleton Key"] = { spellId = 0, reagents = { { name = "Gold Bar", count = 1 }, { name = "Heavy Grinding Stone", count = 1 } } },
    ["Green Iron Gauntlets"] = { spellId = 0, reagents = { { name = "Iron Bar", count = 4 }, { name = "Small Lustrous Pearl", count = 2 }, { name = "Coarse Grinding Stone", count = 2 }, { name = "Green Dye", count = 1 } } },
    ["Golden Rod"] = { spellId = 0, reagents = { { name = "Gold Bar", count = 1 }, { name = "Coarse Grinding Stone", count = 2 } } },
    ["Iron Buckle"] = { spellId = 0, reagents = { { name = "Iron Bar", count = 1 } } },
    ["Iron Shield Spike"] = { spellId = 0, reagents = { { name = "Iron Bar", count = 6 }, { name = "Coarse Grinding Stone", count = 4 } } },
    ["Green Iron Leggings"] = { spellId = 0, reagents = { { name = "Iron Bar", count = 8 }, { name = "Heavy Grinding Stone", count = 1 }, { name = "Green Dye", count = 1 } } },
    ["Silvered Bronze Leggings"] = { spellId = 0, reagents = { { name = "Bronze Bar", count = 12 }, { name = "Silver Bar", count = 4 }, { name = "Coarse Grinding Stone", count = 2 } } },
    ["Solid Iron Maul"] = { spellId = 0, reagents = { { name = "Iron Bar", count = 8 }, { name = "Strong Flux", count = 2 }, { name = "Heavy Grinding Stone", count = 1 }, { name = "Silver Bar", count = 4 }, { name = "Heavy Leather", count = 2 } } },
    ["Green Iron Shoulders"] = { spellId = 0, reagents = { { name = "Iron Bar", count = 7 }, { name = "Heavy Grinding Stone", count = 1 }, { name = "Green Dye", count = 1 } } },
    ["Hardened Iron Shortsword"] = { spellId = 0, reagents = { { name = "Iron Bar", count = 6 }, { name = "Strong Flux", count = 2 }, { name = "Heavy Grinding Stone", count = 1 }, { name = "Lesser Moonstone", count = 2 }, { name = "Heavy Leather", count = 3 } } },
    ["Green Iron Bracers"] = { spellId = 0, reagents = { { name = "Iron Bar", count = 6 }, { name = "Green Dye", count = 1 } } },
    ["Iron Counterweight"] = { spellId = 0, reagents = { { name = "Iron Bar", count = 4 }, { name = "Coarse Grinding Stone", count = 2 }, { name = "Lesser Moonstone", count = 1 } } },
    ["Golden Iron Destroyer"] = { spellId = 0, reagents = { { name = "Iron Bar", count = 10 }, { name = "Gold Bar", count = 4 }, { name = "Lesser Moonstone", count = 2 }, { name = "Strong Flux", count = 2 }, { name = "Heavy Leather", count = 2 }, { name = "Heavy Grinding Stone", count = 2 } } },
    ["Golden Scale Leggings"] = { spellId = 0, reagents = { { name = "Iron Bar", count = 10 }, { name = "Gold Bar", count = 2 }, { name = "Heavy Grinding Stone", count = 1 } } },
    ["Golden Scale Shoulders"] = { spellId = 0, reagents = { { name = "Steel Bar", count = 6 }, { name = "Gold Bar", count = 2 }, { name = "Heavy Grinding Stone", count = 1 } } },
    ["Jade Serpentblade"] = { spellId = 0, reagents = { { name = "Iron Bar", count = 8 }, { name = "Strong Flux", count = 2 }, { name = "Heavy Grinding Stone", count = 2 }, { name = "Jade", count = 2 }, { name = "Heavy Leather", count = 3 } } },
    ["Green Iron Hauberk"] = { spellId = 0, reagents = { { name = "Iron Bar<br />4x [[Heavy Grinding Stone", count = 20 }, { name = "Jade", count = 2 }, { name = "Moss Agate", count = 2 }, { name = "Green Leather Armor", count = 1 } } },
    ["Barbaric Iron Boots"] = { spellId = 0, reagents = { { name = "Iron Bar", count = 12 }, { name = "Large Fang", count = 4 }, { name = "Heavy Grinding Stone", count = 2 } } },
    ["Glinting Steel Dagger"] = { spellId = 0, reagents = { { name = "Steel Bar", count = 10 }, { name = "Strong Flux", count = 2 }, { name = "Moss Agate", count = 1 }, { name = "Elemental Earth", count = 1 }, { name = "Heavy Leather", count = 1 } } },
    ["Moonsteel Broadsword"] = { spellId = 0, reagents = { { name = "Steel Bar", count = 8 }, { name = "Strong Flux", count = 2 }, { name = "Heavy Grinding Stone", count = 2 }, { name = "Lesser Moonstone", count = 3 }, { name = "Heavy Leather", count = 3 } } },
    ["Barbaric Iron Gloves"] = { spellId = 0, reagents = { { name = "Iron Bar", count = 14 }, { name = "Heavy Grinding Stone", count = 3 }, { name = "Large Fang", count = 2 } } },
    ["Massive Iron Axe"] = { spellId = 0, reagents = { { name = "Iron Bar", count = 14 }, { name = "Strong Flux", count = 2 }, { name = "Heavy Grinding Stone", count = 2 }, { name = "Gold Bar", count = 4 }, { name = "Heavy Leather", count = 2 } } },
    ["Polished Steel Boots"] = { spellId = 0, reagents = { { name = "Steel Bar", count = 8 }, { name = "Citrine", count = 1 }, { name = "Lesser Moonstone", count = 1 }, { name = "Heavy Grinding Stone", count = 2 } } },
    ["Golden Scale Bracers"] = { spellId = 0, reagents = { { name = "Steel Bar", count = 5 }, { name = "Heavy Grinding Stone", count = 2 } } },
    ["Edge of Winter"] = { spellId = 0, reagents = { { name = "Steel Bar", count = 10 }, { name = "Frost Oil", count = 1 }, { name = "Elemental Water", count = 2 }, { name = "Elemental Air", count = 2 }, { name = "Heavy Leather", count = 2 } } },
    ["Golden Scale Coif"] = { spellId = 0, reagents = { { name = "Steel Bar", count = 8 }, { name = "Gold Bar", count = 2 }, { name = "Heavy Grinding Stone", count = 2 } } },
    ["Searing Golden Blade"] = { spellId = 0, reagents = { { name = "Steel Bar", count = 10 }, { name = "Gold Bar", count = 4 }, { name = "Elemental Fire", count = 2 }, { name = "Heavy Leather", count = 2 } } },
    ["Steel Weapon Chain"] = { spellId = 0, reagents = { { name = "Steel Bar", count = 8 }, { name = "Heavy Grinding Stone", count = 2 }, { name = "Heavy Leather", count = 4 } } },
    ["Golden Scale Cuirass"] = { spellId = 0, reagents = { { name = "Steel Bar", count = 12 }, { name = "Gold Bar", count = 2 }, { name = "Heavy Grinding Stone", count = 4 } } },
    ["Frost Tiger Blade"] = { spellId = 0, reagents = { { name = "Steel Bar", count = 8 }, { name = "Strong Flux", count = 2 }, { name = "Heavy Grinding Stone", count = 2 }, { name = "Jade", count = 2 }, { name = "Frost Oil", count = 1 }, { name = "Heavy Leather", count = 4 } } },
    ["Golden Scale Boots"] = { spellId = 0, reagents = { { name = "Steel Bar", count = 10 }, { name = "Gold Bar", count = 4 }, { name = "Heavy Grinding Stone", count = 4 } } },
    ["Shadow Crescent Axe"] = { spellId = 0, reagents = { { name = "Steel Bar", count = 10 }, { name = "Strong Flux", count = 2 }, { name = "Heavy Grinding Stone", count = 3 }, { name = "Citrine", count = 2 }, { name = "Shadow Oil", count = 1 }, { name = "Heavy Leather", count = 3 } } },
    ["Truesilver Skeleton Key"] = { spellId = 0, reagents = { { name = "Truesilver Bar", count = 1 }, { name = "Solid Grinding Stone", count = 1 } } },
    ["Whirling Steel Axes"] = { spellId = 0, reagents = { { name = "Steel Bar", count = 5 }, { name = "Elemental Air", count = 2 }, { name = "Heavy Grinding Stone", count = 2 }, { name = "Heavy Leather", count = 1 } } },
    ["Inlaid Mithril Cylinder"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 5 }, { name = "Gold Bar", count = 1 }, { name = "Truesilver Bar", count = 1 } } },
    ["Truesilver Rod"] = { spellId = 0, reagents = { { name = "Truesilver Bar", count = 1 }, { name = "Heavy Grinding Stone", count = 1 } } },
    ["Golden Scale Gauntlets"] = { spellId = 0, reagents = { { name = "Steel Bar", count = 10 }, { name = "Gold Bar", count = 4 }, { name = "Heavy Grinding Stone", count = 4 } } },
    ["Heavy Mithril Gauntlet"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 6 }, { name = "Mageweave Cloth", count = 4 } } },
    ["Heavy Mithril Axe"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 12 }, { name = "Citrine", count = 2 }, { name = "Solid Grinding Stone", count = 1 }, { name = "Heavy Leather", count = 4 } } },
    ["Heavy Mithril Pants"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 10 } } },
    ["Mithril Scale Pants"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 12 } } },
    ["Mithril Scale Bracers"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 8 } } },
    ["Mithril Shield Spike"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 4 }, { name = "Truesilver Bar", count = 2 }, { name = "Solid Grinding Stone", count = 4 } } },
    ["Blue Glittering Axe"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 16 }, { name = "Aquamarine", count = 2 }, { name = "Solid Grinding Stone", count = 1 }, { name = "Thick Leather", count = 4 } } },
    ["Ornate Mithril Gloves"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 10 }, { name = "Mageweave Cloth", count = 6 }, { name = "Solid Grinding Stone", count = 1 }, { name = "Truesilver Bar", count = 1 } } },
    ["Ornate Mithril Pants"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 12 }, { name = "Solid Grinding Stone", count = 1 }, { name = "Truesilver Bar", count = 1 } } },
    ["Truesilver Gauntlets"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 10 }, { name = "Truesilver Bar", count = 8 }, { name = "Aquamarine", count = 3 }, { name = "Citrine", count = 3 }, { name = "Guardian Gloves", count = 1 }, { name = "Solid Grinding Stone", count = 2 } } },
    ["Ornate Mithril Shoulder"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 12 }, { name = "Thick Leather", count = 6 }, { name = "Truesilver Bar", count = 1 } } },
    ["Wicked Mithril Blade"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 14 }, { name = "Truesilver Bar", count = 4 }, { name = "Solid Grinding Stone", count = 1 }, { name = "Thick Leather", count = 2 } } },
    ["Big Black Mace"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 16 }, { name = "Black Pearl", count = 1 }, { name = "Shadowgem", count = 4 }, { name = "Solid Grinding Stone", count = 1 }, { name = "Thick Leather", count = 2 } } },
    ["Orcish War Leggings"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 12 }, { name = "Elemental Earth", count = 1 } } },
    ["Ornate Mithril Breastplate"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 16 }, { name = "Truesilver Bar", count = 6 }, { name = "Heart of Fire", count = 1 }, { name = "Solid Grinding Stone", count = 1 } } },
    ["Mithril Coif"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 10 }, { name = "Mageweave Cloth", count = 6 } } },
    ["Ornate Mithril Boots"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 14 }, { name = "Truesilver Bar", count = 2 }, { name = "Citrine", count = 5 }, { name = "Aquamarine", count = 5 }, { name = "Solid Grinding Stone", count = 1 }, { name = "Thick Leather", count = 4 } } },
    ["The Shatterer"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 24 }, { name = "Core of Earth", count = 4 }, { name = "Truesilver Bar", count = 6 }, { name = "Citrine", count = 5 }, { name = "Jade", count = 5 }, { name = "Solid Grinding Stone", count = 4 }, { name = "Thick Leather", count = 4 } } },
    ["Heavy Mithril Boots"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 14 }, { name = "Thick Leather", count = 4 } } },
    ["Mithril Scale Shoulders"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 14 }, { name = "Thick Leather", count = 4 } } },
    ["Mithril Spurs"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 4 }, { name = "Solid Grinding Stone", count = 3 } } },
    ["Dazzling Mithril Rapier"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 14 }, { name = "Aquamarine", count = 1 }, { name = "Lesser Moonstone", count = 2 }, { name = "Moss Agate", count = 2 }, { name = "Solid Grinding Stone", count = 1 }, { name = "Mageweave Cloth", count = 2 } } },
    ["Phantom Blade"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 28 }, { name = "Breath of Wind", count = 6 }, { name = "Truesilver Bar", count = 8 }, { name = "Lesser Invisibility Potion", count = 2 }, { name = "Aquamarine", count = 6 }, { name = "Solid Grinding Stone", count = 4 }, { name = "Thick Leather", count = 2 } } },
    ["Ornate Mithril Helm"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 16 }, { name = "Truesilver Bar", count = 2 }, { name = "Solid Grinding Stone", count = 1 } } },
    ["Runed Mithril Hammer"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 18 }, { name = "Core of Earth", count = 2 }, { name = "Solid Grinding Stone", count = 1 }, { name = "Thick Leather", count = 4 } } },
    ["Blight (polearm)"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 28 }, { name = "Ichor of Undeath", count = 10 }, { name = "Truesilver Bar", count = 10 }, { name = "Solid Grinding Stone", count = 6 }, { name = "Thick Leather", count = 6 } } },
    ["Thorium Belt"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 8 } } },
    ["Dense Grinding Stone"] = { spellId = 0, reagents = { { name = "Dense Stone", count = 4 } } },
    ["Dense Sharpening Stone"] = { spellId = 0, reagents = { { name = "Dense Stone", count = 1 } } },
    ["Dense Weightstone"] = { spellId = 0, reagents = { { name = "Dense Stone", count = 1 }, { name = "Runecloth", count = 1 } } },
    ["Ebon Shiv"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 12 }, { name = "Truesilver Bar", count = 6 }, { name = "Star Ruby", count = 2 }, { name = "Solid Grinding Stone", count = 1 }, { name = "Thick Leather", count = 2 } } },
    ["Thorium Bracers"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 8 } } },
    ["Earthforged Leggings"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 16 }, { name = "Core of Earth", count = 2 } } },
    ["Light Earthforged Blade"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 12 }, { name = "Core of Earth", count = 4 } } },
    ["Light Emberforged Hammer"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 12 }, { name = "Heart of Fire", count = 4 } } },
    ["Light Skyforged Axe"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 12 }, { name = "Breath of Wind", count = 4 } } },
    ["Truesilver Champion"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 30 }, { name = "Truesilver Bar", count = 16 }, { name = "Star Ruby", count = 6 }, { name = "Breath of Wind", count = 4 }, { name = "Solid Grinding Stone", count = 8 }, { name = "Thick Leather", count = 6 } } },
    ["Windforged Leggings"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 16 }, { name = "Breath of Wind", count = 2 } } },
    ["Radiant Belt"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 10 }, { name = "Heart of Fire", count = 2 } } },
    ["Dark Iron Pulverizer"] = { spellId = 0, reagents = { { name = "Dark Iron Bar", count = 18 }, { name = "Heart of Fire", count = 4 } } },
    ["Imperial Plate Belt"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 10 }, { name = "Rugged Leather", count = 6 } } },
    ["Imperial Plate Shoulders"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 12 }, { name = "Rugged Leather", count = 6 } } },
    ["Wildthorn Mail"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 40 }, { name = "Enchanted Thorium Bar", count = 2 }, { name = "Living Essence", count = 4 }, { name = "Wildvine", count = 4 }, { name = "Huge Emerald", count = 1 } } },
    ["Dark Iron Mail"] = { spellId = 0, reagents = { { name = "Dark Iron Bar", count = 10 }, { name = "Heart of Fire", count = 2 } } },
    ["Imperial Plate Bracers"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 12 } } },
    ["Radiant Breastplate"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 18 }, { name = "Heart of Fire", count = 2 }, { name = "Star Ruby", count = 1 } } },
    ["Dark Iron Sunderer"] = { spellId = 0, reagents = { { name = "Dark Iron Bar", count = 26 }, { name = "Heart of Fire", count = 4 } } },
    ["Dawn's Edge"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 30 }, { name = "Enchanted Thorium Bar", count = 4 }, { name = "Star Ruby", count = 4 }, { name = "Blue Sapphire", count = 4 }, { name = "Dense Grinding Stone", count = 2 }, { name = "Rugged Leather", count = 4 } } },
    ["Arcanite Skeleton Key"] = { spellId = 0, reagents = { { name = "Arcanite Bar", count = 1 }, { name = "Dense Grinding Stone", count = 1 } } },
    ["Ornate Thorium Handaxe"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 20 }, { name = "Large Opal", count = 2 }, { name = "Dense Grinding Stone", count = 2 }, { name = "Rugged Leather", count = 4 } } },
    ["Thorium Shield Spike"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 4 }, { name = "Dense Grinding Stone", count = 4 }, { name = "Essence of Earth", count = 2 } } },
    ["Arcanite Rod"] = { spellId = 0, reagents = { { name = "Arcanite Bar", count = 3 }, { name = "Dense Grinding Stone", count = 1 } } },
    ["Blazing Rapier"] = { spellId = 0, reagents = { { name = "Enchanted Thorium Bar", count = 10 }, { name = "Essence of Fire", count = 4 }, { name = "Heart of Fire", count = 2 }, { name = "Azerothian Diamond", count = 2 }, { name = "Dense Grinding Stone", count = 2 } } },
    ["Enchanted Battlehammer"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 20 }, { name = "Enchanted Thorium Bar", count = 6 }, { name = "Huge Emerald", count = 2 }, { name = "Powerful Mojo", count = 4 }, { name = "Rugged Leather", count = 4 } } },
    ["Dark Iron Shoulders"] = { spellId = 0, reagents = { { name = "Dark Iron Bar", count = 6 }, { name = "Heart of Fire", count = 1 } } },
    ["Huge Thorium Battleaxe"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 40 }, { name = "Dense Grinding Stone", count = 6 }, { name = "Rugged Leather", count = 6 } } },
    ["Thorium Boots"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 12 }, { name = "Rugged Leather", count = 8 } } },
    ["Thorium Helm"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 24 }, { name = "Star Ruby", count = 1 } } },
    ["Dark Iron Plate"] = { spellId = 0, reagents = { { name = "Dark Iron Bar", count = 20 }, { name = "Heart of Fire", count = 8 } } },
    ["Demon Forged Breastplate"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 40 }, { name = "Demonic Rune", count = 10 }, { name = "Blue Sapphire", count = 4 }, { name = "Star Ruby", count = 4 } } },
    ["Serenity (mace)"] = { spellId = 0, reagents = { { name = "Enchanted Thorium Bar", count = 6 }, { name = "Arcanite Bar", count = 2 }, { name = "Powerful Mojo", count = 4 }, { name = "Large Opal", count = 2 }, { name = "Blue Sapphire", count = 2 }, { name = "Huge Emerald", count = 1 } } },
    ["Radiant Gloves"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 18 }, { name = "Heart of Fire", count = 4 } } },
    ["Corruption (sword)"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 40 }, { name = "Arcanite Bar", count = 2 }, { name = "Demonic Rune", count = 16 }, { name = "Essence of Undeath", count = 8 }, { name = "Blue Sapphire", count = 2 }, { name = "Dense Grinding Stone", count = 2 }, { name = "Rugged Leather", count = 4 } } },
    ["Dawnbringer Shoulders"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 20 }, { name = "Arcanite Bar", count = 4 }, { name = "Huge Emerald", count = 2 }, { name = "Essence of Water", count = 2 } } },
    ["Fiery Plate Gauntlets"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 20 }, { name = "Enchanted Thorium Bar", count = 6 }, { name = "Essence of Fire", count = 2 }, { name = "Star Ruby", count = 4 } } },
    ["Girdle of the Dawn"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 8 }, { name = "Truesilver Bar", count = 6 }, { name = "Righteous Orb", count = 1 } } },
    ["Heavy Timbermaw Belt"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 12 }, { name = "Essence of Earth", count = 3 }, { name = "Living Essence", count = 3 } } },
    ["Radiant Boots"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 14 }, { name = "Heart of Fire", count = 4 } } },
    ["Volcanic Hammer"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 30 }, { name = "Heart of Fire", count = 4 }, { name = "Star Ruby", count = 4 }, { name = "Rugged Leather", count = 4 } } },
    ["Dark Iron Bracers"] = { spellId = 0, reagents = { { name = "Dark Iron Bar", count = 4 }, { name = "Fiery Core", count = 2 }, { name = "Lava Core", count = 2 } } },
    ["Fiery Chain Girdle"] = { spellId = 0, reagents = { { name = "Dark Iron Bar", count = 6 }, { name = "Fiery Core", count = 3 }, { name = "Lava Core", count = 3 } } },
    ["Storm Gauntlets"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 20 }, { name = "Enchanted Thorium Bar", count = 4 }, { name = "Essence of Water", count = 4 }, { name = "Blue Sapphire", count = 4 } } },
    ["Imperial Plate Boots"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 18 } } },
    ["Imperial Plate Helm"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 18 }, { name = "Star Ruby", count = 1 } } },
    ["Radiant Circlet"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 18 }, { name = "Heart of Fire", count = 4 } } },
    ["Black Amnesty"] = { spellId = 0, reagents = { { name = "Lava Core", count = 3 }, { name = "Fiery Core", count = 6 }, { name = "Arcanite Bar", count = 12 }, { name = "Blood of the Mountain", count = 1 }, { name = "Dark Iron Bar", count = 4 } } },
    ["Black Grasp of the Destroyer"] = { spellId = 0, reagents = { { name = "Large Obsidian Shard", count = 8 }, { name = "Small Obsidian Shard", count = 24 }, { name = "Enchanted Leather", count = 8 }, { name = "Flask of Supreme Power", count = 1 } } },
    ["Blackfury"] = { spellId = 0, reagents = { { name = "Lava Core", count = 5 }, { name = "Fiery Core", count = 2 }, { name = "Arcanite Bar", count = 16 }, { name = "Dark Iron Bar", count = 6 } } },
    ["Blackguard"] = { spellId = 0, reagents = { { name = "Lava Core", count = 6 }, { name = "Fiery Core", count = 6 }, { name = "Arcanite Bar", count = 10 }, { name = "Dark Iron Bar", count = 6 }, { name = "Guardian Stone", count = 12 } } },
    ["Dark Iron Boots"] = { spellId = 0, reagents = { { name = "Lava Core", count = 3 }, { name = "Fiery Core", count = 3 }, { name = "Core Leather", count = 4 }, { name = "Dark Iron Bar", count = 6 } } },
    ["Dark Iron Gauntlets"] = { spellId = 0, reagents = { { name = "Lava Core", count = 3 }, { name = "Fiery Core", count = 5 }, { name = "Core Leather", count = 4 }, { name = "Dark Iron Bar", count = 4 }, { name = "Blood of the Mountain", count = 2 } } },
    ["Dark Iron Helm"] = { spellId = 0, reagents = { { name = "Lava Core", count = 4 }, { name = "Fiery Core", count = 2 }, { name = "Dark Iron Bar", count = 4 } } },
    ["Dark Iron Leggings"] = { spellId = 0, reagents = { { name = "Lava Core", count = 6 }, { name = "Fiery Core", count = 4 }, { name = "Dark Iron Bar", count = 16 } } },
    ["Ebon Hand"] = { spellId = 0, reagents = { { name = "Lava Core", count = 4 }, { name = "Fiery Core", count = 7 }, { name = "Arcanite Bar", count = 12 }, { name = "Dark Iron Bar", count = 8 }, { name = "Azerothian Diamond", count = 4 } } },
    ["Fiery Chain Shoulders"] = { spellId = 0, reagents = { { name = "Lava Core", count = 5 }, { name = "Fiery Core", count = 4 }, { name = "Dark Iron Bar", count = 16 } } },
    ["Icebane Bracers"] = { spellId = 0, reagents = { { name = "Frozen Rune", count = 4 }, { name = "Thorium Bar", count = 12 }, { name = "Arcanite Bar", count = 2 }, { name = "Essence of Water", count = 2 } } },
    ["Icebane Breastplate"] = { spellId = 0, reagents = { { name = "Frozen Rune", count = 7 }, { name = "Thorium Bar", count = 16 }, { name = "Arcanite Bar", count = 2 }, { name = "Essence of Water", count = 4 } } },
    ["Icebane Gauntlets"] = { spellId = 0, reagents = { { name = "Frozen Rune", count = 5 }, { name = "Thorium Bar", count = 12 }, { name = "Arcanite Bar", count = 2 }, { name = "Essence of Water", count = 2 } } },
    ["Invulnerable Mail"] = { spellId = 0, reagents = { { name = "Arcanite Bar", count = 30 }, { name = "Enchanted Thorium Bar", count = 30 }, { name = "Huge Emerald", count = 6 }, { name = "Azerothian Diamond", count = 6 } } },
    ["Jagged Obsidian Shield"] = { spellId = 0, reagents = { { name = "Large Obsidian Shard", count = 8 }, { name = "Small Obsidian Shard", count = 24 }, { name = "Enchanted Thorium Bar", count = 8 } } },
    ["Lionheart Helm"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 80 }, { name = "Arcanite Bar", count = 12 }, { name = "Wicked Claw", count = 40 }, { name = "Blue Sapphire", count = 10 }, { name = "Azerothian Diamond", count = 4 } } },
    ["Nightfall (axe)"] = { spellId = 0, reagents = { { name = "Lava Core", count = 8 }, { name = "Fiery Core", count = 5 }, { name = "Arcanite Bar", count = 10 }, { name = "Dark Iron Bar", count = 12 }, { name = "Huge Emerald", count = 4 } } },
    ["Obsidian Mail Tunic"] = { spellId = 0, reagents = { { name = "Large Obsidian Shard", count = 15 }, { name = "Small Obsidian Shard", count = 36 }, { name = "Enchanted Leather", count = 12 }, { name = "Guardian Stone", count = 10 }, { name = "Azerothian Diamond", count = 4 } } },
    ["Persuader"] = { spellId = 0, reagents = { { name = "Arcanite Bar", count = 15 }, { name = "Dark Iron Bar", count = 10 }, { name = "Essence of Undeath", count = 20 }, { name = "Dark Rune", count = 20 }, { name = "Devilsaur Leather", count = 10 }, { name = "Skin of Shadow", count = 2 } } },
    ["Sageblade"] = { spellId = 0, reagents = { { name = "Arcanite Bar", count = 12 }, { name = "Nexus Crystal", count = 2 }, { name = "Flask of Supreme Power", count = 2 }, { name = "Enchanted Leather", count = 4 } } },
    ["Stronghold Gauntlets"] = { spellId = 0, reagents = { { name = "Arcanite Bar", count = 15 }, { name = "Enchanted Thorium Bar", count = 20 }, { name = "Essence of Earth", count = 10 }, { name = "Blue Sapphire", count = 4 }, { name = "Large Opal", count = 4 } } },
    ["Sulfuron Hammer"] = { spellId = 0, reagents = { { name = "Sulfuron Ingot", count = 8 }, { name = "Dark Iron Bar", count = 20 }, { name = "Arcanite Bar", count = 50 }, { name = "Essence of Fire", count = 25 }, { name = "Blood of the Mountain", count = 10 }, { name = "Lava Core", count = 10 }, { name = "Fiery Core", count = 10 } } },
    ["Thick Obsidian Breastplate"] = { spellId = 0, reagents = { { name = "Large Obsidian Shard", count = 18 }, { name = "Small Obsidian Shard", count = 40 }, { name = "Enchanted Thorium Bar", count = 12 }, { name = "Essence of Earth", count = 10 }, { name = "Huge Emerald", count = 4 } } },
    ["Titanic Leggings"] = { spellId = 0, reagents = { { name = "Arcanite Bar", count = 12 }, { name = "Enchanted Thorium Bar", count = 20 }, { name = "Essence of Earth", count = 10 }, { name = "Flask of the Titans", count = 2 } } },
    ["Annihilator"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 40 }, { name = "Arcanite Bar", count = 12 }, { name = "Essence of Undeath", count = 10 }, { name = "Huge Emerald", count = 8 }, { name = "Dense Grinding Stone", count = 2 }, { name = "Enchanted Leather", count = 4 } } },
    ["Arcanite Champion"] = { spellId = 0, reagents = { { name = "Arcanite Bar", count = 15 }, { name = "Azerothian Diamond", count = 8 }, { name = "Righteous Orb", count = 1 }, { name = "Large Opal", count = 4 }, { name = "Enchanted Leather", count = 8 }, { name = "Dense Grinding Stone", count = 2 } } },
    ["Arcanite Reaper"] = { spellId = 0, reagents = { { name = "Arcanite Bar", count = 20 }, { name = "Enchanted Leather", count = 6 }, { name = "Dense Grinding Stone", count = 2 } } },
    ["Bloodsoul Breastplate"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 20 }, { name = "Souldarite", count = 10 }, { name = "Bloodvine", count = 2 }, { name = "Star Ruby", count = 2 } } },
    ["Bloodsoul Gauntlets"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 12 }, { name = "Souldarite", count = 6 }, { name = "Bloodvine", count = 2 }, { name = "Enchanted Leather", count = 4 } } },
    ["Bloodsoul Shoulders"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 16 }, { name = "Souldarite", count = 8 }, { name = "Bloodvine", count = 2 }, { name = "Star Ruby", count = 1 } } },
    ["Dark Iron Destroyer"] = { spellId = 0, reagents = { { name = "Dark Iron Bar", count = 18 }, { name = "Lava Core", count = 12 }, { name = "Blood of the Mountain", count = 2 }, { name = "Enchanted Leather", count = 2 } } },
    ["Dark Iron Reaver"] = { spellId = 0, reagents = { { name = "Dark Iron Bar", count = 16 }, { name = "Fiery Core", count = 12 }, { name = "Blood of the Mountain", count = 2 }, { name = "Enchanted Leather", count = 2 } } },
    ["Darkrune Breastplate"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 20 }, { name = "Truesilver Bar", count = 10 }, { name = "Dark Rune", count = 10 } } },
    ["Darkrune Gauntlets"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 12 }, { name = "Truesilver Bar", count = 6 }, { name = "Dark Rune", count = 6 }, { name = "Enchanted Leather", count = 2 } } },
    ["Darkrune Helm"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 16 }, { name = "Truesilver Bar", count = 8 }, { name = "Dark Rune", count = 8 }, { name = "Black Diamond", count = 1 } } },
    ["Darksoul Breastplate"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 20 }, { name = "Souldarite", count = 14 }, { name = "Large Opal", count = 2 } } },
    ["Darksoul Leggings"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 18 }, { name = "Souldarite", count = 12 }, { name = "Large Opal", count = 2 } } },
    ["Darksoul Shoulders"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 16 }, { name = "Souldarite", count = 10 }, { name = "Large Opal", count = 1 } } },
    ["Enchanted Thorium Breastplate"] = { spellId = 0, reagents = { { name = "Arcanite Bar", count = 8 }, { name = "Enchanted Thorium Bar", count = 24 }, { name = "Essence of Earth", count = 4 }, { name = "Essence of Water", count = 4 }, { name = "Huge Emerald", count = 2 }, { name = "Azerothian Diamond", count = 2 } } },
    ["Enchanted Thorium Helm"] = { spellId = 0, reagents = { { name = "Arcanite Bar", count = 6 }, { name = "Enchanted Thorium Bar", count = 16 }, { name = "Essence of Earth", count = 6 }, { name = "Large Opal", count = 2 }, { name = "Azerothian Diamond", count = 1 } } },
    ["Enchanted Thorium Leggings"] = { spellId = 0, reagents = { { name = "Arcanite Bar", count = 10 }, { name = "Enchanted Thorium Bar", count = 20 }, { name = "Essence of Water", count = 6 }, { name = "Blue Sapphire", count = 2 }, { name = "Huge Emerald", count = 1 } } },
    ["Frostguard"] = { spellId = 0, reagents = { { name = "Arcanite Bar", count = 18 }, { name = "Blue Sapphire", count = 8 }, { name = "Azerothian Diamond", count = 8 }, { name = "Essence of Water", count = 4 }, { name = "Dense Grinding Stone", count = 2 }, { name = "Enchanted Leather", count = 4 } } },
    ["Gloves of the Dawn"] = { spellId = 0, reagents = { { name = "Arcanite Bar", count = 2 }, { name = "Truesilver Bar", count = 10 }, { name = "Righteous Orb", count = 1 } } },
    ["Hammer of the Titans"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 50 }, { name = "Arcanite Bar", count = 15 }, { name = "Guardian Stone", count = 4 }, { name = "Enchanted Leather", count = 6 }, { name = "Essence of Earth", count = 10 } } },
    ["Heartseeker"] = { spellId = 0, reagents = { { name = "Arcanite Bar", count = 10 }, { name = "Enchanted Thorium Bar", count = 10 }, { name = "Enchanted Leather", count = 2 }, { name = "Star Ruby", count = 6 }, { name = "Azerothian Diamond", count = 6 }, { name = "Large Opal", count = 6 }, { name = "Dense Grinding Stone", count = 4 } } },
    ["Heavy Obsidian Belt"] = { spellId = 0, reagents = { { name = "Small Obsidian Shard", count = 14 }, { name = "Enchanted Thorium Bar", count = 4 }, { name = "Essence of Earth", count = 2 } } },
    ["Heavy Timbermaw Boots"] = { spellId = 0, reagents = { { name = "Arcanite Bar", count = 4 }, { name = "Essence of Earth", count = 6 }, { name = "Living Essence", count = 6 } } },
    ["Helm of the Great Chief"] = { spellId = 0, reagents = { { name = "Arcanite Bar", count = 40 }, { name = "Enchanted Thorium Bar", count = 4 }, { name = "Jet Black Feather", count = 60 }, { name = "Large Opal", count = 6 }, { name = "Huge Emerald", count = 2 } } },
    ["Ironvine Belt"] = { spellId = 0, reagents = { { name = "Enchanted Thorium Bar", count = 6 }, { name = "Living Essence", count = 2 } } },
    ["Ironvine Breastplate"] = { spellId = 0, reagents = { { name = "Enchanted Thorium Bar", count = 12 }, { name = "Bloodvine", count = 2 }, { name = "Arcanite Bar", count = 2 }, { name = "Living Essence", count = 2 } } },
    ["Ironvine Gloves"] = { spellId = 0, reagents = { { name = "Enchanted Thorium Bar", count = 8 }, { name = "Bloodvine", count = 1 }, { name = "Living Essence", count = 2 } } },
    ["Light Obsidian Belt"] = { spellId = 0, reagents = { { name = "Small Obsidian Shard", count = 14 }, { name = "Enchanted Leather", count = 4 } } },
    ["Masterwork Stormhammer"] = { spellId = 0, reagents = { { name = "Enchanted Thorium Bar", count = 20 }, { name = "Huge Emerald", count = 8 }, { name = "Large Opal", count = 8 }, { name = "Essence of Earth", count = 6 }, { name = "Enchanted Leather", count = 4 } } },
    ["Whitesoul Helm"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 20 }, { name = "Enchanted Thorium Bar", count = 4 }, { name = "Truesilver Bar", count = 6 }, { name = "Gold Bar", count = 6 }, { name = "Azerothian Diamond", count = 2 } } },
    ["Elemental Sharpening Stone"] = { spellId = 0, reagents = { { name = "Elemental Earth", count = 2 }, { name = "Dense Stone", count = 3 } } },
    ["Enchanted Thorium Blades"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 6 }, { name = "Enchanted Thorium Bar", count = 2 }, { name = "Rugged Leather", count = 1 } } },
    ["Imperial Plate Chest"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 20 } } },
    ["Imperial Plate Leggings"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 24 } } },
    ["Radiant Leggings"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 20 }, { name = "Heart of Fire", count = 4 } } },
    ["Runic Breastplate"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 40 }, { name = "Arcanite Bar", count = 2 }, { name = "Star Ruby", count = 1 } } },
    ["Runic Plate Boots"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 20 }, { name = "Arcanite Bar", count = 2 }, { name = "Silver Bar", count = 10 } } },
    ["Runic Plate Helm"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 30 }, { name = "Arcanite Bar", count = 2 }, { name = "Truesilver Bar", count = 2 }, { name = "Huge Emerald", count = 1 } } },
    ["Runic Plate Leggings"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 40 }, { name = "Arcanite Bar", count = 2 }, { name = "Star Ruby", count = 1 } } },
    ["Runic Plate Shoulders"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 20 }, { name = "Arcanite Bar", count = 2 }, { name = "Gold Bar", count = 6 } } },
    ["Thorium Leggings"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 26 }, { name = "Red Power Crystal", count = 4 } } },
}
