GuildShoppingList_CookingRecipes  = {
    ["Recipe: Savory Deviate Delight"] = { spellId = 0, reagents = { { name = "Deviate Fish", count = 1 } } },
    ["Recipe: Thistle Tea"] = { spellId = 0, reagents = { { name = "Swiftthistle", count = 1 }, { name = "Refreshing Spring Water", count = 1 } } },
    ["Recipe: Dragonbreath Chili"] = { spellId = 0, reagents = { { name = "Mystery Meat", count = 1 }, { name = "Small Flame Sac", count = 1 } } },
    ["Recipe: Captain Rumsey's Lager"] = { spellId = 0, reagents = { { name = "Skin of Dwarven Stout", count = 1 }, { name = "Flagon of Dwarven Mead", count = 1 } } },
    ["Recipe: Charred Wolf Meat"] = { spellId = 0, reagents = { { name = "Stringy Wolf Meat", count = 1 } } },
    ["Recipe: Spiced Wolf Meat"] = { spellId = 0, reagents = { { name = "Stringy Wolf Meat", count = 1 } } },
    ["Recipe: Roasted Boar Meat"] = { spellId = 0, reagents = { { name = "Chunk of Boar Meat", count = 1 } } },
    ["Recipe: Coyote Steak"] = { spellId = 0, reagents = { { name = "Coyote Meat", count = 1 } } },
    ["Recipe: Goretusk Liver Pie"] = { spellId = 0, reagents = { { name = "Goretusk Liver", count = 1 } } },
    ["Recipe: Westfall Stew"] = { spellId = 0, reagents = { { name = "Chunk of Boar Meat", count = 1 }, { name = "Refreshing Spring Water", count = 1 } } },
    ["Recipe: Crab Cake"] = { spellId = 0, reagents = { { name = "Crawler Meat", count = 1 } } },
    ["Recipe: Cooked Crab Claw"] = { spellId = 0, reagents = { { name = "Crawler Claw", count = 1 } } },
    ["Recipe: Dry Pork Ribs"] = { spellId = 0, reagents = { { name = "Boar Ribs", count = 1 } } },
    ["Recipe: Redridge Goulash"] = { spellId = 0, reagents = { { name = "Tough Condor Meat", count = 1 } } },
    ["Recipe: Succulent Pork Ribs"] = { spellId = 0, reagents = { { name = "Boar Ribs", count = 2 } } },
    ["Recipe: Seasoned Wolf Kabob"] = { spellId = 0, reagents = { { name = "Lean Wolf Flank", count = 2 } } },
    ["Recipe: Beer Basted Boar Ribs"] = { spellId = 0, reagents = { { name = "Crag Boar Rib", count = 1 } } },
    ["Recipe: Crocolisk Steak"] = { spellId = 0, reagents = { { name = "Crocolisk Meat", count = 1 } } },
    ["Recipe: Blood Sausage"] = { spellId = 0, reagents = { { name = "Bear Meat", count = 1 } } },
    ["Recipe: Murloc Fin Soup"] = { spellId = 0, reagents = { { name = "Murloc Fin", count = 2 } } },
    ["Recipe: Crocolisk Gumbo"] = { spellId = 0, reagents = { { name = "Tender Crocolisk Meat", count = 1 } } },
    ["Recipe: Curiously Tasty Omelet"] = { spellId = 0, reagents = { { name = "Raptor Egg", count = 1 } } },
    ["Recipe: Gooey Spider Cake"] = { spellId = 0, reagents = { { name = "Gooey Spider Leg", count = 2 } } },
    ["Recipe: Hot Lion Chops"] = { spellId = 0, reagents = { { name = "Lion Meat", count = 1 } } },
    ["Recipe: Tasty Lion Steak"] = { spellId = 0, reagents = { { name = "Lion Meat", count = 2 } } },
    ["Recipe: Soothing Turtle Bisque"] = { spellId = 0, reagents = { { name = "Turtle Meat", count = 1 } } },
    ["Recipe: Barbecued Buzzard Wing"] = { spellId = 0, reagents = { { name = "Buzzard Wing", count = 1 } } },
    ["Recipe: Scorpid Surprise"] = { spellId = 0, reagents = { { name = "Scorpid Stinger", count = 1 } } },
    ["Recipe: Roasted Kodo Meat"] = { spellId = 0, reagents = { { name = "Kodo Meat", count = 1 } } },
    ["Recipe: Fillet of Frenzy"] = { spellId = 0, reagents = { { name = "Soft Frenzy Flesh", count = 1 } } },
    ["Recipe: Strider Stew"] = { spellId = 0, reagents = { { name = "Strider Meat", count = 1 } } },
    ["Recipe: Crispy Lizard Tail"] = { spellId = 0, reagents = { { name = "Thunder Lizard Tail", count = 1 } } },
    ["Recipe: Lean Venison"] = { spellId = 0, reagents = { { name = "Stag Meat", count = 1 } } },
    ["Recipe: Clam Chowder"] = { spellId = 0, reagents = { { name = "Clam Meat", count = 1 }, { name = "Ice Cold Milk", count = 1 } } },
    ["Recipe: Goblin Deviled Clams"] = { spellId = 0, reagents = { { name = "Tangy Clam Meat", count = 1 } } },
    ["Recipe: Boiled Clams"] = { spellId = 0, reagents = { { name = "Clam Meat", count = 1 }, { name = "Refreshing Spring Water", count = 1 } } },
    ["Recipe: Giant Clam Scorcho"] = { spellId = 0, reagents = { { name = "Giant Clam Meat", count = 1 } } },
    ["Recipe: Brilliant Smallfish"] = { spellId = 0, reagents = { { name = "Raw Brilliant Smallfish", count = 1 } } },
    ["Recipe: Longjaw Mud Snapper"] = { spellId = 0, reagents = { { name = "Raw Longjaw Mud Snapper", count = 1 } } },
    ["Recipe: Loch Frenzy Delight"] = { spellId = 0, reagents = { { name = "Raw Loch Frenzy", count = 1 } } },
    ["Recipe: Bristle Whisker Catfish"] = { spellId = 0, reagents = { { name = "Raw Bristle Whisker Catfish", count = 1 } } },
    ["Recipe: Rainbow Fin Albacore"] = { spellId = 0, reagents = { { name = "Raw Rainbow Fin Albacore", count = 1 } } },
    ["Recipe: Rockscale Cod"] = { spellId = 0, reagents = { { name = "Raw Rockscale Cod", count = 1 } } },
    ["Recipe: Herb Baked Egg"] = { spellId = 0, reagents = { { name = "Small Egg", count = 1 } } },
    ["Recipe: Smoked Bear Meat"] = { spellId = 0, reagents = { { name = "Bear Meat", count = 1 } } },
    ["Recipe: Crispy Bat Wing"] = { spellId = 0, reagents = { { name = "Meaty Bat Wing", count = 1 } } },
    ["Recipe: Lean Wolf Steak"] = { spellId = 0, reagents = { { name = "Lean Wolf Flank", count = 1 } } },
    ["Recipe: Roast Raptor"] = { spellId = 0, reagents = { { name = "Raptor Flesh", count = 1 } } },
    ["Recipe: Hot Wolf Ribs"] = { spellId = 0, reagents = { { name = "Red Wolf Meat", count = 1 } } },
    ["Recipe: Jungle Stew"] = { spellId = 0, reagents = { { name = "Tiger Meat", count = 1 }, { name = "Refreshing Spring Water", count = 1 } } },
    ["Recipe: Carrion Surprise"] = { spellId = 0, reagents = { { name = "Mystery Meat", count = 1 } } },
    ["Recipe: Mystery Stew"] = { spellId = 0, reagents = { { name = "Mystery Meat", count = 1 }, { name = "Skin of Dwarven Stout", count = 1 } } },
    ["Recipe: Heavy Kodo Stew"] = { spellId = 0, reagents = { { name = "Heavy Kodo Meat", count = 2 } } },
    ["Recipe: Spiced Chili Crab"] = { spellId = 0, reagents = { { name = "Tender Crab Meat", count = 1 } } },
    ["Recipe: Monster Omelet"] = { spellId = 0, reagents = { { name = "Giant Egg", count = 1 } } },
    ["Recipe: Cooked Glossy Mightfish"] = { spellId = 0, reagents = { { name = "Raw Glossy Mightfish", count = 1 } } },
    ["Recipe: Spotted Yellowtail"] = { spellId = 0, reagents = { { name = "Raw Spotted Yellowtail", count = 1 } } },
    ["Recipe: Filet of Redgill"] = { spellId = 0, reagents = { { name = "Raw Redgill", count = 1 } } },
    ["Recipe: Grilled Squid"] = { spellId = 0, reagents = { { name = "Winter Squid", count = 1 } } },
    ["Recipe: Hot Smoked Bass"] = { spellId = 0, reagents = { { name = "Raw Summer Bass", count = 1 } } },
    ["Recipe: Nightfin Soup"] = { spellId = 0, reagents = { { name = "Raw Nightfin Snapper", count = 1 }, { name = "Refreshing Spring Water", count = 1 } } },
    ["Recipe: Poached Sunscale Salmon"] = { spellId = 0, reagents = { { name = "Raw Sunscale Salmon", count = 1 } } },
    ["Recipe: Lobster Stew"] = { spellId = 0, reagents = { { name = "Darkclaw Lobster", count = 1 }, { name = "Refreshing Spring Water", count = 1 } } },
    ["Recipe: Mightfish Steak"] = { spellId = 0, reagents = { { name = "Large Raw Mightfish", count = 1 } } },
    ["Recipe: Baked Salmon"] = { spellId = 0, reagents = { { name = "Raw Whitescale Salmon", count = 1 } } },
    ["Recipe: Undermine Clam Chowder"] = { spellId = 0, reagents = { { name = "Zesty Clam Meat", count = 2 } } },
    ["Recipe: Mithril Head Trout"] = { spellId = 0, reagents = { { name = "Raw Mithril Head Trout", count = 1 } } },
    ["Recipe: Spider Sausage"] = { spellId = 0, reagents = { { name = "White Spider Meat", count = 2 } } },
    ["Recipe: Tender Wolf Steak"] = { spellId = 0, reagents = { { name = "Tender Wolf Meat", count = 1 } } },
    ["Recipe: Runn Tum Tuber Surprise"] = { spellId = 0, reagents = { { name = "Runn Tum Tuber", count = 1 } } },
    ["Recipe: Heavy Crocolisk Stew"] = { spellId = 0, reagents = { { name = "Tender Crocolisk Meat", count = 2 } } },
    ["Recipe: Smoked Desert Dumplings"] = { spellId = 0, reagents = { { name = "Sandworm Meat", count = 1 } } },
    ["Recipe: Dirge's Kickin' Chimaerok Chops"] = { spellId = 0, reagents = { { name = "Goblin Rocket Fuel", count = 1 }, { name = "Deeprock Salt", count = 1 }, { name = "Chimaerok Tenderloin", count = 1 } } },
    ["Recipe: Smoked Sagefish"] = { spellId = 0, reagents = { { name = "Raw Sagefish", count = 1 } } },
    ["Recipe: Sagefish Delight"] = { spellId = 0, reagents = { { name = "Raw Greater Sagefish", count = 1 } } },
    ["Recipe: Crunchy Spider Surprise"] = { spellId = 0, reagents = { { name = "Crunchy Spider Leg", count = 1 } } },
    ["Recipe: Lynx Steak"] = { spellId = 0, reagents = { { name = "Lynx Meat", count = 1 } } },
    ["Recipe: Bat Bites"] = { spellId = 0, reagents = { { name = "Bat Flesh", count = 1 } } },
    ["Recipe: Delicious Chocolate Cake"] = { spellId = 0, reagents = { { name = "Simple Flour", count = 8 }, { name = "Ice Cold Milk", count = 4 }, { name = "Mild Spices", count = 4 }, { name = "Small Egg", count = 4 }, { name = "Flask of Stormwind Tawny", count = 4 }, { name = "Mageroyal", count = 4 } } },
    ["Recipe: Goldthorn Tea"] = { spellId = 0, reagents = { { name = "Goldthorn", count = 1 }, { name = "Refreshing Spring Water", count = 1 } } },
    ["Recipe: Charred Bear Kabobs"] = { spellId = 0, reagents = { { name = "Bear Flank", count = 1 } } },
    ["Recipe: Juicy Bear Burger"] = { spellId = 0, reagents = { { name = "Bear Flank", count = 1 } } },
    ["Recipe: Clamlette Magnifique"] = { spellId = 0, reagents = { { name = "Zesty Clam Meat", count = 1 } } },
    ["Recipe: Lemon Herb Filet"] = { spellId = 0, reagents = { { name = "Darkmoon Daggermaw", count = 2 } } },
    ["Recipe: Sugar-Crusted Fish Feast"] = { spellId = 0, reagents = { { name = "Darkmoon Daggermaw", count = 5 } } },
    ["Recipe: Fancy Darkmoon Feast"] = { spellId = 0, reagents = { { name = "Darkmoon Daggermaw", count = 10 } } },
    ["Recipe: Extra Sugary Fish Feast"] = { spellId = 0, reagents = { { name = "Darkmoon Daggermaw", count = 5 } } },
    ["Recipe: Winter Veil Egg Nog"] = { spellId = 0, reagents = { { name = "Small Egg", count = 1 }, { name = "Ice Cold Milk", count = 1 }, { name = "Holiday Spirits", count = 1 }, { name = "Holiday Spices", count = 1 } } },
    ["Recipe: Gingerbread Cookie"] = { spellId = 0, reagents = { { name = "Small Egg", count = 1 }, { name = "Holiday Spices", count = 1 } } },
    ["Recipe: Hot Apple Cider"] = { spellId = 0, reagents = { { name = "Sparkling Apple Cider", count = 1 }, { name = "Holiday Spirits", count = 1 }, { name = "Holiday Spices", count = 1 } } },
}
