GuildShoppingList_EnchantingFormulae  = {
    ["Advanced Herbalism"] = { spellId = 0, reagents = { { name = "Vision Dust", count = 3 }, { name = "Sungrass", count = 3 } } },
    ["Advanced Mining"] = { spellId = 0, reagents = { { name = "Vision Dust", count = 3 }, { name = "Truesilver Bar", count = 3 } } },
    ["Agility (boots enchant)"] = { spellId = 0, reagents = { { name = "Greater Eternal Essence", count = 2 } } },
    ["Agility (gloves enchant)"] = { spellId = 0, reagents = { { name = "Lesser Nether Essence", count = 1 }, { name = "Vision Dust", count = 1 } } },
    ["Agility (two-handed weapon enchant)"] = { spellId = 0, reagents = { { name = "Essence of Air", count = 4 }, { name = "Large Brilliant Shard", count = 6 } } },
    ["Agility (weapon enchant)"] = { spellId = 0, reagents = { { name = "Essence of Air", count = 4 }, { name = "Large Brilliant Shard", count = 4 } } },
    --["Argent Versatility"] = { spellId = 0, reagents = { { name = "Rich Illusion Dust", count = 4 }, { name = "Greater Eternal Essence", count = 4 }, { name = "Essence of Water", count = 2 } } },
    ["Brilliant Mana Oil"] = { spellId = 0, reagents = { { name = "Purple Lotus", count = 3 }, { name = "Crystal Vial", count = 1 }, { name = "Large Brilliant Shard", count = 2 } } },
    ["Brilliant Wizard Oil"] = { spellId = 0, reagents = { { name = "Firebloom", count = 3 }, { name = "Crystal Vial", count = 1 }, { name = "Large Brilliant Shard", count = 2 } } },
    ["Crusader (enchant)"] = { spellId = 0, reagents = { { name = "Righteous Orb", count = 2 }, { name = "Large Brilliant Shard", count = 4 } } },
    ["Defense (enchant)"] = { spellId = 0, reagents = { { name = "Light Illusion Dust", count = 3 }, { name = "Small Brilliant Shard", count = 1 } } },
    ["Demonslaying"] = { spellId = 0, reagents = { { name = "Rich Illusion Dust", count = 2 }, { name = "Elixir of Demonslaying", count = 1 }, { name = "Large Brilliant Shard", count = 1 } } },
    ["Dodge (bracers enchant)"] = { spellId = 0, reagents = { { name = "Rich Illusion Dust", count = 2 }, { name = "Greater Eternal Essence", count = 2 } } },
    ["Enchanted Leather"] = { spellId = 0, reagents = { { name = "Rugged Leather", count = 1 }, { name = "Greater Eternal Essence", count = 3 } } },
    ["Fiery Weapon"] = { spellId = 0, reagents = { { name = "Essence of Fire", count = 1 }, { name = "Large Brilliant Shard", count = 4 } } },
    ["Fire Power"] = { spellId = 0, reagents = { { name = "Essence of Fire", count = 4 }, { name = "Large Brilliant Shard", count = 10 } } },
    ["Fishing (enchant)"] = { spellId = 0, reagents = { { name = "Light Illusion Dust", count = 2 }, { name = "Blackmouth Oil", count = 3 } } },
    ["Frost Power"] = { spellId = 0, reagents = { { name = "Essence of Water", count = 4 }, { name = "Large Brilliant Shard", count = 10 } } },
    ["Greater Agility (boots enchant)"] = { spellId = 0, reagents = { { name = "Greater Eternal Essence", count = 4 }, { name = "Wildvine", count = 2 } } },
    ["Greater Agility (gloves enchant)"] = { spellId = 0, reagents = { { name = "Rich Illusion Dust", count = 3 }, { name = "Greater Eternal Essence", count = 3 } } },
    ["Greater Defense"] = { spellId = 0, reagents = { { name = "Vision Dust", count = 3 } } },
    ["Greater Health"] = { spellId = 0, reagents = { { name = "Light Illusion Dust", count = 3 } } },
    ["Greater Impact"] = { spellId = 0, reagents = { { name = "Rich Illusion Dust", count = 2 }, { name = "Large Brilliant Shard", count = 2 } } },
    ["Greater Intellect (bracers enchant)"] = { spellId = 0, reagents = { { name = "Greater Eternal Essence", count = 3 } } },
    ["Greater Magic Wand"] = { spellId = 0, reagents = { { name = "Simple Wood", count = 1 }, { name = "Greater Magic Essence", count = 1 } } },
    ["Greater Mana"] = { spellId = 0, reagents = { { name = "Greater Mystic Essence", count = 1 } } },
    ["Greater Mystic Wand"] = { spellId = 0, reagents = { { name = "Greater Mystic Essence", count = 1 }, { name = "Vision Dust", count = 1 }, { name = "Star Wood", count = 1 } } },
    ["Greater Stamina (boots enchant)"] = { spellId = 0, reagents = { { name = "Rich Illusion Dust", count = 4 } } },
    ["Greater Stamina (bracers enchant)"] = { spellId = 0, reagents = { { name = "Rich Illusion Dust", count = 3 } } },
    ["Greater Stamina (shield enchant)"] = { spellId = 0, reagents = { { name = "Rich Illusion Dust", count = 4 } } },
    ["Greater Stats (chest enchant)"] = { spellId = 0, reagents = { { name = "Rich Illusion Dust", count = 6 }, { name = "Large Brilliant Shard", count = 4 } } },
    ["Greater Strength (bracers enchant)"] = { spellId = 0, reagents = { { name = "Rich Illusion Dust", count = 2 }, { name = "Greater Eternal Essence", count = 2 } } },
    ["Greater Strength (gloves enchant)"] = { spellId = 0, reagents = { { name = "Rich Illusion Dust", count = 4 }, { name = "Greater Eternal Essence", count = 4 } } },
    ["Greater Striking"] = { spellId = 0, reagents = { { name = "Greater Eternal Essence", count = 2 }, { name = "Large Brilliant Shard", count = 2 } } },
    --["Greater Versatility (bracers enchant)"] = { spellId = 0, reagents = { { name = "Lesser Nether Essence", count = 3 }, { name = "Vision Dust", count = 1 } } },
    --["Greater Versatility (shield enchant)"] = { spellId = 0, reagents = { { name = "Rich Illusion Dust", count = 2 }, { name = "Greater Eternal Essence", count = 2 } } },
    ["Healing Power (bracers enchant)"] = { spellId = 0, reagents = { { name = "Rich Illusion Dust", count = 5 }, { name = "Greater Eternal Essence", count = 3 }, { name = "Large Brilliant Shard", count = 4 } } },
    ["Healing Power (gloves enchant)"] = { spellId = 0, reagents = { { name = "Righteous Orb", count = 1 }, { name = "Large Brilliant Shard", count = 8 } } },
    ["Healing Power (weapon enchant)"] = { spellId = 0, reagents = { { name = "Greater Eternal Essence", count = 4 }, { name = "Large Brilliant Shard", count = 4 }, { name = "Essence of Water", count = 4 } } },
    ["Health (enchant)"] = { spellId = 0, reagents = { { name = "Light Illusion Dust", count = 4 }, { name = "Lesser Eternal Essence", count = 1 } } },
    ["Herbalism (enchant)"] = { spellId = 0, reagents = { { name = "Light Illusion Dust", count = 1 }, { name = "Kingsblood", count = 3 } } },
    ["Icy Chill"] = { spellId = 0, reagents = { { name = "Icecap", count = 1 }, { name = "Essence of Air", count = 1 }, { name = "Essence of Water", count = 1 }, { name = "Large Brilliant Shard", count = 4 } } },
    ["Impact"] = { spellId = 0, reagents = { { name = "Large Glowing Shard", count = 1 }, { name = "Vision Dust", count = 4 } } },
    ["Intellect (bracers enchant)"] = { spellId = 0, reagents = { { name = "Lesser Nether Essence", count = 2 } } },
    ["Lesser Absorption"] = { spellId = 0, reagents = { { name = "Light Illusion Dust", count = 2 }, { name = "Lesser Eternal Essence", count = 1 }, { name = "Small Brilliant Shard", count = 1 } } },
    ["Lesser Agility (boots enchant)"] = { spellId = 0, reagents = { { name = "Light Illusion Dust", count = 1 }, { name = "Lesser Eternal Essence", count = 2 } } },
    ["Lesser Agility (cloak enchant)"] = { spellId = 0, reagents = { { name = "Lesser Nether Essence", count = 2 } } },
    ["Lesser Beastslayer"] = { spellId = 0, reagents = { { name = "Large Fang", count = 2 }, { name = "Lesser Eternal Essence", count = 4 }, { name = "Small Brilliant Shard", count = 1 } } },
    ["Lesser Dodge (bracers enchant)"] = { spellId = 0, reagents = { { name = "Light Illusion Dust", count = 2 }, { name = "Lesser Eternal Essence", count = 4 } } },
    ["Lesser Elemental Slayer"] = { spellId = 0, reagents = { { name = "Small Glowing Shard", count = 1 }, { name = "Lesser Mystic Essence", count = 1 }, { name = "Elemental Earth", count = 1 } } },
    ["Lesser Health"] = { spellId = 0, reagents = { { name = "Strange Dust", count = 2 }, { name = "Lesser Magic Essence", count = 2 } } },
    ["Lesser Impact"] = { spellId = 0, reagents = { { name = "Light Illusion Dust", count = 3 }, { name = "Small Brilliant Shard", count = 1 } } },
    ["Lesser Intellect (bracers enchant)"] = { spellId = 0, reagents = { { name = "Lesser Eternal Essence", count = 2 } } },
    ["Lesser Intellect (weapon enchant)"] = { spellId = 0, reagents = { { name = "Lesser Magic Essence", count = 2 } } },
    ["Lesser Magic Wand"] = { spellId = 0, reagents = { { name = "Simple Wood", count = 1 }, { name = "Lesser Magic Essence", count = 1 } } },
    ["Lesser Mana Oil"] = { spellId = 0, reagents = { { name = "Rich Illusion Dust", count = 3 }, { name = "Purple Lotus", count = 2 }, { name = "Crystal Vial", count = 1 } } },
    ["Lesser Mana"] = { spellId = 0, reagents = { { name = "Greater Magic Essence", count = 1 }, { name = "Lesser Magic Essence", count = 1 } } },
    ["Lesser Mystic Wand"] = { spellId = 0, reagents = { { name = "Light Illusion Dust", count = 3 }, { name = "Star Wood", count = 1 }, { name = "Lesser Eternal Essence", count = 2 } } },
    ["Lesser Parry"] = { spellId = 0, reagents = { { name = "Large Glowing Shard", count = 1 }, { name = "Greater Mystic Essence", count = 2 }, { name = "Vision Dust", count = 2 } } },
    ["Lesser Protection (cloak enchant)"] = { spellId = 0, reagents = { { name = "Light Illusion Dust", count = 6 }, { name = "Small Brilliant Shard", count = 1 } } },
    ["Lesser Protection (shield enchant)"] = { spellId = 0, reagents = { { name = "Light Illusion Dust", count = 1 }, { name = "Lesser Eternal Essence", count = 1 }, { name = "Small Brilliant Shard", count = 1 } } },
    ["Lesser Stamina (boots enchant)"] = { spellId = 0, reagents = { { name = "Light Illusion Dust", count = 4 } } },
    ["Lesser Stamina (bracers enchant)"] = { spellId = 0, reagents = { { name = "Light Illusion Dust", count = 2 } } },
    ["Lesser Stamina (shield enchant)"] = { spellId = 0, reagents = { { name = "Light Illusion Dust", count = 4 }, { name = "Lesser Eternal Essence", count = 2 } } },
    ["Lesser Stats"] = { spellId = 0, reagents = { { name = "Large Glowing Shard", count = 1 }, { name = "Greater Mystic Essence", count = 2 }, { name = "Vision Dust", count = 2 } } },
    ["Lesser Strength"] = { spellId = 0, reagents = { { name = "Light Illusion Dust", count = 2 } } },
    ["Lesser Striking"] = { spellId = 0, reagents = { { name = "Light Illusion Dust", count = 2 }, { name = "Small Brilliant Shard", count = 1 } } },
    --["Lesser Versatility (boots enchant)"] = { spellId = 0, reagents = { { name = "Greater Mystic Essence", count = 1 }, { name = "Lesser Mystic Essence", count = 2 } } },
    --["Lesser Versatility (bracers enchant)"] = { spellId = 0, reagents = { { name = "Lesser Eternal Essence", count = 2 } } },
    --["Lesser Versatility (shield enchant)"] = { spellId = 0, reagents = { { name = "Light Illusion Dust", count = 4 }, { name = "Lesser Eternal Essence", count = 2 } } },
    --["Lesser Versatility (weapon enchant)"] = { spellId = 0, reagents = { { name = "Light Illusion Dust", count = 3 }, { name = "Lesser Eternal Essence", count = 1 } } },
    ["Lesser Wizard Oil"] = { spellId = 0, reagents = { { name = "Vision Dust", count = 3 }, { name = "Crystal Vial", count = 1 } } },
    ["Lifestealing"] = { spellId = 0, reagents = { { name = "Essence of Undeath", count = 4 }, { name = "Living Essence", count = 4 }, { name = "Large Brilliant Shard", count = 4 } } },
    ["Major Health"] = { spellId = 0, reagents = { { name = "Large Brilliant Shard", count = 3 } } },
    ["Major Intellect (two-hand weapon enchant)"] = { spellId = 0, reagents = { { name = "Greater Eternal Essence", count = 4 }, { name = "Large Brilliant Shard", count = 4 } } },
    ["Major Mana"] = { spellId = 0, reagents = { { name = "Rich Illusion Dust", count = 5 } } },
    --["Major Versatility (weapon enchant)"] = { spellId = 0, reagents = { { name = "Greater Eternal Essence", count = 4 }, { name = "Large Brilliant Shard", count = 4 } } },
    ["Mana (enchant)"] = { spellId = 0, reagents = { { name = "Lesser Eternal Essence", count = 3 } } },
    ["Mighty Intellect (weapon enchant)"] = { spellId = 0, reagents = { { name = "Rich Illusion Dust", count = 16 }, { name = "Greater Eternal Essence", count = 5 }, { name = "Large Brilliant Shard", count = 6 } } },
    --["Mighty Versatility (weapon enchant)"] = { spellId = 0, reagents = { { name = "Rich Illusion Dust", count = 12 }, { name = "Greater Eternal Essence", count = 4 }, { name = "Large Brilliant Shard", count = 6 } } },
    ["Mining (enchant)"] = { spellId = 0, reagents = { { name = "Light Illusion Dust", count = 2 }, { name = "Iron Ore", count = 3 } } },
    ["Minor Absorption"] = { spellId = 0, reagents = { { name = "Strange Dust", count = 2 }, { name = "Lesser Magic Essence", count = 1 } } },
    ["Minor Agility (boots enchant)"] = { spellId = 0, reagents = { { name = "Strange Dust", count = 6 }, { name = "Lesser Eternal Essence", count = 2 } } },
    ["Minor Agility (bracers enchant)"] = { spellId = 0, reagents = { { name = "Strange Dust", count = 2 }, { name = "Greater Magic Essence", count = 1 } } },
    ["Minor Agility (cloak enchant)"] = { spellId = 0, reagents = { { name = "Lesser Eternal Essence", count = 1 } } },
    ["Minor Beastslayer"] = { spellId = 0, reagents = { { name = "Strange Dust", count = 4 }, { name = "Greater Magic Essence", count = 2 } } },
    ["Minor Dodge"] = { spellId = 0, reagents = { { name = "Strange Dust", count = 1 }, { name = "Lesser Magic Essence", count = 1 } } },
    ["Minor Haste"] = { spellId = 0, reagents = { { name = "Wildvine", count = 2 }, { name = "Large Brilliant Shard", count = 2 } } },
    ["Minor Health (bracer enchant)"] = { spellId = 0, reagents = { { name = "Strange Dust", count = 1 } } },
    ["Minor Health (chest enchant)"] = { spellId = 0, reagents = { { name = "Strange Dust", count = 1 } } },
    ["Minor Impact"] = { spellId = 0, reagents = { { name = "Strange Dust", count = 4 }, { name = "Greater Magic Essence", count = 2 } } },
    ["Minor Mana Oil"] = { spellId = 0, reagents = { { name = "Light Illusion Dust", count = 3 }, { name = "Crystal Vial", count = 1 } } },
    ["Minor Mana"] = { spellId = 0, reagents = { { name = "Lesser Magic Essence", count = 2 } } },
    ["Minor Protection"] = { spellId = 0, reagents = { { name = "Strange Dust", count = 3 }, { name = "Greater Magic Essence", count = 1 } } },
    ["Minor Speed"] = { spellId = 0, reagents = { { name = "Small Radiant Shard", count = 1 }, { name = "Lesser Nether Essence", count = 1 }, { name = "Aquamarine", count = 1 } } },
    ["Minor Stamina (boots enchant)"] = { spellId = 0, reagents = { { name = "Light Illusion Dust", count = 4 } } },
    ["Minor Stamina (bracers enchant)"] = { spellId = 0, reagents = { { name = "Strange Dust", count = 3 } } },
    ["Minor Stamina (shield enchant)"] = { spellId = 0, reagents = { { name = "Light Illusion Dust", count = 2 }, { name = "Lesser Eternal Essence", count = 1 } } },
    ["Minor Stats"] = { spellId = 0, reagents = { { name = "Light Illusion Dust", count = 1 }, { name = "Lesser Eternal Essence", count = 2 }, { name = "Small Brilliant Shard", count = 1 } } },
    ["Minor Strength"] = { spellId = 0, reagents = { { name = "Strange Dust", count = 5 } } },
    ["Minor Striking"] = { spellId = 0, reagents = { { name = "Strange Dust", count = 4 }, { name = "Greater Magic Essence", count = 2 } } },
    --["Minor Versatility"] = { spellId = 0, reagents = { { name = "Lesser Magic Essence", count = 2 } } },
    ["Minor Wizard Oil"] = { spellId = 0, reagents = { { name = "Strange Dust", count = 2 }, { name = "Crystal Vial", count = 1 } } },
    ["Riding Skill"] = { spellId = 0, reagents = { { name = "Rich Illusion Dust", count = 3 }, { name = "Large Brilliant Shard", count = 2 } } },
    ["Runed Copper Rod"] = { spellId = 0, reagents = { { name = "Strange Dust", count = 1 }, { name = "Copper Rod", count = 1 }, { name = "Lesser Magic Essence", count = 1 } } },
    ["Shadow Power"] = { spellId = 0, reagents = { { name = "Essence of Undeath", count = 6 }, { name = "Large Brilliant Shard", count = 10 } } },
    ["Skinning (enchant)"] = { spellId = 0, reagents = { { name = "Vision Dust", count = 1 }, { name = "Green Whelp Scale", count = 3 } } },
    ["Smoking Heart of the Mountain"] = { spellId = 0, reagents = { { name = "Essence of Fire", count = 3 }, { name = "Large Brilliant Shard", count = 3 } } },
    ["Spellpower (weapon enchant)"] = { spellId = 0, reagents = { { name = "Golden Pearl", count = 2 }, { name = "Greater Eternal Essence", count = 6 }, { name = "Large Brilliant Shard", count = 4 } } },
    ["Stamina (boots enchant)"] = { spellId = 0, reagents = { { name = "Vision Dust", count = 5 } } },
    ["Stamina (bracers enchant)"] = { spellId = 0, reagents = { { name = "Light Illusion Dust", count = 5 } } },
    ["Stamina (shield enchant)"] = { spellId = 0, reagents = { { name = "Vision Dust", count = 5 } } },
    ["Stats (enchant)"] = { spellId = 0, reagents = { { name = "Rich Illusion Dust", count = 2 }, { name = "Greater Eternal Essence", count = 2 }, { name = "Large Brilliant Shard", count = 2 } } },
    ["Strength (bracers enchant)"] = { spellId = 0, reagents = { { name = "Vision Dust", count = 1 } } },
    ["Strength (gloves enchant)"] = { spellId = 0, reagents = { { name = "Lesser Nether Essence", count = 2 }, { name = "Vision Dust", count = 3 } } },
    ["Strength (weapon enchant)"] = { spellId = 0, reagents = { { name = "Essence of Earth", count = 4 }, { name = "Large Brilliant Shard", count = 4 } } },
    ["Striking"] = { spellId = 0, reagents = { { name = "Large Glowing Shard", count = 1 }, { name = "Greater Mystic Essence", count = 2 } } },
    ["Superior Defense"] = { spellId = 0, reagents = { { name = "Rich Illusion Dust", count = 5 } } },
    ["Superior Health"] = { spellId = 0, reagents = { { name = "Vision Dust", count = 6 } } },
    ["Superior Impact"] = { spellId = 0, reagents = { { name = "Rich Illusion Dust", count = 10 }, { name = "Large Brilliant Shard", count = 4 } } },
    ["Superior Mana"] = { spellId = 0, reagents = { { name = "Greater Eternal Essence", count = 2 } } },
    ["Superior Stamina (bracer enchant)"] = { spellId = 0, reagents = { { name = "Rich Illusion Dust", count = 8 } } },
    ["Superior Strength"] = { spellId = 0, reagents = { { name = "Rich Illusion Dust", count = 6 }, { name = "Greater Eternal Essence", count = 4 } } },
    ["Superior Striking"] = { spellId = 0, reagents = { { name = "Greater Eternal Essence", count = 4 }, { name = "Large Brilliant Shard", count = 4 } } },
    --["Superior Versatility"] = { spellId = 0, reagents = { { name = "Rich Illusion Dust", count = 4 }, { name = "Greater Eternal Essence", count = 3 } } },
    ["Unholy Weapon"] = { spellId = 0, reagents = { { name = "Essence of Undeath", count = 4 }, { name = "Large Brilliant Shard", count = 4 } } },
    --["Versatility (boots enchant)"] = { spellId = 0, reagents = { { name = "Greater Eternal Essence", count = 3 } } },
    --["Versatility (bracers enchant)"] = { spellId = 0, reagents = { { name = "Lesser Eternal Essence", count = 4 } } },
    --["Versatility (shield enchant)"] = { spellId = 0, reagents = { { name = "Greater Mystic Essence", count = 1 }, { name = "Vision Dust", count = 1 } } },
    --["Vitality (shield enchant)"] = { spellId = 0, reagents = { { name = "Rich Illusion Dust", count = 4 }, { name = "Greater Eternal Essence", count = 3 } } },
    ["Winter's Might"] = { spellId = 0, reagents = { { name = "Greater Mystic Essence", count = 3 }, { name = "Vision Dust", count = 3 }, { name = "Large Glowing Shard", count = 1 }, { name = "Dragon's Teeth", count = 2 } } },
    ["Wizard Oil"] = { spellId = 0, reagents = { { name = "Crystal Vial", count = 1 }, { name = "Firebloom", count = 2 }, { name = "Rich Illusion Dust", count = 3 } } },
}
