GuildShoppingList_EnchantingFormulae  = {
    ["Formula: Advanced Herbalism"] = { spellId = 0, reagents = { { name = "Vision Dust", count = 3 }, { name = "Sungrass", count = 3 } } },
    ["Formula: Advanced Mining"] = { spellId = 0, reagents = { { name = "Vision Dust", count = 3 }, { name = "Truesilver Bar", count = 3 } } },
    ["Formula: Agility (boots enchant)"] = { spellId = 0, reagents = { { name = "Greater Eternal Essence", count = 2 } } },
    ["Formula: Agility (gloves enchant)"] = { spellId = 0, reagents = { { name = "Lesser Nether Essence", count = 1 }, { name = "Vision Dust", count = 1 } } },
    ["Formula: Agility (two-handed weapon enchant)"] = { spellId = 0, reagents = { { name = "Essence of Air", count = 4 }, { name = "Large Brilliant Shard", count = 6 } } },
    ["Formula: Agility (weapon enchant)"] = { spellId = 0, reagents = { { name = "Essence of Air", count = 4 }, { name = "Large Brilliant Shard", count = 4 } } },
    --["Formula: Argent Versatility"] = { spellId = 0, reagents = { { name = "Rich Illusion Dust", count = 4 }, { name = "Greater Eternal Essence", count = 4 }, { name = "Essence of Water", count = 2 } } },
    ["Formula: Brilliant Mana Oil"] = { spellId = 0, reagents = { { name = "Purple Lotus", count = 3 }, { name = "Crystal Vial", count = 1 }, { name = "Large Brilliant Shard", count = 2 } } },
    ["Formula: Brilliant Wizard Oil"] = { spellId = 0, reagents = { { name = "Firebloom", count = 3 }, { name = "Crystal Vial", count = 1 }, { name = "Large Brilliant Shard", count = 2 } } },
    ["Formula: Crusader (enchant)"] = { spellId = 0, reagents = { { name = "Righteous Orb", count = 2 }, { name = "Large Brilliant Shard", count = 4 } } },
    ["Formula: Defense (enchant)"] = { spellId = 0, reagents = { { name = "Light Illusion Dust", count = 3 }, { name = "Small Brilliant Shard", count = 1 } } },
    ["Formula: Demonslaying"] = { spellId = 0, reagents = { { name = "Rich Illusion Dust", count = 2 }, { name = "Elixir of Demonslaying", count = 1 }, { name = "Large Brilliant Shard", count = 1 } } },
    ["Formula: Dodge (bracers enchant)"] = { spellId = 0, reagents = { { name = "Rich Illusion Dust", count = 2 }, { name = "Greater Eternal Essence", count = 2 } } },
    ["Formula: Enchanted Leather"] = { spellId = 0, reagents = { { name = "Rugged Leather", count = 1 }, { name = "Greater Eternal Essence", count = 3 } } },
    ["Formula: Fiery Weapon"] = { spellId = 0, reagents = { { name = "Essence of Fire", count = 1 }, { name = "Large Brilliant Shard", count = 4 } } },
    ["Formula: Fire Power"] = { spellId = 0, reagents = { { name = "Essence of Fire", count = 4 }, { name = "Large Brilliant Shard", count = 10 } } },
    ["Formula: Fishing (enchant)"] = { spellId = 0, reagents = { { name = "Light Illusion Dust", count = 2 }, { name = "Blackmouth Oil", count = 3 } } },
    ["Formula: Frost Power"] = { spellId = 0, reagents = { { name = "Essence of Water", count = 4 }, { name = "Large Brilliant Shard", count = 10 } } },
    ["Formula: Greater Agility (boots enchant)"] = { spellId = 0, reagents = { { name = "Greater Eternal Essence", count = 4 }, { name = "Wildvine", count = 2 } } },
    ["Formula: Greater Agility (gloves enchant)"] = { spellId = 0, reagents = { { name = "Rich Illusion Dust", count = 3 }, { name = "Greater Eternal Essence", count = 3 } } },
    ["Formula: Greater Defense"] = { spellId = 0, reagents = { { name = "Vision Dust", count = 3 } } },
    ["Formula: Greater Health"] = { spellId = 0, reagents = { { name = "Light Illusion Dust", count = 3 } } },
    ["Formula: Greater Impact"] = { spellId = 0, reagents = { { name = "Rich Illusion Dust", count = 2 }, { name = "Large Brilliant Shard", count = 2 } } },
    ["Formula: Greater Intellect (bracers enchant)"] = { spellId = 0, reagents = { { name = "Greater Eternal Essence", count = 3 } } },
    ["Formula: Greater Magic Wand"] = { spellId = 0, reagents = { { name = "Simple Wood", count = 1 }, { name = "Greater Magic Essence", count = 1 } } },
    ["Formula: Greater Mana"] = { spellId = 0, reagents = { { name = "Greater Mystic Essence", count = 1 } } },
    ["Formula: Greater Mystic Wand"] = { spellId = 0, reagents = { { name = "Greater Mystic Essence", count = 1 }, { name = "Vision Dust", count = 1 }, { name = "Star Wood", count = 1 } } },
    ["Formula: Greater Stamina (boots enchant)"] = { spellId = 0, reagents = { { name = "Rich Illusion Dust", count = 4 } } },
    ["Formula: Greater Stamina (bracers enchant)"] = { spellId = 0, reagents = { { name = "Rich Illusion Dust", count = 3 } } },
    ["Formula: Greater Stamina (shield enchant)"] = { spellId = 0, reagents = { { name = "Rich Illusion Dust", count = 4 } } },
    ["Formula: Greater Stats (chest enchant)"] = { spellId = 0, reagents = { { name = "Rich Illusion Dust", count = 6 }, { name = "Large Brilliant Shard", count = 4 } } },
    ["Formula: Greater Strength (bracers enchant)"] = { spellId = 0, reagents = { { name = "Rich Illusion Dust", count = 2 }, { name = "Greater Eternal Essence", count = 2 } } },
    ["Formula: Greater Strength (gloves enchant)"] = { spellId = 0, reagents = { { name = "Rich Illusion Dust", count = 4 }, { name = "Greater Eternal Essence", count = 4 } } },
    ["Formula: Greater Striking"] = { spellId = 0, reagents = { { name = "Greater Eternal Essence", count = 2 }, { name = "Large Brilliant Shard", count = 2 } } },
    --["Formula: Greater Versatility (bracers enchant)"] = { spellId = 0, reagents = { { name = "Lesser Nether Essence", count = 3 }, { name = "Vision Dust", count = 1 } } },
    --["Formula: Greater Versatility (shield enchant)"] = { spellId = 0, reagents = { { name = "Rich Illusion Dust", count = 2 }, { name = "Greater Eternal Essence", count = 2 } } },
    ["Formula: Healing Power (bracers enchant)"] = { spellId = 0, reagents = { { name = "Rich Illusion Dust", count = 5 }, { name = "Greater Eternal Essence", count = 3 }, { name = "Large Brilliant Shard", count = 4 } } },
    ["Formula: Healing Power (gloves enchant)"] = { spellId = 0, reagents = { { name = "Righteous Orb", count = 1 }, { name = "Large Brilliant Shard", count = 8 } } },
    ["Formula: Healing Power (weapon enchant)"] = { spellId = 0, reagents = { { name = "Greater Eternal Essence", count = 4 }, { name = "Large Brilliant Shard", count = 4 }, { name = "Essence of Water", count = 4 } } },
    ["Formula: Health (enchant)"] = { spellId = 0, reagents = { { name = "Light Illusion Dust", count = 4 }, { name = "Lesser Eternal Essence", count = 1 } } },
    ["Formula: Herbalism (enchant)"] = { spellId = 0, reagents = { { name = "Light Illusion Dust", count = 1 }, { name = "Kingsblood", count = 3 } } },
    ["Formula: Icy Chill"] = { spellId = 0, reagents = { { name = "Icecap", count = 1 }, { name = "Essence of Air", count = 1 }, { name = "Essence of Water", count = 1 }, { name = "Large Brilliant Shard", count = 4 } } },
    ["Formula: Impact"] = { spellId = 0, reagents = { { name = "Large Glowing Shard", count = 1 }, { name = "Vision Dust", count = 4 } } },
    ["Formula: Intellect (bracers enchant)"] = { spellId = 0, reagents = { { name = "Lesser Nether Essence", count = 2 } } },
    ["Formula: Lesser Absorption"] = { spellId = 0, reagents = { { name = "Light Illusion Dust", count = 2 }, { name = "Lesser Eternal Essence", count = 1 }, { name = "Small Brilliant Shard", count = 1 } } },
    ["Formula: Lesser Agility (boots enchant)"] = { spellId = 0, reagents = { { name = "Light Illusion Dust", count = 1 }, { name = "Lesser Eternal Essence", count = 2 } } },
    ["Formula: Lesser Agility (cloak enchant)"] = { spellId = 0, reagents = { { name = "Lesser Nether Essence", count = 2 } } },
    ["Formula: Lesser Beastslayer"] = { spellId = 0, reagents = { { name = "Large Fang", count = 2 }, { name = "Lesser Eternal Essence", count = 4 }, { name = "Small Brilliant Shard", count = 1 } } },
    ["Formula: Lesser Dodge (bracers enchant)"] = { spellId = 0, reagents = { { name = "Light Illusion Dust", count = 2 }, { name = "Lesser Eternal Essence", count = 4 } } },
    ["Formula: Lesser Elemental Slayer"] = { spellId = 0, reagents = { { name = "Small Glowing Shard", count = 1 }, { name = "Lesser Mystic Essence", count = 1 }, { name = "Elemental Earth", count = 1 } } },
    ["Formula: Lesser Health"] = { spellId = 0, reagents = { { name = "Strange Dust", count = 2 }, { name = "Lesser Magic Essence", count = 2 } } },
    ["Formula: Lesser Impact"] = { spellId = 0, reagents = { { name = "Light Illusion Dust", count = 3 }, { name = "Small Brilliant Shard", count = 1 } } },
    ["Formula: Lesser Intellect (bracers enchant)"] = { spellId = 0, reagents = { { name = "Lesser Eternal Essence", count = 2 } } },
    ["Formula: Lesser Intellect (weapon enchant)"] = { spellId = 0, reagents = { { name = "Lesser Magic Essence", count = 2 } } },
    ["Formula: Lesser Magic Wand"] = { spellId = 0, reagents = { { name = "Simple Wood", count = 1 }, { name = "Lesser Magic Essence", count = 1 } } },
    ["Formula: Lesser Mana Oil"] = { spellId = 0, reagents = { { name = "Rich Illusion Dust", count = 3 }, { name = "Purple Lotus", count = 2 }, { name = "Crystal Vial", count = 1 } } },
    ["Formula: Lesser Mana"] = { spellId = 0, reagents = { { name = "Greater Magic Essence", count = 1 }, { name = "Lesser Magic Essence", count = 1 } } },
    ["Formula: Lesser Mystic Wand"] = { spellId = 0, reagents = { { name = "Light Illusion Dust", count = 3 }, { name = "Star Wood", count = 1 }, { name = "Lesser Eternal Essence", count = 2 } } },
    ["Formula: Lesser Parry"] = { spellId = 0, reagents = { { name = "Large Glowing Shard", count = 1 }, { name = "Greater Mystic Essence", count = 2 }, { name = "Vision Dust", count = 2 } } },
    ["Formula: Lesser Protection (cloak enchant)"] = { spellId = 0, reagents = { { name = "Light Illusion Dust", count = 6 }, { name = "Small Brilliant Shard", count = 1 } } },
    ["Formula: Lesser Protection (shield enchant)"] = { spellId = 0, reagents = { { name = "Light Illusion Dust", count = 1 }, { name = "Lesser Eternal Essence", count = 1 }, { name = "Small Brilliant Shard", count = 1 } } },
    ["Formula: Lesser Stamina (boots enchant)"] = { spellId = 0, reagents = { { name = "Light Illusion Dust", count = 4 } } },
    ["Formula: Lesser Stamina (bracers enchant)"] = { spellId = 0, reagents = { { name = "Light Illusion Dust", count = 2 } } },
    ["Formula: Lesser Stamina (shield enchant)"] = { spellId = 0, reagents = { { name = "Light Illusion Dust", count = 4 }, { name = "Lesser Eternal Essence", count = 2 } } },
    ["Formula: Lesser Stats"] = { spellId = 0, reagents = { { name = "Large Glowing Shard", count = 1 }, { name = "Greater Mystic Essence", count = 2 }, { name = "Vision Dust", count = 2 } } },
    ["Formula: Lesser Strength"] = { spellId = 0, reagents = { { name = "Light Illusion Dust", count = 2 } } },
    ["Formula: Lesser Striking"] = { spellId = 0, reagents = { { name = "Light Illusion Dust", count = 2 }, { name = "Small Brilliant Shard", count = 1 } } },
    --["Formula: Lesser Versatility (boots enchant)"] = { spellId = 0, reagents = { { name = "Greater Mystic Essence", count = 1 }, { name = "Lesser Mystic Essence", count = 2 } } },
    --["Formula: Lesser Versatility (bracers enchant)"] = { spellId = 0, reagents = { { name = "Lesser Eternal Essence", count = 2 } } },
    --["Formula: Lesser Versatility (shield enchant)"] = { spellId = 0, reagents = { { name = "Light Illusion Dust", count = 4 }, { name = "Lesser Eternal Essence", count = 2 } } },
    --["Formula: Lesser Versatility (weapon enchant)"] = { spellId = 0, reagents = { { name = "Light Illusion Dust", count = 3 }, { name = "Lesser Eternal Essence", count = 1 } } },
    ["Formula: Lesser Wizard Oil"] = { spellId = 0, reagents = { { name = "Vision Dust", count = 3 }, { name = "Crystal Vial", count = 1 } } },
    ["Formula: Lifestealing"] = { spellId = 0, reagents = { { name = "Essence of Undeath", count = 4 }, { name = "Living Essence", count = 4 }, { name = "Large Brilliant Shard", count = 4 } } },
    ["Formula: Major Health"] = { spellId = 0, reagents = { { name = "Large Brilliant Shard", count = 3 } } },
    ["Formula: Major Intellect (two-hand weapon enchant)"] = { spellId = 0, reagents = { { name = "Greater Eternal Essence", count = 4 }, { name = "Large Brilliant Shard", count = 4 } } },
    ["Formula: Major Mana"] = { spellId = 0, reagents = { { name = "Rich Illusion Dust", count = 5 } } },
    --["Formula: Major Versatility (weapon enchant)"] = { spellId = 0, reagents = { { name = "Greater Eternal Essence", count = 4 }, { name = "Large Brilliant Shard", count = 4 } } },
    ["Formula: Mana (enchant)"] = { spellId = 0, reagents = { { name = "Lesser Eternal Essence", count = 3 } } },
    ["Formula: Mighty Intellect (weapon enchant)"] = { spellId = 0, reagents = { { name = "Rich Illusion Dust", count = 16 }, { name = "Greater Eternal Essence", count = 5 }, { name = "Large Brilliant Shard", count = 6 } } },
    --["Formula: Mighty Versatility (weapon enchant)"] = { spellId = 0, reagents = { { name = "Rich Illusion Dust", count = 12 }, { name = "Greater Eternal Essence", count = 4 }, { name = "Large Brilliant Shard", count = 6 } } },
    ["Formula: Mining (enchant)"] = { spellId = 0, reagents = { { name = "Light Illusion Dust", count = 2 }, { name = "Iron Ore", count = 3 } } },
    ["Formula: Minor Absorption"] = { spellId = 0, reagents = { { name = "Strange Dust", count = 2 }, { name = "Lesser Magic Essence", count = 1 } } },
    ["Formula: Minor Agility (boots enchant)"] = { spellId = 0, reagents = { { name = "Strange Dust", count = 6 }, { name = "Lesser Eternal Essence", count = 2 } } },
    ["Formula: Minor Agility (bracers enchant)"] = { spellId = 0, reagents = { { name = "Strange Dust", count = 2 }, { name = "Greater Magic Essence", count = 1 } } },
    ["Formula: Minor Agility (cloak enchant)"] = { spellId = 0, reagents = { { name = "Lesser Eternal Essence", count = 1 } } },
    ["Formula: Minor Beastslayer"] = { spellId = 0, reagents = { { name = "Strange Dust", count = 4 }, { name = "Greater Magic Essence", count = 2 } } },
    ["Formula: Minor Dodge"] = { spellId = 0, reagents = { { name = "Strange Dust", count = 1 }, { name = "Lesser Magic Essence", count = 1 } } },
    ["Formula: Minor Haste"] = { spellId = 0, reagents = { { name = "Wildvine", count = 2 }, { name = "Large Brilliant Shard", count = 2 } } },
    ["Formula: Minor Health (bracer enchant)"] = { spellId = 0, reagents = { { name = "Strange Dust", count = 1 } } },
    ["Formula: Minor Health (chest enchant)"] = { spellId = 0, reagents = { { name = "Strange Dust", count = 1 } } },
    ["Formula: Minor Impact"] = { spellId = 0, reagents = { { name = "Strange Dust", count = 4 }, { name = "Greater Magic Essence", count = 2 } } },
    ["Formula: Minor Mana Oil"] = { spellId = 0, reagents = { { name = "Light Illusion Dust", count = 3 }, { name = "Crystal Vial", count = 1 } } },
    ["Formula: Minor Mana"] = { spellId = 0, reagents = { { name = "Lesser Magic Essence", count = 2 } } },
    ["Formula: Minor Protection"] = { spellId = 0, reagents = { { name = "Strange Dust", count = 3 }, { name = "Greater Magic Essence", count = 1 } } },
    ["Formula: Minor Speed"] = { spellId = 0, reagents = { { name = "Small Radiant Shard", count = 1 }, { name = "Lesser Nether Essence", count = 1 }, { name = "Aquamarine", count = 1 } } },
    ["Formula: Minor Stamina (boots enchant)"] = { spellId = 0, reagents = { { name = "Light Illusion Dust", count = 4 } } },
    ["Formula: Minor Stamina (bracers enchant)"] = { spellId = 0, reagents = { { name = "Strange Dust", count = 3 } } },
    ["Formula: Minor Stamina (shield enchant)"] = { spellId = 0, reagents = { { name = "Light Illusion Dust", count = 2 }, { name = "Lesser Eternal Essence", count = 1 } } },
    ["Formula: Minor Stats"] = { spellId = 0, reagents = { { name = "Light Illusion Dust", count = 1 }, { name = "Lesser Eternal Essence", count = 2 }, { name = "Small Brilliant Shard", count = 1 } } },
    ["Formula: Minor Strength"] = { spellId = 0, reagents = { { name = "Strange Dust", count = 5 } } },
    ["Formula: Minor Striking"] = { spellId = 0, reagents = { { name = "Strange Dust", count = 4 }, { name = "Greater Magic Essence", count = 2 } } },
    --["Formula: Minor Versatility"] = { spellId = 0, reagents = { { name = "Lesser Magic Essence", count = 2 } } },
    ["Formula: Minor Wizard Oil"] = { spellId = 0, reagents = { { name = "Strange Dust", count = 2 }, { name = "Crystal Vial", count = 1 } } },
    ["Formula: Riding Skill"] = { spellId = 0, reagents = { { name = "Rich Illusion Dust", count = 3 }, { name = "Large Brilliant Shard", count = 2 } } },
    ["Formula: Runed Copper Rod"] = { spellId = 0, reagents = { { name = "Strange Dust", count = 1 }, { name = "Copper Rod", count = 1 }, { name = "Lesser Magic Essence", count = 1 } } },
    ["Formula: Shadow Power"] = { spellId = 0, reagents = { { name = "Essence of Undeath", count = 6 }, { name = "Large Brilliant Shard", count = 10 } } },
    ["Formula: Skinning (enchant)"] = { spellId = 0, reagents = { { name = "Vision Dust", count = 1 }, { name = "Green Whelp Scale", count = 3 } } },
    ["Formula: Smoking Heart of the Mountain"] = { spellId = 0, reagents = { { name = "Essence of Fire", count = 3 }, { name = "Large Brilliant Shard", count = 3 } } },
    ["Formula: Spellpower (weapon enchant)"] = { spellId = 0, reagents = { { name = "Golden Pearl", count = 2 }, { name = "Greater Eternal Essence", count = 6 }, { name = "Large Brilliant Shard", count = 4 } } },
    ["Formula: Stamina (boots enchant)"] = { spellId = 0, reagents = { { name = "Vision Dust", count = 5 } } },
    ["Formula: Stamina (bracers enchant)"] = { spellId = 0, reagents = { { name = "Light Illusion Dust", count = 5 } } },
    ["Formula: Stamina (shield enchant)"] = { spellId = 0, reagents = { { name = "Vision Dust", count = 5 } } },
    ["Formula: Stats (enchant)"] = { spellId = 0, reagents = { { name = "Rich Illusion Dust", count = 2 }, { name = "Greater Eternal Essence", count = 2 }, { name = "Large Brilliant Shard", count = 2 } } },
    ["Formula: Strength (bracers enchant)"] = { spellId = 0, reagents = { { name = "Vision Dust", count = 1 } } },
    ["Formula: Strength (gloves enchant)"] = { spellId = 0, reagents = { { name = "Lesser Nether Essence", count = 2 }, { name = "Vision Dust", count = 3 } } },
    ["Formula: Strength (weapon enchant)"] = { spellId = 0, reagents = { { name = "Essence of Earth", count = 4 }, { name = "Large Brilliant Shard", count = 4 } } },
    ["Formula: Striking"] = { spellId = 0, reagents = { { name = "Large Glowing Shard", count = 1 }, { name = "Greater Mystic Essence", count = 2 } } },
    ["Formula: Superior Defense"] = { spellId = 0, reagents = { { name = "Rich Illusion Dust", count = 5 } } },
    ["Formula: Superior Health"] = { spellId = 0, reagents = { { name = "Vision Dust", count = 6 } } },
    ["Formula: Superior Impact"] = { spellId = 0, reagents = { { name = "Rich Illusion Dust", count = 10 }, { name = "Large Brilliant Shard", count = 4 } } },
    ["Formula: Superior Mana"] = { spellId = 0, reagents = { { name = "Greater Eternal Essence", count = 2 } } },
    ["Formula: Superior Stamina (bracer enchant)"] = { spellId = 0, reagents = { { name = "Rich Illusion Dust", count = 8 } } },
    ["Formula: Superior Strength"] = { spellId = 0, reagents = { { name = "Rich Illusion Dust", count = 6 }, { name = "Greater Eternal Essence", count = 4 } } },
    ["Formula: Superior Striking"] = { spellId = 0, reagents = { { name = "Greater Eternal Essence", count = 4 }, { name = "Large Brilliant Shard", count = 4 } } },
    --["Formula: Superior Versatility"] = { spellId = 0, reagents = { { name = "Rich Illusion Dust", count = 4 }, { name = "Greater Eternal Essence", count = 3 } } },
    ["Formula: Unholy Weapon"] = { spellId = 0, reagents = { { name = "Essence of Undeath", count = 4 }, { name = "Large Brilliant Shard", count = 4 } } },
    --["Formula: Versatility (boots enchant)"] = { spellId = 0, reagents = { { name = "Greater Eternal Essence", count = 3 } } },
    --["Formula: Versatility (bracers enchant)"] = { spellId = 0, reagents = { { name = "Lesser Eternal Essence", count = 4 } } },
    --["Formula: Versatility (shield enchant)"] = { spellId = 0, reagents = { { name = "Greater Mystic Essence", count = 1 }, { name = "Vision Dust", count = 1 } } },
    --["Formula: Vitality (shield enchant)"] = { spellId = 0, reagents = { { name = "Rich Illusion Dust", count = 4 }, { name = "Greater Eternal Essence", count = 3 } } },
    ["Formula: Winter's Might"] = { spellId = 0, reagents = { { name = "Greater Mystic Essence", count = 3 }, { name = "Vision Dust", count = 3 }, { name = "Large Glowing Shard", count = 1 }, { name = "Dragon's Teeth", count = 2 } } },
    ["Formula: Wizard Oil"] = { spellId = 0, reagents = { { name = "Crystal Vial", count = 1 }, { name = "Firebloom", count = 2 }, { name = "Rich Illusion Dust", count = 3 } } },
}
