GuildShoppingList_EngineeringSchematics  = {
    ["Schematic: Accurate Scope"] = { spellId = 0, reagents = { { name = "Citrine", count = 1 }, { name = "Jade", count = 1 }, { name = "Bronze Tube", count = 1 } } },
    ["Schematic: Advanced Target Dummy"] = { spellId = 0, reagents = { { name = "Bronze Framework", count = 1 }, { name = "Gyrochronatom", count = 1 }, { name = "Heavy Leather", count = 4 }, { name = "Iron Strut", count = 1 } } },
    ["Schematic: Aquadynamic Fish Attractor"] = { spellId = 0, reagents = { { name = "Bronze Bar", count = 2 }, { name = "Coarse Blasting Powder", count = 1 }, { name = "Nightcrawlers", count = 1 } } },
    ["Schematic: Arcane Bomb"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 3 }, { name = "Delicate Arcanite Converter", count = 1 }, { name = "Runecloth", count = 1 } } },
    ["Schematic: Arcanite Dragonling"] = { spellId = 0, reagents = { { name = "Delicate Arcanite Converter", count = 4 }, { name = "Mithril Mechanical Dragonling", count = 1 } } },
    ["Schematic: Arclight Spanner"] = { spellId = 0, reagents = { { name = "Copper Bar", count = 6 } } },
    ["Schematic: Big Bronze Bomb"] = { spellId = 0, reagents = { { name = "Bronze Bar", count = 3 }, { name = "Heavy Blasting Powder", count = 2 }, { name = "Silver Contact", count = 1 } } },
    ["Schematic: Big Iron Bomb"] = { spellId = 0, reagents = { { name = "Iron Bar", count = 3 }, { name = "Heavy Blasting Powder", count = 3 }, { name = "Silver Contact", count = 1 } } },
    ["Schematic: Biznicks 247x128 Accurascope"] = { spellId = 0, reagents = { { name = "Dark Iron Bar", count = 6 }, { name = "Lava Core", count = 2 }, { name = "Essence of Earth", count = 2 }, { name = "Delicate Arcanite Converter", count = 4 }, { name = "Thorium Tube", count = 1 } } },
    ["Schematic: Bloodvine Goggles"] = { spellId = 0, reagents = { { name = "Souldarite", count = 5 }, { name = "Bloodvine", count = 4 }, { name = "Delicate Arcanite Converter", count = 2 }, { name = "Enchanted Leather", count = 4 }, { name = "Powerful Mojo", count = 8 } } },
    ["Schematic: Bloodvine Lens"] = { spellId = 0, reagents = { { name = "Souldarite", count = 5 }, { name = "Bloodvine", count = 5 }, { name = "Delicate Arcanite Converter", count = 1 }, { name = "Enchanted Leather", count = 4 }, { name = "Powerful Mojo", count = 8 } } },
    ["Schematic: Blue Firework"] = { spellId = 0, reagents = { { name = "Heavy Blasting Powder", count = 1 }, { name = "Heavy Leather", count = 1 } } },
    ["Schematic: Blue Rocket Cluster"] = { spellId = 0, reagents = { { name = "Solid Blasting Powder", count = 1 }, { name = "Thick Leather", count = 1 } } },
    ["Schematic: Bright-Eye Goggles"] = { spellId = 0, reagents = { { name = "Citrine", count = 2 }, { name = "Heavy Leather", count = 6 } } },
    ["Schematic: Bronze Framework"] = { spellId = 0, reagents = { { name = "Bronze Bar", count = 2 }, { name = "Medium Leather", count = 1 }, { name = "Wool Cloth", count = 1 } } },
    ["Schematic: Bronze Tube"] = { spellId = 0, reagents = { { name = "Bronze Bar", count = 2 } } },
    ["Schematic: Catseye Ultra Goggles"] = { spellId = 0, reagents = { { name = "Aquamarine", count = 2 }, { name = "Catseye Elixir", count = 1 }, { name = "Thick Leather", count = 4 } } },
    ["Schematic: Clockwork Box"] = { spellId = 0, reagents = { { name = "Bronze Bar", count = 3 } } },
    ["Schematic: Cluster Launcher"] = { spellId = 0, reagents = { { name = "Goblin Rocket Fuel", count = 4 }, { name = "Inlaid Mithril Cylinder", count = 4 }, { name = "Mithril Casing", count = 1 }, { name = "Truesilver Transformer", count = 2 } } },
    ["Schematic: Coarse Blasting Powder"] = { spellId = 0, reagents = { { name = "Coarse Stone", count = 1 } } },
    ["Schematic: Coarse Dynamite"] = { spellId = 0, reagents = { { name = "Coarse Blasting Powder", count = 1 }, { name = "Linen Cloth", count = 1 } } },
    ["Schematic: Compact Harvest Reaper Kit"] = { spellId = 0, reagents = { { name = "Bronze Framework", count = 1 }, { name = "Gyrochronatom", count = 2 }, { name = "Heavy Leather", count = 4 }, { name = "Iron Strut", count = 2 } } },
    ["Schematic: Core Marksman Rifle"] = { spellId = 0, reagents = { { name = "Fiery Core", count = 4 }, { name = "Lava Core", count = 2 }, { name = "Arcanite Bar", count = 6 }, { name = "Delicate Arcanite Converter", count = 2 }, { name = "Thorium Tube", count = 2 } } },
    ["Schematic: Craftsman's Monocle"] = { spellId = 0, reagents = { { name = "Citrine", count = 2 }, { name = "Heavy Leather", count = 6 } } },
    ["Schematic: Crude Scope"] = { spellId = 0, reagents = { { name = "Malachite", count = 1 }, { name = "Copper Bar", count = 2 }, { name = "Handful of Copper Bolts", count = 1 } } },
    ["Schematic: Dark Iron Bomb"] = { spellId = 0, reagents = { { name = "Dark Iron Bar", count = 1 }, { name = "Dense Blasting Powder", count = 3 }, { name = "Runecloth", count = 3 }, { name = "Thorium Widget", count = 2 } } },
    ["Schematic: Dark Iron Rifle"] = { spellId = 0, reagents = { { name = "Blue Sapphire", count = 2 }, { name = "Large Opal", count = 2 }, { name = "Dark Iron Bar", count = 6 }, { name = "Deadly Scope", count = 2 }, { name = "Rugged Leather", count = 4 } } },
    ["Schematic: Deadly Blunderbuss"] = { spellId = 0, reagents = { { name = "Bronze Tube", count = 4 }, { name = "Standard Scope", count = 1 }, { name = "Wooden Stock", count = 1 } } },
    ["Schematic: Deadly Scope"] = { spellId = 0, reagents = { { name = "Aquamarine", count = 2 }, { name = "Mithril Tube", count = 1 }, { name = "Thick Leather", count = 2 } } },
    ["Schematic: Deepdive Helmet"] = { spellId = 0, reagents = { { name = "Malachite", count = 4 }, { name = "Tigerseye", count = 4 }, { name = "Truesilver Bar", count = 1 }, { name = "Mithril Bar", count = 8 }, { name = "Mithril Casing", count = 1 } } },
    ["Schematic: Delicate Arcanite Converter"] = { spellId = 0, reagents = { { name = "Arcanite Bar", count = 1 }, { name = "Ironweb Spider Silk", count = 1 } } },
    ["Schematic: Dense Blasting Powder"] = { spellId = 0, reagents = { { name = "Dense Stone", count = 2 } } },
    ["Schematic: Dense Dynamite"] = { spellId = 0, reagents = { { name = "Dense Blasting Powder", count = 2 }, { name = "Runecloth", count = 3 } } },
    ["Schematic: Discombobulator Ray"] = { spellId = 0, reagents = { { name = "Jade", count = 1 }, { name = "Bronze Tube", count = 1 }, { name = "Silk Cloth", count = 2 }, { name = "Whirring Bronze Gizmo", count = 3 } } },
    ["Schematic: Explosive Sheep"] = { spellId = 0, reagents = { { name = "Bronze Framework", count = 1 }, { name = "Heavy Blasting Powder", count = 2 }, { name = "Whirring Bronze Gizmo", count = 1 }, { name = "Wool Cloth", count = 2 } } },
    ["Schematic: Ez-Thro Dynamite II"] = { spellId = 0, reagents = { { name = "Mageweave Cloth", count = 2 }, { name = "Solid Blasting Powder", count = 1 } } },
    ["Schematic: Ez-Thro Dynamite"] = { spellId = 0, reagents = { { name = "Coarse Blasting Powder", count = 4 }, { name = "Wool Cloth", count = 1 } } },
    ["Schematic: Field Repair Bot 74A"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 16 }, { name = "Fused Wiring", count = 1 } } },
    ["Schematic: Fire Goggles"] = { spellId = 0, reagents = { { name = "Citrine", count = 2 }, { name = "Green Tinted Goggles", count = 1 }, { name = "Elemental Fire", count = 2 }, { name = "Heavy Leather", count = 4 } } },
    ["Schematic: Firework Launcher"] = { spellId = 0, reagents = { { name = "Goblin Rocket Fuel", count = 1 }, { name = "Inlaid Mithril Cylinder", count = 1 }, { name = "Mithril Casing", count = 1 }, { name = "Unstable Trigger", count = 1 } } },
    ["Schematic: Flame Deflector"] = { spellId = 0, reagents = { { name = "Small Flame Sac", count = 1 }, { name = "Whirring Bronze Gizmo", count = 1 } } },
    ["Schematic: Flash Bomb"] = { spellId = 0, reagents = { { name = "Blue Pearl", count = 1 }, { name = "Heavy Blasting Powder", count = 1 }, { name = "Silk Cloth", count = 1 } } },
    ["Schematic: Flawless Arcanite Rifle"] = { spellId = 0, reagents = { { name = "Azerothian Diamond", count = 2 }, { name = "Arcanite Bar", count = 10 }, { name = "Essence of Earth", count = 2 }, { name = "Essence of Fire", count = 2 }, { name = "Enchanted Leather", count = 2 }, { name = "Thorium Tube", count = 2 } } },
    ["Schematic: Flying Tiger Goggles"] = { spellId = 0, reagents = { { name = "Tigerseye", count = 2 }, { name = "Light Leather", count = 6 } } },
    ["Schematic: Force Reactive Disk"] = { spellId = 0, reagents = { { name = "Arcanite Bar", count = 6 }, { name = "Essence of Air", count = 8 }, { name = "Essence of Earth", count = 8 }, { name = "Living Essence", count = 12 }, { name = "Delicate Arcanite Converter", count = 2 } } },
    ["Schematic: Fused Wiring"] = { spellId = 0, reagents = { { name = "Delicate Copper Wire", count = 3 }, { name = "Essence of Fire", count = 2 } } },
    ["Schematic: Gnomish Cloaking Device"] = { spellId = 0, reagents = { { name = "Citrine", count = 2 }, { name = "Jade", count = 2 }, { name = "Lesser Moonstone", count = 2 }, { name = "Fused Wiring", count = 1 }, { name = "Gyrochronatom", count = 4 } } },
    ["Schematic: Gnomish Universal Remote"] = { spellId = 0, reagents = { { name = "Malachite", count = 1 }, { name = "Tigerseye", count = 1 }, { name = "Bronze Bar", count = 6 }, { name = "Flask of Oil", count = 2 }, { name = "Whirring Bronze Gizmo", count = 1 } } },
    ["Schematic: Goblin Jumper Cables"] = { spellId = 0, reagents = { { name = "Shadowgem", count = 2 }, { name = "Iron Bar", count = 6 }, { name = "Flask of Oil", count = 2 }, { name = "Fused Wiring", count = 1 }, { name = "Silk Cloth", count = 2 }, { name = "Whirring Bronze Gizmo", count = 2 } } },
    ["Schematic: Goblin Land Mine"] = { spellId = 0, reagents = { { name = "Iron Bar", count = 2 }, { name = "Gyrochronatom", count = 1 }, { name = "Heavy Blasting Powder", count = 3 } } },
    ["Schematic: Gold Power Core"] = { spellId = 0, reagents = { { name = "Gold Bar", count = 1 } } },
    ["Schematic: Green Firework"] = { spellId = 0, reagents = { { name = "Heavy Blasting Powder", count = 1 }, { name = "Heavy Leather", count = 1 } } },
    ["Schematic: Green Lens"] = { spellId = 0, reagents = { { name = "Aquamarine", count = 3 }, { name = "Jade", count = 3 }, { name = "Heart of the Wild (crafting reagent)", count = 2 }, { name = "Thick Leather", count = 8 }, { name = "Wildvine", count = 2 } } },
    ["Schematic: Green Rocket Cluster"] = { spellId = 0, reagents = { { name = "Solid Blasting Powder", count = 1 }, { name = "Thick Leather", count = 1 } } },
    ["Schematic: Green Tinted Goggles"] = { spellId = 0, reagents = { { name = "Moss Agate", count = 2 }, { name = "Flying Tiger Goggles", count = 1 }, { name = "Medium Leather", count = 4 } } },
    ["Schematic: Gyrochronatom"] = { spellId = 0, reagents = { { name = "Iron Bar", count = 1 }, { name = "Gold Power Core", count = 1 } } },
    ["Schematic: Gyrofreeze Ice Reflector"] = { spellId = 0, reagents = { { name = "Blue Sapphire", count = 2 }, { name = "Essence of Fire", count = 4 }, { name = "Frost Oil", count = 2 }, { name = "Icecap", count = 4 }, { name = "Thorium Widget", count = 6 }, { name = "Truesilver Transformer", count = 2 } } },
    ["Schematic: Gyromatic Micro-Adjustor"] = { spellId = 0, reagents = { { name = "Steel Bar", count = 4 } } },
    ["Schematic: Handful of Copper Bolts"] = { spellId = 0, reagents = { { name = "Copper Bar", count = 1 } } },
    ["Schematic: Heavy Blasting Powder"] = { spellId = 0, reagents = { { name = "Heavy Stone", count = 1 } } },
    ["Schematic: Heavy Dynamite"] = { spellId = 0, reagents = { { name = "Heavy Blasting Powder", count = 2 }, { name = "Wool Cloth", count = 1 } } },
    ["Schematic: Hi-Explosive Bomb"] = { spellId = 0, reagents = { { name = "Mithril Casing", count = 2 }, { name = "Solid Blasting Powder", count = 2 }, { name = "Unstable Trigger", count = 1 } } },
    ["Schematic: High-Powered Flashlight"] = { spellId = 0, reagents = { { name = "Thorium Widget", count = 4 }, { name = "Truesilver Bar", count = 6 }, { name = "Essence of Fire", count = 6 } } },
    ["Schematic: Hyper-Radiant Flame Reflector"] = { spellId = 0, reagents = { { name = "Azerothian Diamond", count = 2 }, { name = "Star Ruby", count = 4 }, { name = "Dark Iron Bar", count = 4 }, { name = "Essence of Water", count = 6 }, { name = "Truesilver Transformer", count = 3 } } },
    ["Schematic: Ice Deflector"] = { spellId = 0, reagents = { { name = "Frost Oil", count = 1 }, { name = "Whirring Bronze Gizmo", count = 1 } } },
    ["Schematic: Iron Grenade"] = { spellId = 0, reagents = { { name = "Iron Bar", count = 1 }, { name = "Heavy Blasting Powder", count = 1 }, { name = "Silk Cloth", count = 1 } } },
    ["Schematic: Iron Strut"] = { spellId = 0, reagents = { { name = "Iron Bar", count = 2 } } },
    ["Schematic: Large Blue Rocket Cluster"] = { spellId = 0, reagents = { { name = "Dense Blasting Powder", count = 1 }, { name = "Rugged Leather", count = 1 } } },
    ["Schematic: Large Blue Rocket"] = { spellId = 0, reagents = { { name = "Heavy Blasting Powder", count = 1 }, { name = "Heavy Leather", count = 1 } } },
    ["Schematic: Large Copper Bomb"] = { spellId = 0, reagents = { { name = "Copper Bar", count = 3 }, { name = "Coarse Blasting Powder", count = 4 }, { name = "Silver Contact", count = 1 } } },
    ["Schematic: Large Green Rocket Cluster"] = { spellId = 0, reagents = { { name = "Dense Blasting Powder", count = 1 }, { name = "Rugged Leather", count = 1 } } },
    ["Schematic: Large Green Rocket"] = { spellId = 0, reagents = { { name = "Heavy Blasting Powder", count = 1 }, { name = "Heavy Leather", count = 1 } } },
    ["Schematic: Large Red Rocket Cluster"] = { spellId = 0, reagents = { { name = "Dense Blasting Powder", count = 1 }, { name = "Rugged Leather", count = 1 } } },
    ["Schematic: Large Red Rocket"] = { spellId = 0, reagents = { { name = "Heavy Blasting Powder", count = 1 }, { name = "Heavy Leather", count = 1 } } },
    ["Schematic: Large Seaforium Charge"] = { spellId = 0, reagents = { { name = "Heavy Leather", count = 2 }, { name = "Refreshing Spring Water", count = 1 }, { name = "Solid Blasting Powder", count = 2 } } },
    ["Schematic: Lifelike Mechanical Toad"] = { spellId = 0, reagents = { { name = "Living Essence", count = 1 }, { name = "Gold Power Core", count = 1 }, { name = "Rugged Leather", count = 1 }, { name = "Thorium Widget", count = 4 } } },
    ["Schematic: Lil' Smoky"] = { spellId = 0, reagents = { { name = "Truesilver Bar", count = 1 }, { name = "Mithril Bar", count = 2 }, { name = "Core of Earth", count = 1 }, { name = "Fused Wiring", count = 1 }, { name = "Gyrochronatom", count = 2 } } },
    ["Schematic: Lovingly Crafted Boomstick"] = { spellId = 0, reagents = { { name = "Moss Agate", count = 3 }, { name = "Bronze Tube", count = 2 }, { name = "Handful of Copper Bolts", count = 2 }, { name = "Heavy Stock", count = 1 } } },
    ["Schematic: Major Recombobulator"] = { spellId = 0, reagents = { { name = "Runecloth", count = 2 }, { name = "Thorium Tube", count = 2 }, { name = "Truesilver Transformer", count = 1 } } },
    ["Schematic: Master Engineer's Goggles"] = { spellId = 0, reagents = { { name = "Huge Emerald", count = 2 }, { name = "Fire Goggles", count = 1 }, { name = "Enchanted Leather", count = 4 } } },
    ["Schematic: Masterwork Target Dummy"] = { spellId = 0, reagents = { { name = "Truesilver Bar", count = 1 }, { name = "Mithril Casing", count = 1 }, { name = "Rugged Leather", count = 2 }, { name = "Runecloth", count = 4 }, { name = "Thorium Tube", count = 1 }, { name = "Thorium Widget", count = 2 } } },
    ["Schematic: Mechanical Dragonling"] = { spellId = 0, reagents = { { name = "Citrine", count = 1 }, { name = "Bronze Framework", count = 1 }, { name = "Gyrochronatom", count = 2 }, { name = "Iron Strut", count = 2 } } },
    ["Schematic: Mechanical Repair Kit"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 1 }, { name = "Mageweave Cloth", count = 1 }, { name = "Solid Blasting Powder", count = 1 } } },
    ["Schematic: Mechanical Squirrel Box"] = { spellId = 0, reagents = { { name = "Malachite", count = 2 }, { name = "Copper Bar", count = 1 }, { name = "Handful of Copper Bolts", count = 1 } } },
    ["Schematic: Minor Recombobulator"] = { spellId = 0, reagents = { { name = "Moss Agate", count = 1 }, { name = "Bronze Tube", count = 1 }, { name = "Medium Leather", count = 2 }, { name = "Whirring Bronze Gizmo", count = 2 } } },
    ["Schematic: Mithril Blunderbuss"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 4 }, { name = "Elemental Fire", count = 2 }, { name = "Heavy Stock", count = 1 }, { name = "Mithril Tube", count = 1 }, { name = "Unstable Trigger", count = 1 } } },
    ["Schematic: Mithril Casing"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 3 } } },
    ["Schematic: Mithril Frag Bomb"] = { spellId = 0, reagents = { { name = "Mithril Casing", count = 1 }, { name = "Solid Blasting Powder", count = 1 }, { name = "Unstable Trigger", count = 1 } } },
    ["Schematic: Mithril Heavy-Bore Rifle"] = { spellId = 0, reagents = { { name = "Citrine", count = 2 }, { name = "Mithril Bar", count = 6 }, { name = "Heavy Stock", count = 1 }, { name = "Mithril Tube", count = 2 }, { name = "Unstable Trigger", count = 1 } } },
    ["Schematic: Mithril Mechanical Dragonling"] = { spellId = 0, reagents = { { name = "Star Ruby", count = 2 }, { name = "Truesilver Bar", count = 4 }, { name = "Mithril Bar", count = 14 }, { name = "Goblin Rocket Fuel", count = 2 }, { name = "Heart of Fire", count = 4 }, { name = "Inlaid Mithril Cylinder", count = 2 } } },
    ["Schematic: Mithril Tube"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 3 } } },
    ["Schematic: Moonsight Rifle"] = { spellId = 0, reagents = { { name = "Lesser Moonstone", count = 2 }, { name = "Bronze Tube", count = 3 }, { name = "Heavy Stock", count = 1 }, { name = "Whirring Bronze Gizmo", count = 3 } } },
    ["Schematic: Ornate Spyglass"] = { spellId = 0, reagents = { { name = "Moss Agate", count = 1 }, { name = "Bronze Tube", count = 2 }, { name = "Copper Modulator", count = 1 }, { name = "Whirring Bronze Gizmo", count = 2 } } },
    ["Schematic: Parachute Cloak"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 4 }, { name = "Shadow Silk", count = 2 }, { name = "Solid Blasting Powder", count = 4 }, { name = "Unstable Trigger", count = 1 } } },
    ["Schematic: Pet Bombling"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 6 }, { name = "Big Iron Bomb", count = 1 }, { name = "Fused Wiring", count = 1 }, { name = "Heart of Fire", count = 1 } } },
    ["Schematic: Portable Bronze Mortar"] = { spellId = 0, reagents = { { name = "Bronze Tube", count = 4 }, { name = "Heavy Blasting Powder", count = 4 }, { name = "Iron Strut", count = 1 }, { name = "Medium Leather", count = 4 } } },
    ["Schematic: Powerful Seaforium Charge"] = { spellId = 0, reagents = { { name = "Dense Blasting Powder", count = 3 }, { name = "Refreshing Spring Water", count = 1 }, { name = "Rugged Leather", count = 2 }, { name = "Thorium Widget", count = 2 } } },
    ["Schematic: Red Firework"] = { spellId = 0, reagents = { { name = "Heavy Blasting Powder", count = 1 }, { name = "Heavy Leather", count = 1 } } },
    ["Schematic: Red Rocket Cluster"] = { spellId = 0, reagents = { { name = "Solid Blasting Powder", count = 1 }, { name = "Thick Leather", count = 1 } } },
    ["Schematic: Rose Colored Goggles"] = { spellId = 0, reagents = { { name = "Star Ruby", count = 2 }, { name = "Thick Leather", count = 6 } } },
    ["Schematic: Rough Blasting Powder"] = { spellId = 0, reagents = { { name = "Rough Stone", count = 1 } } },
    ["Schematic: Rough Boomstick"] = { spellId = 0, reagents = { { name = "Copper Bar", count = 4 }, { name = "Handful of Copper Bolts", count = 3 }, { name = "Wooden Stock", count = 1 } } },
    ["Schematic: Rough Copper Bomb"] = { spellId = 0, reagents = { { name = "Handful of Copper Bolts", count = 1 }, { name = "Rough Blasting Powder", count = 2 } } },
    ["Schematic: Rough Dynamite"] = { spellId = 0, reagents = { { name = "Rough Blasting Powder", count = 1 }, { name = "Linen Cloth", count = 1 } } },
    ["Schematic: Shadow Goggles"] = { spellId = 0, reagents = { { name = "Shadowgem", count = 2 }, { name = "Medium Leather", count = 4 } } },
    ["Schematic: Silver Contact"] = { spellId = 0, reagents = { { name = "Silver Bar", count = 1 } } },
    ["Schematic: Silver-plated Shotgun"] = { spellId = 0, reagents = { { name = "Silver Bar", count = 3 }, { name = "Bronze Tube", count = 2 }, { name = "Heavy Stock", count = 1 }, { name = "Whirring Bronze Gizmo", count = 2 } } },
    ["Schematic: Small Blue Rocket"] = { spellId = 0, reagents = { { name = "Coarse Blasting Powder", count = 1 }, { name = "Medium Leather", count = 1 } } },
    ["Schematic: Small Bronze Bomb"] = { spellId = 0, reagents = { { name = "Bronze Bar", count = 2 }, { name = "Coarse Blasting Powder", count = 4 }, { name = "Silver Contact", count = 1 }, { name = "Wool Cloth", count = 1 } } },
    ["Schematic: Small Green Rocket"] = { spellId = 0, reagents = { { name = "Coarse Blasting Powder", count = 1 }, { name = "Medium Leather", count = 1 } } },
    ["Schematic: Small Red Rocket"] = { spellId = 0, reagents = { { name = "Coarse Blasting Powder", count = 1 }, { name = "Medium Leather", count = 1 } } },
    ["Schematic: Small Seaforium Charge"] = { spellId = 0, reagents = { { name = "Coarse Blasting Powder", count = 2 }, { name = "Copper Modulator", count = 1 }, { name = "Light Leather", count = 1 }, { name = "Refreshing Spring Water", count = 1 } } },
    ["Schematic: Snake Burst Firework"] = { spellId = 0, reagents = { { name = "Deeprock Salt", count = 1 }, { name = "Dense Blasting Powder", count = 2 }, { name = "Runecloth", count = 2 } } },
    ["Schematic: Sniper Scope"] = { spellId = 0, reagents = { { name = "Star Ruby", count = 1 }, { name = "Truesilver Bar", count = 2 }, { name = "Mithril Tube", count = 1 } } },
    ["Schematic: Snowmaster 9000"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 8 }, { name = "Frost Oil", count = 1 }, { name = "Gyrochronatom", count = 4 }, { name = "Snowball", count = 4 } } },
    ["Schematic: Solid Blasting Powder"] = { spellId = 0, reagents = { { name = "Solid Stone", count = 2 } } },
    ["Schematic: Solid Dynamite"] = { spellId = 0, reagents = { { name = "Silk Cloth", count = 1 }, { name = "Solid Blasting Powder", count = 1 } } },
    ["Schematic: Spellpower Goggles Xtreme Plus"] = { spellId = 0, reagents = { { name = "Star Ruby", count = 4 }, { name = "Spellpower Goggles Xtreme", count = 1 }, { name = "Enchanted Leather", count = 2 }, { name = "Runecloth", count = 8 } } },
    ["Schematic: Spellpower Goggles Xtreme"] = { spellId = 0, reagents = { { name = "Star Ruby", count = 2 }, { name = "Thick Leather", count = 4 } } },
    ["Schematic: Standard Scope"] = { spellId = 0, reagents = { { name = "Moss Agate", count = 1 }, { name = "Bronze Tube", count = 1 } } },
    ["Schematic: Steam Tonk Controller"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 3 }, { name = "Gold Power Core", count = 1 } } },
    ["Schematic: Target Dummy"] = { spellId = 0, reagents = { { name = "Bronze Bar", count = 2 }, { name = "Wool Cloth", count = 2 } } },
    ["Schematic: Thorium Grenade"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 3 }, { name = "Dense Blasting Powder", count = 3 }, { name = "Runecloth", count = 3 }, { name = "Thorium Widget", count = 1 } } },
    ["Schematic: Thorium Rifle"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 4 }, { name = "Deadly Scope", count = 1 }, { name = "Mithril Casing", count = 2 }, { name = "Mithril Tube", count = 2 }, { name = "Thorium Widget", count = 2 } } },
    ["Schematic: Thorium Tube"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 6 } } },
    ["Schematic: Thorium Widget"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 3 }, { name = "Runecloth", count = 1 } } },
    ["Schematic: Tranquil Mechanical Yeti"] = { spellId = 0, reagents = { { name = "Cured Rugged Hide", count = 1 }, { name = "Globe of Water", count = 2 }, { name = "Gold Power Core", count = 1 }, { name = "Thorium Widget", count = 4 }, { name = "Truesilver Transformer", count = 2 } } },
    ["Schematic: Truesilver Transformer"] = { spellId = 0, reagents = { { name = "Truesilver Bar", count = 2 }, { name = "Elemental Air", count = 1 }, { name = "Elemental Earth", count = 2 } } },
    ["Schematic: Ultra-Flash Shadow Reflector"] = { spellId = 0, reagents = { { name = "Azerothian Diamond", count = 2 }, { name = "Large Opal", count = 2 }, { name = "Dark Iron Bar", count = 8 }, { name = "Essence of Undeath", count = 4 }, { name = "Living Essence", count = 6 }, { name = "Truesilver Transformer", count = 4 } } },
    ["Schematic: Unstable Trigger"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 1 }, { name = "Mageweave Cloth", count = 1 }, { name = "Solid Blasting Powder", count = 1 } } },
    ["Schematic: Voice Amplification Modulator"] = { spellId = 0, reagents = { { name = "Large Opal", count = 1 }, { name = "Delicate Arcanite Converter", count = 2 }, { name = "Gold Power Core", count = 1 }, { name = "Thorium Widget", count = 1 } } },
    ["Schematic: Whirring Bronze Gizmo"] = { spellId = 0, reagents = { { name = "Bronze Bar", count = 2 }, { name = "Wool Cloth", count = 1 } } },
}
