GuildShoppingList_EngineeringSchematics  = {
    ["Accurate Scope"] = { spellId = 0, reagents = { { name = "Citrine", count = 1 }, { name = "Jade", count = 1 }, { name = "Bronze Tube", count = 1 } } },
    ["Advanced Target Dummy"] = { spellId = 0, reagents = { { name = "Bronze Framework", count = 1 }, { name = "Gyrochronatom", count = 1 }, { name = "Heavy Leather", count = 4 }, { name = "Iron Strut", count = 1 } } },
    ["Aquadynamic Fish Attractor"] = { spellId = 0, reagents = { { name = "Bronze Bar", count = 2 }, { name = "Coarse Blasting Powder", count = 1 }, { name = "Nightcrawlers", count = 1 } } },
    ["Arcane Bomb"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 3 }, { name = "Delicate Arcanite Converter", count = 1 }, { name = "Runecloth", count = 1 } } },
    ["Arcanite Dragonling"] = { spellId = 0, reagents = { { name = "Delicate Arcanite Converter", count = 4 }, { name = "Mithril Mechanical Dragonling", count = 1 } } },
    ["Arclight Spanner"] = { spellId = 0, reagents = { { name = "Copper Bar", count = 6 } } },
    ["Big Bronze Bomb"] = { spellId = 0, reagents = { { name = "Bronze Bar", count = 3 }, { name = "Heavy Blasting Powder", count = 2 }, { name = "Silver Contact", count = 1 } } },
    ["Big Iron Bomb"] = { spellId = 0, reagents = { { name = "Iron Bar", count = 3 }, { name = "Heavy Blasting Powder", count = 3 }, { name = "Silver Contact", count = 1 } } },
    ["Biznicks 247x128 Accurascope"] = { spellId = 0, reagents = { { name = "Dark Iron Bar", count = 6 }, { name = "Lava Core", count = 2 }, { name = "Essence of Earth", count = 2 }, { name = "Delicate Arcanite Converter", count = 4 }, { name = "Thorium Tube", count = 1 } } },
    ["Bloodvine Goggles"] = { spellId = 0, reagents = { { name = "Souldarite", count = 5 }, { name = "Bloodvine", count = 4 }, { name = "Delicate Arcanite Converter", count = 2 }, { name = "Enchanted Leather", count = 4 }, { name = "Powerful Mojo", count = 8 } } },
    ["Bloodvine Lens"] = { spellId = 0, reagents = { { name = "Souldarite", count = 5 }, { name = "Bloodvine", count = 5 }, { name = "Delicate Arcanite Converter", count = 1 }, { name = "Enchanted Leather", count = 4 }, { name = "Powerful Mojo", count = 8 } } },
    ["Blue Firework"] = { spellId = 0, reagents = { { name = "Heavy Blasting Powder", count = 1 }, { name = "Heavy Leather", count = 1 } } },
    ["Blue Rocket Cluster"] = { spellId = 0, reagents = { { name = "Solid Blasting Powder", count = 1 }, { name = "Thick Leather", count = 1 } } },
    ["Bright-Eye Goggles"] = { spellId = 0, reagents = { { name = "Citrine", count = 2 }, { name = "Heavy Leather", count = 6 } } },
    ["Bronze Framework"] = { spellId = 0, reagents = { { name = "Bronze Bar", count = 2 }, { name = "Medium Leather", count = 1 }, { name = "Wool Cloth", count = 1 } } },
    ["Bronze Tube"] = { spellId = 0, reagents = { { name = "Bronze Bar", count = 2 } } },
    ["Catseye Ultra Goggles"] = { spellId = 0, reagents = { { name = "Aquamarine", count = 2 }, { name = "Catseye Elixir", count = 1 }, { name = "Thick Leather", count = 4 } } },
    ["Clockwork Box"] = { spellId = 0, reagents = { { name = "Bronze Bar", count = 3 } } },
    ["Cluster Launcher"] = { spellId = 0, reagents = { { name = "Goblin Rocket Fuel", count = 4 }, { name = "Inlaid Mithril Cylinder", count = 4 }, { name = "Mithril Casing", count = 1 }, { name = "Truesilver Transformer", count = 2 } } },
    ["Coarse Blasting Powder"] = { spellId = 0, reagents = { { name = "Coarse Stone", count = 1 } } },
    ["Coarse Dynamite"] = { spellId = 0, reagents = { { name = "Coarse Blasting Powder", count = 1 }, { name = "Linen Cloth", count = 1 } } },
    ["Compact Harvest Reaper Kit"] = { spellId = 0, reagents = { { name = "Bronze Framework", count = 1 }, { name = "Gyrochronatom", count = 2 }, { name = "Heavy Leather", count = 4 }, { name = "Iron Strut", count = 2 } } },
    ["Core Marksman Rifle"] = { spellId = 0, reagents = { { name = "Fiery Core", count = 4 }, { name = "Lava Core", count = 2 }, { name = "Arcanite Bar", count = 6 }, { name = "Delicate Arcanite Converter", count = 2 }, { name = "Thorium Tube", count = 2 } } },
    ["Craftsman's Monocle"] = { spellId = 0, reagents = { { name = "Citrine", count = 2 }, { name = "Heavy Leather", count = 6 } } },
    ["Crude Scope"] = { spellId = 0, reagents = { { name = "Malachite", count = 1 }, { name = "Copper Bar", count = 2 }, { name = "Handful of Copper Bolts", count = 1 } } },
    ["Dark Iron Bomb"] = { spellId = 0, reagents = { { name = "Dark Iron Bar", count = 1 }, { name = "Dense Blasting Powder", count = 3 }, { name = "Runecloth", count = 3 }, { name = "Thorium Widget", count = 2 } } },
    ["Dark Iron Rifle"] = { spellId = 0, reagents = { { name = "Blue Sapphire", count = 2 }, { name = "Large Opal", count = 2 }, { name = "Dark Iron Bar", count = 6 }, { name = "Deadly Scope", count = 2 }, { name = "Rugged Leather", count = 4 } } },
    ["Deadly Blunderbuss"] = { spellId = 0, reagents = { { name = "Bronze Tube", count = 4 }, { name = "Standard Scope", count = 1 }, { name = "Wooden Stock", count = 1 } } },
    ["Deadly Scope"] = { spellId = 0, reagents = { { name = "Aquamarine", count = 2 }, { name = "Mithril Tube", count = 1 }, { name = "Thick Leather", count = 2 } } },
    ["Deepdive Helmet"] = { spellId = 0, reagents = { { name = "Malachite", count = 4 }, { name = "Tigerseye", count = 4 }, { name = "Truesilver Bar", count = 1 }, { name = "Mithril Bar", count = 8 }, { name = "Mithril Casing", count = 1 } } },
    ["Delicate Arcanite Converter"] = { spellId = 0, reagents = { { name = "Arcanite Bar", count = 1 }, { name = "Ironweb Spider Silk", count = 1 } } },
    ["Dense Blasting Powder"] = { spellId = 0, reagents = { { name = "Dense Stone", count = 2 } } },
    ["Dense Dynamite"] = { spellId = 0, reagents = { { name = "Dense Blasting Powder", count = 2 }, { name = "Runecloth", count = 3 } } },
    ["Discombobulator Ray"] = { spellId = 0, reagents = { { name = "Jade", count = 1 }, { name = "Bronze Tube", count = 1 }, { name = "Silk Cloth", count = 2 }, { name = "Whirring Bronze Gizmo", count = 3 } } },
    ["Explosive Sheep"] = { spellId = 0, reagents = { { name = "Bronze Framework", count = 1 }, { name = "Heavy Blasting Powder", count = 2 }, { name = "Whirring Bronze Gizmo", count = 1 }, { name = "Wool Cloth", count = 2 } } },
    ["Ez-Thro Dynamite II"] = { spellId = 0, reagents = { { name = "Mageweave Cloth", count = 2 }, { name = "Solid Blasting Powder", count = 1 } } },
    ["Ez-Thro Dynamite"] = { spellId = 0, reagents = { { name = "Coarse Blasting Powder", count = 4 }, { name = "Wool Cloth", count = 1 } } },
    ["Field Repair Bot 74A"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 16 }, { name = "Fused Wiring", count = 1 } } },
    ["Fire Goggles"] = { spellId = 0, reagents = { { name = "Citrine", count = 2 }, { name = "Green Tinted Goggles", count = 1 }, { name = "Elemental Fire", count = 2 }, { name = "Heavy Leather", count = 4 } } },
    ["Firework Launcher"] = { spellId = 0, reagents = { { name = "Goblin Rocket Fuel", count = 1 }, { name = "Inlaid Mithril Cylinder", count = 1 }, { name = "Mithril Casing", count = 1 }, { name = "Unstable Trigger", count = 1 } } },
    ["Flame Deflector"] = { spellId = 0, reagents = { { name = "Small Flame Sac", count = 1 }, { name = "Whirring Bronze Gizmo", count = 1 } } },
    ["Flash Bomb"] = { spellId = 0, reagents = { { name = "Blue Pearl", count = 1 }, { name = "Heavy Blasting Powder", count = 1 }, { name = "Silk Cloth", count = 1 } } },
    ["Flawless Arcanite Rifle"] = { spellId = 0, reagents = { { name = "Azerothian Diamond", count = 2 }, { name = "Arcanite Bar", count = 10 }, { name = "Essence of Earth", count = 2 }, { name = "Essence of Fire", count = 2 }, { name = "Enchanted Leather", count = 2 }, { name = "Thorium Tube", count = 2 } } },
    ["Flying Tiger Goggles"] = { spellId = 0, reagents = { { name = "Tigerseye", count = 2 }, { name = "Light Leather", count = 6 } } },
    ["Force Reactive Disk"] = { spellId = 0, reagents = { { name = "Arcanite Bar", count = 6 }, { name = "Essence of Air", count = 8 }, { name = "Essence of Earth", count = 8 }, { name = "Living Essence", count = 12 }, { name = "Delicate Arcanite Converter", count = 2 } } },
    ["Fused Wiring"] = { spellId = 0, reagents = { { name = "Delicate Copper Wire", count = 3 }, { name = "Essence of Fire", count = 2 } } },
    ["Gnomish Cloaking Device"] = { spellId = 0, reagents = { { name = "Citrine", count = 2 }, { name = "Jade", count = 2 }, { name = "Lesser Moonstone", count = 2 }, { name = "Fused Wiring", count = 1 }, { name = "Gyrochronatom", count = 4 } } },
    ["Gnomish Universal Remote"] = { spellId = 0, reagents = { { name = "Malachite", count = 1 }, { name = "Tigerseye", count = 1 }, { name = "Bronze Bar", count = 6 }, { name = "Flask of Oil", count = 2 }, { name = "Whirring Bronze Gizmo", count = 1 } } },
    ["Goblin Jumper Cables"] = { spellId = 0, reagents = { { name = "Shadowgem", count = 2 }, { name = "Iron Bar", count = 6 }, { name = "Flask of Oil", count = 2 }, { name = "Fused Wiring", count = 1 }, { name = "Silk Cloth", count = 2 }, { name = "Whirring Bronze Gizmo", count = 2 } } },
    ["Goblin Land Mine"] = { spellId = 0, reagents = { { name = "Iron Bar", count = 2 }, { name = "Gyrochronatom", count = 1 }, { name = "Heavy Blasting Powder", count = 3 } } },
    ["Gold Power Core"] = { spellId = 0, reagents = { { name = "Gold Bar", count = 1 } } },
    ["Green Firework"] = { spellId = 0, reagents = { { name = "Heavy Blasting Powder", count = 1 }, { name = "Heavy Leather", count = 1 } } },
    ["Green Lens"] = { spellId = 0, reagents = { { name = "Aquamarine", count = 3 }, { name = "Jade", count = 3 }, { name = "Heart of the Wild (crafting reagent)", count = 2 }, { name = "Thick Leather", count = 8 }, { name = "Wildvine", count = 2 } } },
    ["Green Rocket Cluster"] = { spellId = 0, reagents = { { name = "Solid Blasting Powder", count = 1 }, { name = "Thick Leather", count = 1 } } },
    ["Green Tinted Goggles"] = { spellId = 0, reagents = { { name = "Moss Agate", count = 2 }, { name = "Flying Tiger Goggles", count = 1 }, { name = "Medium Leather", count = 4 } } },
    ["Gyrochronatom"] = { spellId = 0, reagents = { { name = "Iron Bar", count = 1 }, { name = "Gold Power Core", count = 1 } } },
    ["Gyrofreeze Ice Reflector"] = { spellId = 0, reagents = { { name = "Blue Sapphire", count = 2 }, { name = "Essence of Fire", count = 4 }, { name = "Frost Oil", count = 2 }, { name = "Icecap", count = 4 }, { name = "Thorium Widget", count = 6 }, { name = "Truesilver Transformer", count = 2 } } },
    ["Gyromatic Micro-Adjustor"] = { spellId = 0, reagents = { { name = "Steel Bar", count = 4 } } },
    ["Handful of Copper Bolts"] = { spellId = 0, reagents = { { name = "Copper Bar", count = 1 } } },
    ["Heavy Blasting Powder"] = { spellId = 0, reagents = { { name = "Heavy Stone", count = 1 } } },
    ["Heavy Dynamite"] = { spellId = 0, reagents = { { name = "Heavy Blasting Powder", count = 2 }, { name = "Wool Cloth", count = 1 } } },
    ["Hi-Explosive Bomb"] = { spellId = 0, reagents = { { name = "Mithril Casing", count = 2 }, { name = "Solid Blasting Powder", count = 2 }, { name = "Unstable Trigger", count = 1 } } },
    ["High-Powered Flashlight"] = { spellId = 0, reagents = { { name = "Thorium Widget", count = 4 }, { name = "Truesilver Bar", count = 6 }, { name = "Essence of Fire", count = 6 } } },
    ["Hyper-Radiant Flame Reflector"] = { spellId = 0, reagents = { { name = "Azerothian Diamond", count = 2 }, { name = "Star Ruby", count = 4 }, { name = "Dark Iron Bar", count = 4 }, { name = "Essence of Water", count = 6 }, { name = "Truesilver Transformer", count = 3 } } },
    ["Ice Deflector"] = { spellId = 0, reagents = { { name = "Frost Oil", count = 1 }, { name = "Whirring Bronze Gizmo", count = 1 } } },
    ["Iron Grenade"] = { spellId = 0, reagents = { { name = "Iron Bar", count = 1 }, { name = "Heavy Blasting Powder", count = 1 }, { name = "Silk Cloth", count = 1 } } },
    ["Iron Strut"] = { spellId = 0, reagents = { { name = "Iron Bar", count = 2 } } },
    ["Large Blue Rocket Cluster"] = { spellId = 0, reagents = { { name = "Dense Blasting Powder", count = 1 }, { name = "Rugged Leather", count = 1 } } },
    ["Large Blue Rocket"] = { spellId = 0, reagents = { { name = "Heavy Blasting Powder", count = 1 }, { name = "Heavy Leather", count = 1 } } },
    ["Large Copper Bomb"] = { spellId = 0, reagents = { { name = "Copper Bar", count = 3 }, { name = "Coarse Blasting Powder", count = 4 }, { name = "Silver Contact", count = 1 } } },
    ["Large Green Rocket Cluster"] = { spellId = 0, reagents = { { name = "Dense Blasting Powder", count = 1 }, { name = "Rugged Leather", count = 1 } } },
    ["Large Green Rocket"] = { spellId = 0, reagents = { { name = "Heavy Blasting Powder", count = 1 }, { name = "Heavy Leather", count = 1 } } },
    ["Large Red Rocket Cluster"] = { spellId = 0, reagents = { { name = "Dense Blasting Powder", count = 1 }, { name = "Rugged Leather", count = 1 } } },
    ["Large Red Rocket"] = { spellId = 0, reagents = { { name = "Heavy Blasting Powder", count = 1 }, { name = "Heavy Leather", count = 1 } } },
    ["Large Seaforium Charge"] = { spellId = 0, reagents = { { name = "Heavy Leather", count = 2 }, { name = "Refreshing Spring Water", count = 1 }, { name = "Solid Blasting Powder", count = 2 } } },
    ["Lifelike Mechanical Toad"] = { spellId = 0, reagents = { { name = "Living Essence", count = 1 }, { name = "Gold Power Core", count = 1 }, { name = "Rugged Leather", count = 1 }, { name = "Thorium Widget", count = 4 } } },
    ["Lil' Smoky"] = { spellId = 0, reagents = { { name = "Truesilver Bar", count = 1 }, { name = "Mithril Bar", count = 2 }, { name = "Core of Earth", count = 1 }, { name = "Fused Wiring", count = 1 }, { name = "Gyrochronatom", count = 2 } } },
    ["Lovingly Crafted Boomstick"] = { spellId = 0, reagents = { { name = "Moss Agate", count = 3 }, { name = "Bronze Tube", count = 2 }, { name = "Handful of Copper Bolts", count = 2 }, { name = "Heavy Stock", count = 1 } } },
    ["Major Recombobulator"] = { spellId = 0, reagents = { { name = "Runecloth", count = 2 }, { name = "Thorium Tube", count = 2 }, { name = "Truesilver Transformer", count = 1 } } },
    ["Master Engineer's Goggles"] = { spellId = 0, reagents = { { name = "Huge Emerald", count = 2 }, { name = "Fire Goggles", count = 1 }, { name = "Enchanted Leather", count = 4 } } },
    ["Masterwork Target Dummy"] = { spellId = 0, reagents = { { name = "Truesilver Bar", count = 1 }, { name = "Mithril Casing", count = 1 }, { name = "Rugged Leather", count = 2 }, { name = "Runecloth", count = 4 }, { name = "Thorium Tube", count = 1 }, { name = "Thorium Widget", count = 2 } } },
    ["Mechanical Dragonling"] = { spellId = 0, reagents = { { name = "Citrine", count = 1 }, { name = "Bronze Framework", count = 1 }, { name = "Gyrochronatom", count = 2 }, { name = "Iron Strut", count = 2 } } },
    ["Mechanical Repair Kit"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 1 }, { name = "Mageweave Cloth", count = 1 }, { name = "Solid Blasting Powder", count = 1 } } },
    ["Mechanical Squirrel Box"] = { spellId = 0, reagents = { { name = "Malachite", count = 2 }, { name = "Copper Bar", count = 1 }, { name = "Handful of Copper Bolts", count = 1 } } },
    ["Minor Recombobulator"] = { spellId = 0, reagents = { { name = "Moss Agate", count = 1 }, { name = "Bronze Tube", count = 1 }, { name = "Medium Leather", count = 2 }, { name = "Whirring Bronze Gizmo", count = 2 } } },
    ["Mithril Blunderbuss"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 4 }, { name = "Elemental Fire", count = 2 }, { name = "Heavy Stock", count = 1 }, { name = "Mithril Tube", count = 1 }, { name = "Unstable Trigger", count = 1 } } },
    ["Mithril Casing"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 3 } } },
    ["Mithril Frag Bomb"] = { spellId = 0, reagents = { { name = "Mithril Casing", count = 1 }, { name = "Solid Blasting Powder", count = 1 }, { name = "Unstable Trigger", count = 1 } } },
    ["Mithril Heavy-Bore Rifle"] = { spellId = 0, reagents = { { name = "Citrine", count = 2 }, { name = "Mithril Bar", count = 6 }, { name = "Heavy Stock", count = 1 }, { name = "Mithril Tube", count = 2 }, { name = "Unstable Trigger", count = 1 } } },
    ["Mithril Mechanical Dragonling"] = { spellId = 0, reagents = { { name = "Star Ruby", count = 2 }, { name = "Truesilver Bar", count = 4 }, { name = "Mithril Bar", count = 14 }, { name = "Goblin Rocket Fuel", count = 2 }, { name = "Heart of Fire", count = 4 }, { name = "Inlaid Mithril Cylinder", count = 2 } } },
    ["Mithril Tube"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 3 } } },
    ["Moonsight Rifle"] = { spellId = 0, reagents = { { name = "Lesser Moonstone", count = 2 }, { name = "Bronze Tube", count = 3 }, { name = "Heavy Stock", count = 1 }, { name = "Whirring Bronze Gizmo", count = 3 } } },
    ["Ornate Spyglass"] = { spellId = 0, reagents = { { name = "Moss Agate", count = 1 }, { name = "Bronze Tube", count = 2 }, { name = "Copper Modulator", count = 1 }, { name = "Whirring Bronze Gizmo", count = 2 } } },
    ["Parachute Cloak"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 4 }, { name = "Shadow Silk", count = 2 }, { name = "Solid Blasting Powder", count = 4 }, { name = "Unstable Trigger", count = 1 } } },
    ["Pet Bombling"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 6 }, { name = "Big Iron Bomb", count = 1 }, { name = "Fused Wiring", count = 1 }, { name = "Heart of Fire", count = 1 } } },
    ["Portable Bronze Mortar"] = { spellId = 0, reagents = { { name = "Bronze Tube", count = 4 }, { name = "Heavy Blasting Powder", count = 4 }, { name = "Iron Strut", count = 1 }, { name = "Medium Leather", count = 4 } } },
    ["Powerful Seaforium Charge"] = { spellId = 0, reagents = { { name = "Dense Blasting Powder", count = 3 }, { name = "Refreshing Spring Water", count = 1 }, { name = "Rugged Leather", count = 2 }, { name = "Thorium Widget", count = 2 } } },
    ["Red Firework"] = { spellId = 0, reagents = { { name = "Heavy Blasting Powder", count = 1 }, { name = "Heavy Leather", count = 1 } } },
    ["Red Rocket Cluster"] = { spellId = 0, reagents = { { name = "Solid Blasting Powder", count = 1 }, { name = "Thick Leather", count = 1 } } },
    ["Rose Colored Goggles"] = { spellId = 0, reagents = { { name = "Star Ruby", count = 2 }, { name = "Thick Leather", count = 6 } } },
    ["Rough Blasting Powder"] = { spellId = 0, reagents = { { name = "Rough Stone", count = 1 } } },
    ["Rough Boomstick"] = { spellId = 0, reagents = { { name = "Copper Bar", count = 4 }, { name = "Handful of Copper Bolts", count = 3 }, { name = "Wooden Stock", count = 1 } } },
    ["Rough Copper Bomb"] = { spellId = 0, reagents = { { name = "Handful of Copper Bolts", count = 1 }, { name = "Rough Blasting Powder", count = 2 } } },
    ["Rough Dynamite"] = { spellId = 0, reagents = { { name = "Rough Blasting Powder", count = 1 }, { name = "Linen Cloth", count = 1 } } },
    ["Shadow Goggles"] = { spellId = 0, reagents = { { name = "Shadowgem", count = 2 }, { name = "Medium Leather", count = 4 } } },
    ["Silver Contact"] = { spellId = 0, reagents = { { name = "Silver Bar", count = 1 } } },
    ["Silver-plated Shotgun"] = { spellId = 0, reagents = { { name = "Silver Bar", count = 3 }, { name = "Bronze Tube", count = 2 }, { name = "Heavy Stock", count = 1 }, { name = "Whirring Bronze Gizmo", count = 2 } } },
    ["Small Blue Rocket"] = { spellId = 0, reagents = { { name = "Coarse Blasting Powder", count = 1 }, { name = "Medium Leather", count = 1 } } },
    ["Small Bronze Bomb"] = { spellId = 0, reagents = { { name = "Bronze Bar", count = 2 }, { name = "Coarse Blasting Powder", count = 4 }, { name = "Silver Contact", count = 1 }, { name = "Wool Cloth", count = 1 } } },
    ["Small Green Rocket"] = { spellId = 0, reagents = { { name = "Coarse Blasting Powder", count = 1 }, { name = "Medium Leather", count = 1 } } },
    ["Small Red Rocket"] = { spellId = 0, reagents = { { name = "Coarse Blasting Powder", count = 1 }, { name = "Medium Leather", count = 1 } } },
    ["Small Seaforium Charge"] = { spellId = 0, reagents = { { name = "Coarse Blasting Powder", count = 2 }, { name = "Copper Modulator", count = 1 }, { name = "Light Leather", count = 1 }, { name = "Refreshing Spring Water", count = 1 } } },
    ["Snake Burst Firework"] = { spellId = 0, reagents = { { name = "Deeprock Salt", count = 1 }, { name = "Dense Blasting Powder", count = 2 }, { name = "Runecloth", count = 2 } } },
    ["Sniper Scope"] = { spellId = 0, reagents = { { name = "Star Ruby", count = 1 }, { name = "Truesilver Bar", count = 2 }, { name = "Mithril Tube", count = 1 } } },
    ["Snowmaster 9000"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 8 }, { name = "Frost Oil", count = 1 }, { name = "Gyrochronatom", count = 4 }, { name = "Snowball", count = 4 } } },
    ["Solid Blasting Powder"] = { spellId = 0, reagents = { { name = "Solid Stone", count = 2 } } },
    ["Solid Dynamite"] = { spellId = 0, reagents = { { name = "Silk Cloth", count = 1 }, { name = "Solid Blasting Powder", count = 1 } } },
    ["Spellpower Goggles Xtreme Plus"] = { spellId = 0, reagents = { { name = "Star Ruby", count = 4 }, { name = "Spellpower Goggles Xtreme", count = 1 }, { name = "Enchanted Leather", count = 2 }, { name = "Runecloth", count = 8 } } },
    ["Spellpower Goggles Xtreme"] = { spellId = 0, reagents = { { name = "Star Ruby", count = 2 }, { name = "Thick Leather", count = 4 } } },
    ["Standard Scope"] = { spellId = 0, reagents = { { name = "Moss Agate", count = 1 }, { name = "Bronze Tube", count = 1 } } },
    ["Steam Tonk Controller"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 3 }, { name = "Gold Power Core", count = 1 } } },
    ["Target Dummy"] = { spellId = 0, reagents = { { name = "Bronze Bar", count = 2 }, { name = "Wool Cloth", count = 2 } } },
    ["Thorium Grenade"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 3 }, { name = "Dense Blasting Powder", count = 3 }, { name = "Runecloth", count = 3 }, { name = "Thorium Widget", count = 1 } } },
    ["Thorium Rifle"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 4 }, { name = "Deadly Scope", count = 1 }, { name = "Mithril Casing", count = 2 }, { name = "Mithril Tube", count = 2 }, { name = "Thorium Widget", count = 2 } } },
    ["Thorium Tube"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 6 } } },
    ["Thorium Widget"] = { spellId = 0, reagents = { { name = "Thorium Bar", count = 3 }, { name = "Runecloth", count = 1 } } },
    ["Tranquil Mechanical Yeti"] = { spellId = 0, reagents = { { name = "Cured Rugged Hide", count = 1 }, { name = "Globe of Water", count = 2 }, { name = "Gold Power Core", count = 1 }, { name = "Thorium Widget", count = 4 }, { name = "Truesilver Transformer", count = 2 } } },
    ["Truesilver Transformer"] = { spellId = 0, reagents = { { name = "Truesilver Bar", count = 2 }, { name = "Elemental Air", count = 1 }, { name = "Elemental Earth", count = 2 } } },
    ["Ultra-Flash Shadow Reflector"] = { spellId = 0, reagents = { { name = "Azerothian Diamond", count = 2 }, { name = "Large Opal", count = 2 }, { name = "Dark Iron Bar", count = 8 }, { name = "Essence of Undeath", count = 4 }, { name = "Living Essence", count = 6 }, { name = "Truesilver Transformer", count = 4 } } },
    ["Unstable Trigger"] = { spellId = 0, reagents = { { name = "Mithril Bar", count = 1 }, { name = "Mageweave Cloth", count = 1 }, { name = "Solid Blasting Powder", count = 1 } } },
    ["Voice Amplification Modulator"] = { spellId = 0, reagents = { { name = "Large Opal", count = 1 }, { name = "Delicate Arcanite Converter", count = 2 }, { name = "Gold Power Core", count = 1 }, { name = "Thorium Widget", count = 1 } } },
    ["Whirring Bronze Gizmo"] = { spellId = 0, reagents = { { name = "Bronze Bar", count = 2 }, { name = "Wool Cloth", count = 1 } } },
}
