GuildShoppingList_LeatherworkingPatterns  = {
    ["Barbaric Belt"] = { spellId = 0, reagents = { { name = "Heavy Leather", count = 6 }, { name = "Cured Heavy Hide", count = 2 }, { name = "Coarse Gorilla Hair", count = 2 }, { name = "Great Rage Potion", count = 1 }, { name = "Silken Thread", count = 1 }, { name = "Iron Buckle", count = 1 } } },
    ["Barbaric Bracers"] = { spellId = 0, reagents = { { name = "Heavy Leather", count = 8 }, { name = "Small Lustrous Pearl", count = 4 }, { name = "Large Fang", count = 4 }, { name = "Cured Heavy Hide", count = 2 }, { name = "Raptor Hide", count = 1 } } },
    ["Barbaric Gloves"] = { spellId = 0, reagents = { { name = "Heavy Leather", count = 6 }, { name = "Large Fang", count = 2 }, { name = "Fine Thread", count = 1 } } },
    ["Barbaric Harness"] = { spellId = 0, reagents = { { name = "Heavy Leather", count = 14 }, { name = "Fine Thread", count = 2 }, { name = "Iron Buckle", count = 1 } } },
    ["Barbaric Leggings"] = { spellId = 0, reagents = { { name = "Heavy Leather", count = 10 }, { name = "Fine Thread", count = 2 }, { name = "Moss Agate", count = 1 } } },
    ["Barbaric Shoulders"] = { spellId = 0, reagents = { { name = "Heavy Leather", count = 8 }, { name = "Fine Thread", count = 2 }, { name = "Cured Heavy Hide", count = 1 } } },
    ["Big Voodoo Cloak"] = { spellId = 0, reagents = { { name = "Thick Leather", count = 14 }, { name = "Heavy Silken Thread", count = 2 } } },
    ["Big Voodoo Mask"] = { spellId = 0, reagents = { { name = "Thick Leather", count = 8 }, { name = "Heavy Silken Thread", count = 1 } } },
    ["Big Voodoo Pants"] = { spellId = 0, reagents = { { name = "Thick Leather", count = 10 }, { name = "Heavy Silken Thread", count = 2 } } },
    ["Big Voodoo Robe"] = { spellId = 0, reagents = { { name = "Thick Leather", count = 10 }, { name = "Heavy Silken Thread", count = 1 } } },
    ["Black Dragonscale Boots"] = { spellId = 0, reagents = { { name = "Black Dragonscale", count = 30 }, { name = "Enchanted Leather", count = 6 }, { name = "Fiery Core", count = 4 }, { name = "Lava Core", count = 3 }, { name = "Rune Thread", count = 2 } } },
    ["Black Dragonscale Breastplate"] = { spellId = 0, reagents = { { name = "Black Dragonscale", count = 60 }, { name = "Rugged Leather", count = 40 }, { name = "Rune Thread", count = 2 }, { name = "Cured Rugged Hide", count = 1 } } },
    ["Black Dragonscale Leggings"] = { spellId = 0, reagents = { { name = "Black Dragonscale", count = 60 }, { name = "Rugged Leather", count = 40 }, { name = "Enchanted Leather", count = 4 }, { name = "Rune Thread", count = 2 }, { name = "Cured Rugged Hide", count = 1 } } },
    ["Black Dragonscale Shoulders"] = { spellId = 0, reagents = { { name = "Black Dragonscale", count = 45 }, { name = "Rugged Leather", count = 44 }, { name = "Enchanted Leather", count = 2 }, { name = "Rune Thread", count = 1 }, { name = "Cured Rugged Hide", count = 1 } } },
    ["Black Whelp Cloak"] = { spellId = 0, reagents = { { name = "Black Whelp Scale", count = 12 }, { name = "Medium Leather", count = 4 }, { name = "Fine Thread", count = 1 } } },
    ["Black Whelp Tunic"] = { spellId = 0, reagents = { { name = "Medium Leather", count = 8 }, { name = "Black Whelp Scale", count = 8 }, { name = "Fine Thread", count = 2 }, { name = "Cured Light Hide", count = 1 } } },
    ["Blackstorm Leggings"] = { spellId = 0, reagents = { { name = "Rugged Leather", count = 10 }, { name = "Breath of Wind", count = 8 }, { name = "Cured Thick Hide", count = 2 }, { name = "Rune Thread", count = 1 } } },
    ["Blood Tiger Breastplate"] = { spellId = 0, reagents = { { name = "Primal Tiger Leather", count = 35 }, { name = "Rune Thread", count = 3 }, { name = "Cured Rugged Hide", count = 3 }, { name = "Bloodvine", count = 2 } } },
    ["Blood Tiger Shoulders"] = { spellId = 0, reagents = { { name = "Primal Tiger Leather", count = 25 }, { name = "Rune Thread", count = 3 }, { name = "Cured Rugged Hide", count = 3 }, { name = "Bloodvine", count = 2 } } },
    ["Blue Dragonscale Breastplate"] = { spellId = 0, reagents = { { name = "Blue Dragonscale", count = 30 }, { name = "Rugged Leather", count = 28 }, { name = "Rune Thread", count = 1 }, { name = "Cured Rugged Hide", count = 1 } } },
    ["Blue Dragonscale Leggings"] = { spellId = 0, reagents = { { name = "Blue Dragonscale", count = 36 }, { name = "Rugged Leather", count = 28 }, { name = "Rune Thread", count = 2 }, { name = "Cured Rugged Hide", count = 2 } } },
    ["Blue Dragonscale Shoulders"] = { spellId = 0, reagents = { { name = "Blue Dragonscale", count = 30 }, { name = "Rugged Leather", count = 28 }, { name = "Enchanted Leather", count = 2 }, { name = "Rune Thread", count = 1 }, { name = "Cured Rugged Hide", count = 1 } } },
    ["Bramblewood Belt"] = { spellId = 0, reagents = { { name = "Enchanted Leather", count = 4 }, { name = "Living Essence", count = 2 }, { name = "Cured Rugged Hide", count = 1 } } },
    ["Bramblewood Boots"] = { spellId = 0, reagents = { { name = "Enchanted Leather", count = 6 }, { name = "Living Essence", count = 2 }, { name = "Larval Acid", count = 2 }, { name = "Cured Rugged Hide", count = 2 } } },
    ["Bramblewood Helm"] = { spellId = 0, reagents = { { name = "Enchanted Leather", count = 12 }, { name = "Living Essence", count = 2 }, { name = "Cured Rugged Hide", count = 2 }, { name = "Bloodvine", count = 2 } } },
    ["Chimeric Boots"] = { spellId = 0, reagents = { { name = "Chimera Leather", count = 8 }, { name = "Rugged Leather", count = 4 }, { name = "Rune Thread", count = 1 } } },
    ["Chimeric Gloves"] = { spellId = 0, reagents = { { name = "Rugged Leather", count = 6 }, { name = "Living Essence", count = 1 }, { name = "Rune Thread", count = 1 } } },
    ["Chimeric Leggings"] = { spellId = 0, reagents = { { name = "Rugged Leather", count = 8 }, { name = "Chimera Leather", count = 8 }, { name = "Rune Thread", count = 1 } } },
    ["Chimeric Vest"] = { spellId = 0, reagents = { { name = "Rugged Leather", count = 10 }, { name = "Chimera Leather", count = 10 }, { name = "Rune Thread", count = 1 } } },
    ["Chromatic Cloak"] = { spellId = 0, reagents = { { name = "Rugged Leather", count = 30 }, { name = "Red Dragonscale", count = 30 }, { name = "Black Dragonscale", count = 30 }, { name = "Brilliant Chromatic Scale", count = 12 }, { name = "Rune Thread", count = 8 }, { name = "Cured Rugged Hide", count = 5 } } },
    ["Chromatic Gauntlets"] = { spellId = 0, reagents = { { name = "Fiery Core", count = 5 }, { name = "Ironweb Spider Silk", count = 4 }, { name = "Cured Rugged Hide", count = 4 }, { name = "Core Leather", count = 4 }, { name = "Brilliant Chromatic Scale", count = 4 }, { name = "Lava Core", count = 2 } } },
    ["Comfortable Insoles"] = { spellId = 0, reagents = { { name = "Knothide Leather", count = 2 } } },
    ["Comfortable Leather Hat"] = { spellId = 0, reagents = { { name = "Heavy Leather", count = 12 }, { name = "Cured Heavy Hide", count = 2 }, { name = "Silken Thread", count = 2 } } },
    ["Core Armor Kit"] = { spellId = 0, reagents = { { name = "Core Leather", count = 3 }, { name = "Rune Thread", count = 2 } } },
    ["Corehound Belt"] = { spellId = 0, reagents = { { name = "Core Leather", count = 12 }, { name = "Enchanted Leather", count = 10 }, { name = "Fiery Core", count = 8 }, { name = "Ironweb Spider Silk", count = 4 }, { name = "Cured Rugged Hide", count = 4 } } },
    ["Corehound Boots"] = { spellId = 0, reagents = { { name = "Core Leather", count = 20 }, { name = "Fiery Core", count = 6 }, { name = "Rune Thread", count = 2 }, { name = "Lava Core", count = 2 } } },
    ["Cured Heavy Hide"] = { spellId = 0, reagents = { { name = "Salt", count = 3 }, { name = "Heavy Hide", count = 1 } } },
    ["Cured Light Hide"] = { spellId = 0, reagents = { { name = "Light Hide", count = 1 }, { name = "Salt", count = 1 } } },
    ["Cured Medium Hide"] = { spellId = 0, reagents = { { name = "Medium Hide", count = 1 }, { name = "Salt", count = 1 } } },
    ["Cured Rugged Hide"] = { spellId = 0, reagents = { { name = "Rugged Hide", count = 1 }, { name = "Refined Deeprock Salt", count = 1 } } },
    ["Cured Thick Hide"] = { spellId = 0, reagents = { { name = "Thick Hide", count = 1 }, { name = "Deeprock Salt", count = 1 } } },
    ["Dark Leather Belt"] = { spellId = 0, reagents = { { name = "Fine Thread", count = 2 }, { name = "Gray Dye", count = 1 }, { name = "Fine Leather Belt", count = 1 }, { name = "Cured Medium Hide", count = 1 } } },
    ["Dark Leather Boots"] = { spellId = 0, reagents = { { name = "Medium Leather", count = 4 }, { name = "Fine Thread", count = 2 }, { name = "Gray Dye", count = 1 } } },
    ["Dark Leather Cloak"] = { spellId = 0, reagents = { { name = "Medium Leather", count = 8 }, { name = "Fine Thread", count = 1 }, { name = "Gray Dye", count = 1 } } },
    ["Dark Leather Gloves"] = { spellId = 0, reagents = { { name = "Gray Dye", count = 1 }, { name = "Fine Thread", count = 1 }, { name = "Fine Leather Gloves", count = 1 }, { name = "Cured Medium Hide", count = 1 } } },
    ["Dark Leather Pants"] = { spellId = 0, reagents = { { name = "Medium Leather", count = 12 }, { name = "Gray Dye", count = 1 }, { name = "Fine Thread", count = 1 } } },
    ["Dark Leather Shoulders"] = { spellId = 0, reagents = { { name = "Medium Leather", count = 12 }, { name = "Fine Thread", count = 2 }, { name = "Gray Dye", count = 1 }, { name = "Elixir of Lesser Agility", count = 1 } } },
    ["Dark Leather Tunic"] = { spellId = 0, reagents = { { name = "Medium Leather", count = 6 }, { name = "Fine Thread", count = 1 }, { name = "Gray Dye", count = 1 } } },
    ["Dawn Treaders"] = { spellId = 0, reagents = { { name = "Rugged Leather", count = 30 }, { name = "Essence of Water", count = 4 }, { name = "Rune Thread", count = 2 }, { name = "Guardian Stone", count = 2 }, { name = "Cured Rugged Hide", count = 2 } } },
    ["Deviate Scale Belt"] = { spellId = 0, reagents = { { name = "Perfect Deviate Scale", count = 6 }, { name = "Deviate Scale", count = 4 }, { name = "Fine Thread", count = 2 } } },
    ["Deviate Scale Cloak"] = { spellId = 0, reagents = { { name = "Deviate Scale", count = 4 }, { name = "Cured Light Hide", count = 1 }, { name = "Fine Thread", count = 1 } } },
    ["Deviate Scale Gloves"] = { spellId = 0, reagents = { { name = "Deviate Scale", count = 5 }, { name = "Fine Thread", count = 2 } } },
    ["Devilsaur Gauntlets"] = { spellId = 0, reagents = { { name = "Rugged Leather", count = 30 }, { name = "Devilsaur Leather", count = 8 }, { name = "Rune Thread", count = 1 } } },
    ["Devilsaur Leggings"] = { spellId = 0, reagents = { { name = "Rugged Leather", count = 30 }, { name = "Devilsaur Leather", count = 14 }, { name = "Cured Rugged Hide", count = 1 }, { name = "Rune Thread", count = 1 } } },
    ["Dragonscale Breastplate"] = { spellId = 0, reagents = { { name = "Thick Leather", count = 40 }, { name = "Worn Dragonscale", count = 30 }, { name = "Heavy Silken Thread", count = 4 }, { name = "Cured Thick Hide", count = 4 } } },
    ["Dragonscale Gauntlets"] = { spellId = 0, reagents = { { name = "Thick Leather", count = 24 }, { name = "Worn Dragonscale", count = 12 }, { name = "Heavy Silken Thread", count = 4 }, { name = "Cured Thick Hide", count = 2 } } },
    ["Dragonstrike Leggings"] = { spellId = 0, reagents = { { name = "Rugged Leather", count = 10 }, { name = "Worn Dragonscale", count = 10 }, { name = "Heart of Fire", count = 2 }, { name = "Cured Thick Hide", count = 2 }, { name = "Rune Thread", count = 1 } } },
    ["Dreamscale Breastplate"] = { spellId = 0, reagents = { { name = "Enchanted Leather", count = 12 }, { name = "Ironweb Spider Silk", count = 6 }, { name = "Dreamscale", count = 6 }, { name = "Living Essence", count = 4 }, { name = "Cured Rugged Hide", count = 4 } } },
    ["Dusky Belt"] = { spellId = 0, reagents = { { name = "Heavy Leather", count = 10 }, { name = "Bolt of Silk Cloth", count = 2 }, { name = "Black Dye", count = 2 }, { name = "Iron Buckle", count = 1 } } },
    ["Dusky Boots"] = { spellId = 0, reagents = { { name = "Heavy Leather", count = 8 }, { name = "Shadow Silk", count = 2 }, { name = "Silken Thread", count = 2 } } },
    ["Dusky Bracers"] = { spellId = 0, reagents = { { name = "Heavy Leather", count = 16 }, { name = "Silken Thread", count = 2 }, { name = "Black Dye", count = 1 } } },
    ["Dusky Leather Armor"] = { spellId = 0, reagents = { { name = "Heavy Leather", count = 10 }, { name = "Fine Thread", count = 2 }, { name = "Shadow Oil", count = 1 } } },
    ["Dusky Leather Leggings"] = { spellId = 0, reagents = { { name = "Heavy Leather", count = 10 }, { name = "Fine Thread", count = 2 }, { name = "Black Dye", count = 1 } } },
    ["Earthen Leather Shoulders"] = { spellId = 0, reagents = { { name = "Medium Leather", count = 6 }, { name = "Fine Thread", count = 2 }, { name = "Elemental Earth", count = 1 } } },
    ["Embossed Leather Boots"] = { spellId = 0, reagents = { { name = "Light Leather", count = 8 }, { name = "Coarse Thread", count = 5 } } },
    ["Embossed Leather Cloak"] = { spellId = 0, reagents = { { name = "Light Leather", count = 5 }, { name = "Coarse Thread", count = 2 } } },
    ["Embossed Leather Gloves"] = { spellId = 0, reagents = { { name = "Light Leather", count = 3 }, { name = "Coarse Thread", count = 2 } } },
    ["Embossed Leather Pants"] = { spellId = 0, reagents = { { name = "Light Leather", count = 6 }, { name = "Coarse Thread", count = 2 }, { name = "Cured Light Hide", count = 1 } } },
    ["Embossed Leather Vest"] = { spellId = 0, reagents = { { name = "Light Leather", count = 8 }, { name = "Coarse Thread", count = 4 } } },
    ["Feathered Breastplate"] = { spellId = 0, reagents = { { name = "Thick Leather", count = 40 }, { name = "Jet Black Feather", count = 40 }, { name = "Heavy Silken Thread", count = 4 }, { name = "Cured Thick Hide", count = 4 }, { name = "Black Pearl", count = 2 } } },
    ["Felscale Gloves"] = { spellId = 0, reagents = { { name = "Knothide Leather", count = 5 }, { name = "Rune Thread", count = 2 }, { name = "Fel Scales", count = 1 } } },
    ["Fine Leather Belt"] = { spellId = 0, reagents = { { name = "Light Leather", count = 6 }, { name = "Coarse Thread", count = 2 } } },
    ["Fine Leather Boots"] = { spellId = 0, reagents = { { name = "Light Leather", count = 7 }, { name = "Coarse Thread", count = 2 } } },
    ["Fine Leather Cloak"] = { spellId = 0, reagents = { { name = "Light Leather", count = 10 }, { name = "Fine Thread", count = 2 } } },
    ["Fine Leather Gloves"] = { spellId = 0, reagents = { { name = "Light Leather", count = 4 }, { name = "Coarse Thread", count = 2 }, { name = "Cured Light Hide", count = 1 } } },
    ["Fine Leather Pants"] = { spellId = 0, reagents = { { name = "Medium Leather", count = 8 }, { name = "Bolt of Woolen Cloth", count = 1 }, { name = "Fine Thread", count = 1 } } },
    ["Fine Leather Tunic"] = { spellId = 0, reagents = { { name = "Light Leather", count = 6 }, { name = "Coarse Thread", count = 4 }, { name = "Cured Light Hide", count = 3 } } },
    ["Fletcher's Gloves"] = { spellId = 0, reagents = { { name = "Medium Leather", count = 8 }, { name = "Cured Medium Hide", count = 4 }, { name = "Fine Thread", count = 2 } } },
    ["Frost Leather Cloak"] = { spellId = 0, reagents = { { name = "Heavy Leather", count = 6 }, { name = "Elemental Earth", count = 2 }, { name = "Elemental Water", count = 2 }, { name = "Fine Thread", count = 2 } } },
    ["Frostsaber Boots"] = { spellId = 0, reagents = { { name = "Rugged Leather", count = 4 }, { name = "Essence of Water", count = 1 }, { name = "Rune Thread", count = 1 } } },
    ["Frostsaber Gloves"] = { spellId = 0, reagents = { { name = "Rugged Leather", count = 6 }, { name = "Essence of Water", count = 1 }, { name = "Rune Thread", count = 1 } } },
    ["Frostsaber Leggings"] = { spellId = 0, reagents = { { name = "Rugged Leather", count = 6 }, { name = "Essence of Water", count = 1 }, { name = "Rune Thread", count = 1 } } },
    ["Frostsaber Tunic"] = { spellId = 0, reagents = { { name = "Rugged Leather", count = 12 }, { name = "Essence of Water", count = 1 }, { name = "Rune Thread", count = 2 }, { name = "Cured Rugged Hide", count = 1 } } },
    ["Gauntlets of the Sea"] = { spellId = 0, reagents = { { name = "Thick Leather", count = 20 }, { name = "Globe of Water", count = 8 }, { name = "Heavy Silken Thread", count = 4 }, { name = "Core of Earth", count = 2 }, { name = "Cured Thick Hide", count = 1 } } },
    ["Gem-Studded Leather Belt"] = { spellId = 0, reagents = { { name = "Cured Heavy Hide", count = 4 }, { name = "Iridescent Pearl", count = 2 }, { name = "Jade", count = 2 }, { name = "Citrine", count = 1 }, { name = "Fine Thread", count = 1 } } },
    ["Girdle of Insight"] = { spellId = 0, reagents = { { name = "Rugged Leather", count = 12 }, { name = "Powerful Mojo", count = 12 }, { name = "Rune Thread", count = 4 }, { name = "Cured Rugged Hide", count = 2 } } },
    ["Gloves of the Greatfather"] = { spellId = 0, reagents = { { name = "Heavy Leather", count = 8 }, { name = "Elemental Earth", count = 4 }, { name = "Silken Thread", count = 1 } } },
    ["Golden Mantle of the Dawn"] = { spellId = 0, reagents = { { name = "Enchanted Leather", count = 8 }, { name = "Living Essence", count = 4 }, { name = "Guardian Stone", count = 4 }, { name = "Rune Thread", count = 2 }, { name = "Cured Rugged Hide", count = 2 } } },
    ["Gordok Ogre Suit"] = { spellId = 0, reagents = { { name = "Rugged Leather", count = 4 }, { name = "Bolt of Runecloth", count = 2 }, { name = "Rune Thread", count = 1 }, { name = "Ogre Tannin", count = 1 } } },
    ["Green Dragonscale Breastplate"] = { spellId = 0, reagents = { { name = "Green Dragonscale", count = 25 }, { name = "Rugged Leather", count = 20 }, { name = "Rune Thread", count = 2 } } },
    ["Green Dragonscale Gauntlets"] = { spellId = 0, reagents = { { name = "Green Dragonscale", count = 30 }, { name = "Rugged Leather", count = 20 }, { name = "Rune Thread", count = 2 }, { name = "Cured Rugged Hide", count = 1 } } },
    ["Green Dragonscale Leggings"] = { spellId = 0, reagents = { { name = "Green Dragonscale", count = 25 }, { name = "Rugged Leather", count = 20 }, { name = "Rune Thread", count = 1 } } },
    ["Green Leather Armor"] = { spellId = 0, reagents = { { name = "Heavy Leather", count = 9 }, { name = "Fine Thread", count = 4 }, { name = "Green Dye", count = 2 } } },
    ["Green Leather Belt"] = { spellId = 0, reagents = { { name = "Heavy Leather", count = 5 }, { name = "Cured Heavy Hide", count = 1 }, { name = "Fine Thread", count = 1 }, { name = "Green Dye", count = 1 }, { name = "Iron Buckle", count = 1 } } },
    ["Green Leather Bracers"] = { spellId = 0, reagents = { { name = "Heavy Leather", count = 6 }, { name = "Cured Heavy Hide", count = 2 }, { name = "Green Dye", count = 1 }, { name = "Fine Thread", count = 1 } } },
    ["Green Whelp Armor"] = { spellId = 0, reagents = { { name = "Heavy Leather", count = 10 }, { name = "Green Whelp Scale", count = 4 }, { name = "Fine Thread", count = 2 } } },
    ["Green Whelp Bracers"] = { spellId = 0, reagents = { { name = "Heavy Leather", count = 8 }, { name = "Green Whelp Scale", count = 6 }, { name = "Silken Thread", count = 2 } } },
    ["Guardian Armor"] = { spellId = 0, reagents = { { name = "Heavy Leather", count = 12 }, { name = "Cured Heavy Hide", count = 2 }, { name = "Fine Thread", count = 2 }, { name = "Shadow Oil", count = 1 } } },
    ["Guardian Belt"] = { spellId = 0, reagents = { { name = "Heavy Leather", count = 4 }, { name = "Cured Heavy Hide", count = 2 }, { name = "Fine Thread", count = 1 }, { name = "Iron Buckle", count = 1 } } },
    ["Guardian Cloak"] = { spellId = 0, reagents = { { name = "Heavy Leather", count = 14 }, { name = "Bolt of Silk Cloth", count = 2 }, { name = "Silken Thread", count = 2 } } },
    ["Guardian Gloves"] = { spellId = 0, reagents = { { name = "Heavy Leather", count = 4 }, { name = "Cured Heavy Hide", count = 1 }, { name = "Silken Thread", count = 1 } } },
    ["Guardian Leather Bracers"] = { spellId = 0, reagents = { { name = "Heavy Leather", count = 6 }, { name = "Cured Heavy Hide", count = 2 }, { name = "Silken Thread", count = 1 } } },
    ["Guardian Pants"] = { spellId = 0, reagents = { { name = "Heavy Leather", count = 12 }, { name = "Bolt of Silk Cloth", count = 2 }, { name = "Fine Thread", count = 2 } } },
    ["Handstitched Leather Belt"] = { spellId = 0, reagents = { { name = "Light Leather", count = 6 }, { name = "Coarse Thread", count = 1 } } },
    ["Handstitched Leather Boots"] = { spellId = 0, reagents = { { name = "Light Leather", count = 2 }, { name = "Coarse Thread", count = 1 } } },
    ["Handstitched Leather Bracers"] = { spellId = 0, reagents = { { name = "Coarse Thread", count = 3 }, { name = "Light Leather", count = 2 } } },
    ["Handstitched Leather Cloak"] = { spellId = 0, reagents = { { name = "Light Leather", count = 2 }, { name = "Coarse Thread", count = 1 } } },
    ["Handstitched Leather Pants"] = { spellId = 0, reagents = { { name = "Light Leather", count = 4 }, { name = "Coarse Thread", count = 1 } } },
    ["Handstitched Leather Vest"] = { spellId = 0, reagents = { { name = "Light Leather", count = 3 }, { name = "Coarse Thread", count = 1 } } },
    ["Heavy Armor Kit"] = { spellId = 0, reagents = { { name = "Heavy Leather", count = 5 }, { name = "Fine Thread", count = 1 } } },
    ["Heavy Earthen Gloves"] = { spellId = 0, reagents = { { name = "Medium Leather", count = 12 }, { name = "Elemental Earth", count = 2 }, { name = "Bolt of Woolen Cloth", count = 2 }, { name = "Fine Thread", count = 2 } } },
    ["Heavy Leather Ball"] = { spellId = 0, reagents = { { name = "Heavy Leather", count = 2 }, { name = "Fine Thread", count = 1 } } },
    ["Heavy Leather"] = { spellId = 0, reagents = { { name = "Medium Leather", count = 5 } } },
    ["Heavy Scorpid Belt"] = { spellId = 0, reagents = { { name = "Heavy Scorpid Scale", count = 8 }, { name = "Rugged Leather", count = 6 }, { name = "Rune Thread", count = 1 } } },
    ["Heavy Scorpid Bracers"] = { spellId = 0, reagents = { { name = "Rugged Leather", count = 4 }, { name = "Heavy Scorpid Scale", count = 4 }, { name = "Rune Thread", count = 1 } } },
    ["Heavy Scorpid Gauntlets"] = { spellId = 0, reagents = { { name = "Heavy Scorpid Scale", count = 8 }, { name = "Rugged Leather", count = 6 }, { name = "Rune Thread", count = 1 } } },
    ["Heavy Scorpid Helm"] = { spellId = 0, reagents = { { name = "Heavy Scorpid Scale", count = 12 }, { name = "Rugged Leather", count = 8 }, { name = "Rune Thread", count = 1 }, { name = "Cured Rugged Hide", count = 1 } } },
    ["Heavy Scorpid Leggings"] = { spellId = 0, reagents = { { name = "Heavy Scorpid Scale", count = 12 }, { name = "Rugged Leather", count = 8 }, { name = "Rune Thread", count = 1 } } },
    ["Heavy Scorpid Shoulders"] = { spellId = 0, reagents = { { name = "Rugged Leather", count = 14 }, { name = "Heavy Scorpid Scale", count = 14 }, { name = "Rune Thread", count = 2 }, { name = "Cured Rugged Hide", count = 1 } } },
    ["Heavy Scorpid Vest"] = { spellId = 0, reagents = { { name = "Rugged Leather", count = 6 }, { name = "Heavy Scorpid Scale", count = 6 }, { name = "Rune Thread", count = 1 } } },
    ["Helm of Fire"] = { spellId = 0, reagents = { { name = "Thick Leather", count = 40 }, { name = "Heart of Fire", count = 8 }, { name = "Heavy Silken Thread", count = 4 }, { name = "Core of Earth", count = 4 }, { name = "Cured Thick Hide", count = 2 } } },
    ["Herbalist's Gloves"] = { spellId = 0, reagents = { { name = "Medium Leather", count = 8 }, { name = "Kingsblood", count = 4 }, { name = "Fine Thread", count = 2 } } },
    ["Hide of the Wild"] = { spellId = 0, reagents = { { name = "Rugged Leather", count = 30 }, { name = "Living Essence", count = 12 }, { name = "Essence of Water", count = 10 }, { name = "Rune Thread", count = 8 }, { name = "Larval Acid", count = 8 }, { name = "Cured Rugged Hide", count = 3 } } },
    ["Hillman's Belt"] = { spellId = 0, reagents = { { name = "Medium Leather", count = 8 }, { name = "Fine Thread", count = 2 }, { name = "Elixir of Wisdom", count = 1 } } },
    ["Hillman's Cloak"] = { spellId = 0, reagents = { { name = "Heavy Leather", count = 5 }, { name = "Fine Thread", count = 2 } } },
    ["Hillman's Leather Gloves"] = { spellId = 0, reagents = { { name = "Medium Leather", count = 14 }, { name = "Fine Thread", count = 4 } } },
    ["Hillman's Leather Vest"] = { spellId = 0, reagents = { { name = "Cured Light Hide", count = 2 }, { name = "Coarse Thread", count = 2 }, { name = "Fine Leather Tunic", count = 1 } } },
    ["Hillman's Shoulders"] = { spellId = 0, reagents = { { name = "Medium Leather", count = 4 }, { name = "Fine Thread", count = 1 }, { name = "Cured Medium Hide", count = 1 } } },
    ["Icy Scale Bracers"] = { spellId = 0, reagents = { { name = "Heavy Scorpid Scale", count = 16 }, { name = "Ironweb Spider Silk", count = 4 }, { name = "Frozen Rune", count = 4 }, { name = "Essence of Water", count = 2 }, { name = "Cured Rugged Hide", count = 2 } } },
    ["Icy Scale Breastplate"] = { spellId = 0, reagents = { { name = "Heavy Scorpid Scale", count = 24 }, { name = "Frozen Rune", count = 7 }, { name = "Cured Rugged Hide", count = 4 }, { name = "Ironweb Spider Silk", count = 4 }, { name = "Essence of Water", count = 2 } } },
    ["Icy Scale Gauntlets"] = { spellId = 0, reagents = { { name = "Heavy Scorpid Scale", count = 16 }, { name = "Frozen Rune", count = 5 }, { name = "Ironweb Spider Silk", count = 4 }, { name = "Cured Rugged Hide", count = 3 }, { name = "Essence of Water", count = 2 } } },
    ["Ironfeather Breastplate"] = { spellId = 0, reagents = { { name = "Ironfeather", count = 120 }, { name = "Rugged Leather", count = 40 }, { name = "Rune Thread", count = 1 }, { name = "Jade", count = 1 }, { name = "Cured Rugged Hide", count = 1 } } },
    ["Ironfeather Shoulders"] = { spellId = 0, reagents = { { name = "Ironfeather", count = 80 }, { name = "Rugged Leather", count = 24 }, { name = "Jade", count = 2 }, { name = "Rune Thread", count = 1 } } },
    ["Knothide Armor Kit"] = { spellId = 0, reagents = { { name = "Knothide Leather", count = 4 } } },
    ["Knothide Leather"] = { spellId = 0, reagents = { { name = "Knothide Leather Scraps", count = 5 } } },
    ["Kodo Hide Bag"] = { spellId = 0, reagents = { { name = "Light Leather", count = 4 }, { name = "Thin Kodo Leather", count = 3 }, { name = "Coarse Thread", count = 1 } } },
    ["Lava Belt"] = { spellId = 0, reagents = { { name = "Lava Core", count = 5 }, { name = "Cured Rugged Hide", count = 4 }, { name = "Ironweb Spider Silk", count = 4 } } },
    ["Leatherworker's Satchel"] = { spellId = 0, reagents = { { name = "Knothide Leather", count = 20 }, { name = "Fel Scales", count = 4 }, { name = "Fel Hide", count = 4 }, { name = "Rune Thread", count = 3 } } },
    ["Light Armor Kit"] = { spellId = 0, reagents = { { name = "Light Leather", count = 1 } } },
    ["Light Leather Bracers"] = { spellId = 0, reagents = { { name = "Light Leather", count = 6 }, { name = "Coarse Thread", count = 4 } } },
    ["Light Leather Pants"] = { spellId = 0, reagents = { { name = "Light Leather", count = 10 }, { name = "Cured Light Hide", count = 1 }, { name = "Fine Thread", count = 1 } } },
    ["Light Leather"] = { spellId = 0, reagents = { { name = "Ruined Leather Scraps", count = 3 } } },
    ["Living Breastplate"] = { spellId = 0, reagents = { { name = "Rugged Leather", count = 16 }, { name = "Living Essence", count = 8 }, { name = "Rune Thread", count = 2 }, { name = "Mooncloth", count = 2 }, { name = "Cured Rugged Hide", count = 1 } } },
    ["Living Leggings"] = { spellId = 0, reagents = { { name = "Rugged Leather", count = 16 }, { name = "Living Essence", count = 6 }, { name = "Rune Thread", count = 1 }, { name = "Cured Rugged Hide", count = 1 } } },
    ["Living Shoulders"] = { spellId = 0, reagents = { { name = "Rugged Leather", count = 12 }, { name = "Living Essence", count = 4 }, { name = "Rune Thread", count = 1 } } },
    ["Medium Armor Kit"] = { spellId = 0, reagents = { { name = "Medium Leather", count = 4 }, { name = "Coarse Thread", count = 1 } } },
    ["Medium Leather"] = { spellId = 0, reagents = { { name = "Light Leather", count = 4 } } },
    ["Might of the Timbermaw"] = { spellId = 0, reagents = { { name = "Rugged Leather", count = 30 }, { name = "Living Essence", count = 4 }, { name = "Rune Thread", count = 2 }, { name = "Powerful Mojo", count = 2 }, { name = "Cured Rugged Hide", count = 2 } } },
    ["Molten Belt"] = { spellId = 0, reagents = { { name = "Lava Core", count = 7 }, { name = "Essence of Earth", count = 6 }, { name = "Ironweb Spider Silk", count = 4 }, { name = "Cured Rugged Hide", count = 4 }, { name = "Fiery Core", count = 2 } } },
    ["Molten Helm"] = { spellId = 0, reagents = { { name = "Core Leather", count = 15 }, { name = "Lava Core", count = 6 }, { name = "Fiery Core", count = 3 }, { name = "Rune Thread", count = 2 } } },
    ["Mongoose Boots"] = { spellId = 0, reagents = { { name = "Rugged Leather", count = 12 }, { name = "Essence of Air", count = 6 }, { name = "Rune Thread", count = 4 }, { name = "Black Diamond", count = 4 }, { name = "Cured Rugged Hide", count = 2 } } },
    ["Moonglow Vest"] = { spellId = 0, reagents = { { name = "Light Leather", count = 6 }, { name = "Coarse Thread", count = 4 }, { name = "Small Lustrous Pearl", count = 1 }, { name = "Cured Light Hide", count = 1 } } },
    ["Murloc Scale Belt"] = { spellId = 0, reagents = { { name = "Slimy Murloc Scale", count = 8 }, { name = "Light Leather", count = 6 }, { name = "Fine Thread", count = 1 } } },
    ["Murloc Scale Bracers"] = { spellId = 0, reagents = { { name = "Thick Murloc Scale", count = 16 }, { name = "Heavy Leather", count = 14 }, { name = "Cured Heavy Hide", count = 1 }, { name = "Silken Thread", count = 1 } } },
    ["Murloc Scale Breastplate"] = { spellId = 0, reagents = { { name = "Slimy Murloc Scale", count = 12 }, { name = "Light Leather", count = 8 }, { name = "Fine Thread", count = 1 }, { name = "Cured Light Hide", count = 1 } } },
    ["Nightscape Boots"] = { spellId = 0, reagents = { { name = "Thick Leather", count = 16 }, { name = "Heavy Silken Thread", count = 2 } } },
    ["Nightscape Headband"] = { spellId = 0, reagents = { { name = "Thick Leather", count = 5 }, { name = "Silken Thread", count = 2 } } },
    ["Nightscape Pants"] = { spellId = 0, reagents = { { name = "Thick Leather", count = 14 }, { name = "Silken Thread", count = 4 } } },
    ["Nightscape Shoulders"] = { spellId = 0, reagents = { { name = "Thick Leather", count = 8 }, { name = "Mageweave Cloth", count = 6 }, { name = "Silken Thread", count = 3 } } },
    ["Nightscape Tunic"] = { spellId = 0, reagents = { { name = "Thick Leather", count = 7 }, { name = "Silken Thread", count = 2 } } },
    ["Nimble Leather Gloves"] = { spellId = 0, reagents = { { name = "Medium Leather", count = 6 }, { name = "Fine Thread", count = 1 }, { name = "Elixir of Minor Agility", count = 1 } } },
    ["Onyxia Scale Cloak"] = { spellId = 0, reagents = { { name = "Scale of Onyxia", count = 1 }, { name = "Rune Thread", count = 1 }, { name = "Cindercloth Cloak", count = 1 } } },
    ["Pilferer's Gloves"] = { spellId = 0, reagents = { { name = "Medium Leather", count = 10 }, { name = "Lucky Charm", count = 2 }, { name = "Fine Thread", count = 2 } } },
    ["Polar Bracers"] = { spellId = 0, reagents = { { name = "Enchanted Leather", count = 12 }, { name = "Ironweb Spider Silk", count = 4 }, { name = "Frozen Rune", count = 4 }, { name = "Essence of Water", count = 2 }, { name = "Cured Rugged Hide", count = 2 } } },
    ["Polar Gloves"] = { spellId = 0, reagents = { { name = "Enchanted Leather", count = 12 }, { name = "Frozen Rune", count = 5 }, { name = "Ironweb Spider Silk", count = 4 }, { name = "Cured Rugged Hide", count = 3 }, { name = "Essence of Water", count = 2 } } },
    ["Polar Tunic"] = { spellId = 0, reagents = { { name = "Enchanted Leather", count = 16 }, { name = "Frozen Rune", count = 7 }, { name = "Ironweb Spider Silk", count = 4 }, { name = "Cured Rugged Hide", count = 4 }, { name = "Essence of Water", count = 2 } } },
    ["Primal Batskin Bracers"] = { spellId = 0, reagents = { { name = "Primal Bat Leather", count = 8 }, { name = "Living Essence", count = 4 }, { name = "Rune Thread", count = 3 }, { name = "Cured Rugged Hide", count = 3 } } },
    ["Primal Batskin Gloves"] = { spellId = 0, reagents = { { name = "Primal Bat Leather", count = 10 }, { name = "Living Essence", count = 4 }, { name = "Cured Rugged Hide", count = 4 }, { name = "Rune Thread", count = 3 } } },
    ["Primal Batskin Jerkin"] = { spellId = 0, reagents = { { name = "Primal Bat Leather", count = 14 }, { name = "Cured Rugged Hide", count = 5 }, { name = "Rune Thread", count = 4 }, { name = "Living Essence", count = 4 } } },
    ["Raptor Hide Belt"] = { spellId = 0, reagents = { { name = "Raptor Hide", count = 4 }, { name = "Heavy Leather", count = 4 }, { name = "Fine Thread", count = 2 } } },
    ["Raptor Hide Harness"] = { spellId = 0, reagents = { { name = "Raptor Hide", count = 6 }, { name = "Heavy Leather", count = 4 }, { name = "Fine Thread", count = 2 } } },
    ["Red Dragonscale Breastplate"] = { spellId = 0, reagents = { { name = "Rugged Leather", count = 40 }, { name = "Red Dragonscale", count = 30 }, { name = "Rune Thread", count = 1 } } },
    ["Red Whelp Gloves"] = { spellId = 0, reagents = { { name = "Red Dye", count = 6 }, { name = "Medium Leather", count = 10 }, { name = "Fine Thread", count = 1 } } },
    ["Rugged Armor Kit"] = { spellId = 0, reagents = { { name = "Rugged Leather", count = 5 } } },
    ["Rugged Leather Pants"] = { spellId = 0, reagents = { { name = "Light Leather", count = 5 }, { name = "Coarse Thread", count = 5 } } },
    ["Rugged Leather"] = { spellId = 0, reagents = { { name = "Thick Leather", count = 6 } } },
    ["Runic Leather Armor"] = { spellId = 0, reagents = { { name = "Rugged Leather", count = 22 }, { name = "Runecloth", count = 16 }, { name = "Enchanted Leather", count = 4 }, { name = "Rune Thread", count = 2 }, { name = "Cured Rugged Hide", count = 1 } } },
    ["Runic Leather Belt"] = { spellId = 0, reagents = { { name = "Rugged Leather", count = 12 }, { name = "Runecloth", count = 10 }, { name = "Rune Thread", count = 1 } } },
    ["Runic Leather Bracers"] = { spellId = 0, reagents = { { name = "Runecloth", count = 6 }, { name = "Rugged Leather", count = 6 }, { name = "Rune Thread", count = 1 }, { name = "Black Pearl", count = 1 } } },
    ["Runic Leather Gauntlets"] = { spellId = 0, reagents = { { name = "Rugged Leather", count = 10 }, { name = "Runecloth", count = 6 }, { name = "Rune Thread", count = 1 } } },
    ["Runic Leather Headband"] = { spellId = 0, reagents = { { name = "Rugged Leather", count = 14 }, { name = "Runecloth", count = 10 }, { name = "Rune Thread", count = 1 } } },
    ["Runic Leather Pants"] = { spellId = 0, reagents = { { name = "Rugged Leather", count = 18 }, { name = "Runecloth", count = 12 }, { name = "Enchanted Leather", count = 2 }, { name = "Rune Thread", count = 1 } } },
    ["Runic Leather Shoulders"] = { spellId = 0, reagents = { { name = "Runecloth", count = 18 }, { name = "Rugged Leather", count = 16 }, { name = "Enchanted Leather", count = 4 }, { name = "Rune Thread", count = 2 }, { name = "Cured Rugged Hide", count = 1 } } },
    ["Sandstalker Bracers"] = { spellId = 0, reagents = { { name = "Silithid Chitin", count = 20 }, { name = "Larval Acid", count = 2 }, { name = "Heavy Silithid Carapace", count = 1 } } },
    ["Sandstalker Breastplate"] = { spellId = 0, reagents = { { name = "Silithid Chitin", count = 40 }, { name = "Heavy Silithid Carapace", count = 3 }, { name = "Larval Acid", count = 2 }, { name = "Cured Rugged Hide", count = 2 } } },
    ["Sandstalker Gauntlets"] = { spellId = 0, reagents = { { name = "Silithid Chitin", count = 30 }, { name = "Larval Acid", count = 2 }, { name = "Heavy Silithid Carapace", count = 2 }, { name = "Cured Rugged Hide", count = 1 } } },
    ["Scaled Draenic Pants"] = { spellId = 0, reagents = { { name = "Knothide Leather", count = 6 }, { name = "Fel Scales", count = 3 }, { name = "Rune Thread", count = 2 } } },
    ["Shadowskin Gloves"] = { spellId = 0, reagents = { { name = "Shadow Silk", count = 8 }, { name = "Thick Leather", count = 6 }, { name = "Cured Heavy Hide", count = 4 }, { name = "Heavy Silken Thread", count = 1 } } },
    ["Shifting Cloak"] = { spellId = 0, reagents = { { name = "Rugged Leather", count = 30 }, { name = "Essence of Air", count = 12 }, { name = "Rune Thread", count = 8 }, { name = "Guardian Stone", count = 8 }, { name = "Skin of Shadow", count = 4 }, { name = "Cured Rugged Hide", count = 4 } } },
    ["Spitfire Bracers"] = { spellId = 0, reagents = { { name = "Silithid Chitin", count = 20 }, { name = "Essence of Fire", count = 2 }, { name = "Light Silithid Carapace", count = 1 } } },
    ["Spitfire Breastplate"] = { spellId = 0, reagents = { { name = "Silithid Chitin", count = 40 }, { name = "Light Silithid Carapace", count = 3 }, { name = "Essence of Fire", count = 2 }, { name = "Cured Rugged Hide", count = 2 } } },
    ["Spitfire Gauntlets"] = { spellId = 0, reagents = { { name = "Silithid Chitin", count = 30 }, { name = "Light Silithid Carapace", count = 2 }, { name = "Essence of Fire", count = 2 }, { name = "Cured Rugged Hide", count = 1 } } },
    ["Stormshroud Armor"] = { spellId = 0, reagents = { { name = "Rugged Leather", count = 16 }, { name = "Essence of Water", count = 3 }, { name = "Essence of Air", count = 3 }, { name = "Rune Thread", count = 1 }, { name = "Cured Rugged Hide", count = 1 } } },
    ["Stormshroud Gloves"] = { spellId = 0, reagents = { { name = "Enchanted Leather", count = 6 }, { name = "Essence of Water", count = 4 }, { name = "Essence of Air", count = 4 }, { name = "Ironweb Spider Silk", count = 2 }, { name = "Cured Rugged Hide", count = 2 } } },
    ["Stormshroud Pants"] = { spellId = 0, reagents = { { name = "Rugged Leather", count = 16 }, { name = "Essence of Water", count = 2 }, { name = "Essence of Air", count = 2 }, { name = "Rune Thread", count = 1 } } },
    ["Stormshroud Shoulders"] = { spellId = 0, reagents = { { name = "Rugged Leather", count = 12 }, { name = "Essence of Water", count = 3 }, { name = "Essence of Air", count = 3 }, { name = "Enchanted Leather", count = 2 }, { name = "Rune Thread", count = 1 } } },
    ["Swift Boots"] = { spellId = 0, reagents = { { name = "Heavy Leather", count = 10 }, { name = "Swiftness Potion", count = 2 }, { name = "Thick Spider's Silk", count = 2 }, { name = "Silken Thread", count = 1 } } },
    ["Swift Flight Bracers"] = { spellId = 0, reagents = { { name = "Ironfeather", count = 60 }, { name = "Rugged Leather", count = 12 }, { name = "Larval Acid", count = 8 }, { name = "Rune Thread", count = 4 }, { name = "Cured Rugged Hide", count = 4 } } },
    ["Thick Armor Kit"] = { spellId = 0, reagents = { { name = "Thick Leather", count = 5 }, { name = "Silken Thread", count = 1 } } },
    ["Thick Draenic Gloves"] = { spellId = 0, reagents = { { name = "Knothide Leather", count = 6 }, { name = "Rune Thread", count = 2 } } },
    ["Thick Leather"] = { spellId = 0, reagents = { { name = "Heavy Leather", count = 6 } } },
    ["Thick Murloc Armor"] = { spellId = 0, reagents = { { name = "Thick Murloc Scale", count = 12 }, { name = "Heavy Leather", count = 10 }, { name = "Fine Thread", count = 3 }, { name = "Cured Heavy Hide", count = 1 } } },
    ["Timbermaw Brawlers"] = { spellId = 0, reagents = { { name = "Enchanted Leather", count = 8 }, { name = "Powerful Mojo", count = 6 }, { name = "Living Essence", count = 6 }, { name = "Ironweb Spider Silk", count = 2 }, { name = "Cured Rugged Hide", count = 2 } } },
    ["Tough Scorpid Boots"] = { spellId = 0, reagents = { { name = "Thick Leather", count = 12 }, { name = "Scorpid Scale", count = 12 }, { name = "Silken Thread", count = 6 } } },
    ["Tough Scorpid Bracers"] = { spellId = 0, reagents = { { name = "Thick Leather", count = 10 }, { name = "Scorpid Scale", count = 4 }, { name = "Silken Thread", count = 2 } } },
    ["Tough Scorpid Breastplate"] = { spellId = 0, reagents = { { name = "Thick Leather", count = 12 }, { name = "Scorpid Scale", count = 12 }, { name = "Silken Thread", count = 4 } } },
    ["Tough Scorpid Gloves"] = { spellId = 0, reagents = { { name = "Scorpid Scale", count = 8 }, { name = "Thick Leather", count = 6 }, { name = "Silken Thread", count = 2 } } },
    ["Tough Scorpid Helm"] = { spellId = 0, reagents = { { name = "Scorpid Scale", count = 20 }, { name = "Thick Leather", count = 10 }, { name = "Heavy Silken Thread", count = 2 } } },
    ["Tough Scorpid Leggings"] = { spellId = 0, reagents = { { name = "Thick Leather", count = 14 }, { name = "Scorpid Scale", count = 8 }, { name = "Heavy Silken Thread", count = 2 } } },
    ["Tough Scorpid Shoulders"] = { spellId = 0, reagents = { { name = "Scorpid Scale", count = 16 }, { name = "Thick Leather", count = 12 }, { name = "Heavy Silken Thread", count = 2 } } },
    ["Toughened Leather Armor"] = { spellId = 0, reagents = { { name = "Medium Leather", count = 10 }, { name = "Cured Light Hide", count = 6 }, { name = "Fine Thread", count = 2 } } },
    ["Toughened Leather Gloves"] = { spellId = 0, reagents = { { name = "Medium Leather", count = 4 }, { name = "Spider's Silk", count = 2 }, { name = "Fine Thread", count = 2 }, { name = "Elixir of Defense", count = 2 }, { name = "Cured Medium Hide", count = 2 } } },
    ["Turtle Scale Bracers"] = { spellId = 0, reagents = { { name = "Turtle Scale", count = 12 }, { name = "Thick Leather", count = 8 }, { name = "Heavy Silken Thread", count = 1 } } },
    ["Turtle Scale Breastplate"] = { spellId = 0, reagents = { { name = "Turtle Scale", count = 12 }, { name = "Thick Leather", count = 6 }, { name = "Heavy Silken Thread", count = 1 } } },
    ["Turtle Scale Gloves"] = { spellId = 0, reagents = { { name = "Turtle Scale", count = 8 }, { name = "Thick Leather", count = 6 }, { name = "Heavy Silken Thread", count = 1 } } },
    ["Turtle Scale Helm"] = { spellId = 0, reagents = { { name = "Turtle Scale", count = 24 }, { name = "Thick Leather", count = 14 }, { name = "Heavy Silken Thread", count = 1 } } },
    ["Turtle Scale Leggings"] = { spellId = 0, reagents = { { name = "Turtle Scale", count = 28 }, { name = "Thick Leather", count = 14 }, { name = "Heavy Silken Thread", count = 1 } } },
    ["Volcanic Breastplate"] = { spellId = 0, reagents = { { name = "Rugged Leather", count = 8 }, { name = "Rune Thread", count = 1 }, { name = "Essence of Fire", count = 1 }, { name = "Essence of Earth", count = 1 } } },
    ["Volcanic Leggings"] = { spellId = 0, reagents = { { name = "Rugged Leather", count = 6 }, { name = "Rune Thread", count = 1 }, { name = "Essence of Fire", count = 1 }, { name = "Core of Earth", count = 1 } } },
    ["Volcanic Shoulders"] = { spellId = 0, reagents = { { name = "Rugged Leather", count = 10 }, { name = "Rune Thread", count = 2 }, { name = "Essence of Fire", count = 1 }, { name = "Essence of Earth", count = 1 } } },
    ["Warbear Harness"] = { spellId = 0, reagents = { { name = "Rugged Leather", count = 28 }, { name = "Warbear Leather", count = 12 }, { name = "Rune Thread", count = 1 } } },
    ["Warbear Woolies"] = { spellId = 0, reagents = { { name = "Rugged Leather", count = 24 }, { name = "Warbear Leather", count = 14 }, { name = "Rune Thread", count = 1 } } },
    ["White Leather Jerkin"] = { spellId = 0, reagents = { { name = "Light Leather", count = 8 }, { name = "Coarse Thread", count = 2 }, { name = "Bleach", count = 1 } } },
    ["Wicked Leather Armor"] = { spellId = 0, reagents = { { name = "Rugged Leather", count = 20 }, { name = "Black Dye", count = 4 }, { name = "Cured Rugged Hide", count = 2 }, { name = "Felcloth", count = 2 }, { name = "Rune Thread", count = 2 } } },
    ["Wicked Leather Belt"] = { spellId = 0, reagents = { { name = "Rugged Leather", count = 14 }, { name = "Black Dye", count = 2 }, { name = "Rune Thread", count = 2 } } },
    ["Wicked Leather Bracers"] = { spellId = 0, reagents = { { name = "Rugged Leather", count = 8 }, { name = "Rune Thread", count = 1 }, { name = "Black Dye", count = 1 } } },
    ["Wicked Leather Gauntlets"] = { spellId = 0, reagents = { { name = "Rugged Leather", count = 8 }, { name = "Rune Thread", count = 1 }, { name = "Black Dye", count = 1 } } },
    ["Wicked Leather Headband"] = { spellId = 0, reagents = { { name = "Rugged Leather", count = 12 }, { name = "Rune Thread", count = 1 }, { name = "Black Dye", count = 1 } } },
    ["Wicked Leather Pants"] = { spellId = 0, reagents = { { name = "Rugged Leather", count = 16 }, { name = "Black Dye", count = 3 }, { name = "Rune Thread", count = 1 }, { name = "Cured Rugged Hide", count = 1 } } },
    ["Wild Draenish Boots"] = { spellId = 0, reagents = { { name = "Knothide Leather", count = 6 }, { name = "Rune Thread", count = 3 } } },
    ["Wild Leather Boots"] = { spellId = 0, reagents = { { name = "Thick Leather", count = 14 }, { name = "Wildvine", count = 4 }, { name = "Cured Thick Hide", count = 2 } } },
    ["Wild Leather Cloak"] = { spellId = 0, reagents = { { name = "Thick Leather", count = 16 }, { name = "Wildvine", count = 6 }, { name = "Cured Thick Hide", count = 2 } } },
    ["Wild Leather Helmet"] = { spellId = 0, reagents = { { name = "Thick Leather", count = 10 }, { name = "Wildvine", count = 2 }, { name = "Cured Thick Hide", count = 1 } } },
    ["Wild Leather Leggings"] = { spellId = 0, reagents = { { name = "Thick Leather", count = 16 }, { name = "Wildvine", count = 6 }, { name = "Cured Thick Hide", count = 2 } } },
    ["Wild Leather Shoulders"] = { spellId = 0, reagents = { { name = "Thick Leather", count = 10 }, { name = "Wildvine", count = 1 }, { name = "Cured Thick Hide", count = 1 } } },
    ["Wild Leather Vest"] = { spellId = 0, reagents = { { name = "Thick Leather", count = 12 }, { name = "Wildvine", count = 2 }, { name = "Cured Thick Hide", count = 1 } } },
    ["Wildfeather Leggings"] = { spellId = 0, reagents = { { name = "Jet Black Feather", count = 40 }, { name = "Rugged Leather", count = 10 }, { name = "Wildvine", count = 4 }, { name = "Cured Thick Hide", count = 2 }, { name = "Rune Thread", count = 1 } } },
    ["Winter Boots"] = { spellId = 0, reagents = { { name = "Rugged Leather", count = 4 }, { name = "Rune Thread", count = 1 }, { name = "Copper Bar", count = 1 }, { name = "Bolt of Woolen Cloth", count = 1 } } },
    ["Wolfshead Helm"] = { spellId = 0, reagents = { { name = "Thick Leather", count = 18 }, { name = "Wildvine", count = 12 }, { name = "Heavy Silken Thread", count = 4 }, { name = "Cured Thick Hide", count = 2 } } },
}
