GuildShoppingList_TailoringPatterns  = {
    ["Bolt of Linen Cloth"] = { spellId = 0, reagents = { { name = "Linen Cloth", count = 2 } } },
    ["Brown Linen Shirt"] = { spellId = 0, reagents = { { name = "Bolt of Linen Cloth", count = 1 }, { name = "Coarse Thread", count = 1 } } },
    ["Linen Cloak"] = { spellId = 0, reagents = { { name = "Bolt of Linen Cloth", count = 1 }, { name = "Coarse Thread", count = 1 } } },
    ["Simple Linen Pants"] = { spellId = 0, reagents = { { name = "Bolt of Linen Cloth", count = 1 }, { name = "Coarse Thread", count = 1 } } },
    ["White Linen Shirt"] = { spellId = 0, reagents = { { name = "Bolt of Linen Cloth", count = 1 }, { name = "Coarse Thread", count = 1 }, { name = "Bleach", count = 1 } } },
    ["Brown Linen Vest"] = { spellId = 0, reagents = { { name = "Bolt of Linen Cloth", count = 1 }, { name = "Coarse Thread", count = 1 } } },
    ["Linen Belt"] = { spellId = 0, reagents = { { name = "Bolt of Linen Cloth", count = 1 }, { name = "Coarse Thread", count = 1 } } },
    ["Simple Linen Boots"] = { spellId = 0, reagents = { { name = "Bolt of Linen Cloth", count = 2 }, { name = "Light Leather", count = 1 }, { name = "Coarse Thread", count = 1 } } },
    ["Brown Linen Pants"] = { spellId = 0, reagents = { { name = "Bolt of Linen Cloth", count = 2 }, { name = "Coarse Thread", count = 1 } } },
    ["Brown Linen Robe"] = { spellId = 0, reagents = { { name = "Bolt of Linen Cloth", count = 3 }, { name = "Coarse Thread", count = 1 } } },
    ["White Linen Robe"] = { spellId = 0, reagents = { { name = "Bolt of Linen Cloth", count = 3 }, { name = "Coarse Thread", count = 1 }, { name = "Bleach", count = 1 } } },
    ["Heavy Linen Gloves"] = { spellId = 0, reagents = { { name = "Bolt of Linen Cloth", count = 2 }, { name = "Coarse Thread", count = 1 } } },
    ["Red Linen Robe"] = { spellId = 0, reagents = { { name = "Bolt of Linen Cloth", count = 3 }, { name = "Coarse Thread", count = 2 }, { name = "Red Dye", count = 2 } } },
    ["Red Linen Shirt"] = { spellId = 0, reagents = { { name = "Bolt of Linen Cloth", count = 2 }, { name = "Coarse Thread", count = 1 }, { name = "Red Dye", count = 1 } } },
    ["Blue Linen Shirt"] = { spellId = 0, reagents = { { name = "Bolt of Linen Cloth", count = 2 }, { name = "Coarse Thread", count = 1 }, { name = "Blue Dye", count = 1 } } },
    ["Simple Dress"] = { spellId = 0, reagents = { { name = "Bolt of Linen Cloth", count = 2 }, { name = "Coarse Thread", count = 1 }, { name = "Blue Dye", count = 1 }, { name = "Bleach", count = 1 } } },
    ["Linen Bag"] = { spellId = 0, reagents = { { name = "Bolt of Linen Cloth", count = 3 }, { name = "Coarse Thread", count = 3 } } },
    ["Red Linen Vest"] = { spellId = 0, reagents = { { name = "Bolt of Linen Cloth", count = 3 }, { name = "Coarse Thread", count = 1 }, { name = "Red Dye", count = 1 } } },
    ["Blue Linen Vest"] = { spellId = 0, reagents = { { name = "Bolt of Linen Cloth", count = 3 }, { name = "Coarse Thread", count = 1 }, { name = "Blue Dye", count = 1 } } },
    ["Reinforced Linen Cape"] = { spellId = 0, reagents = { { name = "Bolt of Linen Cloth", count = 2 }, { name = "Coarse Thread", count = 3 } } },
    ["Green Linen Bracers"] = { spellId = 0, reagents = { { name = "Bolt of Linen Cloth", count = 3 }, { name = "Coarse Thread", count = 2 }, { name = "Green Dye", count = 1 } } },
    ["Linen Boots"] = { spellId = 0, reagents = { { name = "Bolt of Linen Cloth", count = 3 }, { name = "Coarse Thread", count = 1 }, { name = "Light Leather", count = 1 } } },
    ["Red Linen Bag"] = { spellId = 0, reagents = { { name = "Bolt of Linen Cloth", count = 4 }, { name = "Fine Thread", count = 1 }, { name = "Red Dye", count = 1 } } },
    ["Blue Linen Robe"] = { spellId = 0, reagents = { { name = "Bolt of Linen Cloth", count = 4 }, { name = "Coarse Thread", count = 2 }, { name = "Blue Dye", count = 2 } } },
    ["Simple Kilt"] = { spellId = 0, reagents = { { name = "Bolt of Linen Cloth", count = 4 }, { name = "Fine Thread", count = 1 } } },
    ["Bolt of Woolen Cloth"] = { spellId = 0, reagents = { { name = "Wool Cloth", count = 2 } } },
    ["Woolen Cape"] = { spellId = 0, reagents = { { name = "Bolt of Woolen Cloth", count = 1 }, { name = "Fine Thread", count = 1 } } },
    ["Woolen Bag"] = { spellId = 0, reagents = { { name = "Bolt of Woolen Cloth", count = 3 }, { name = "Fine Thread", count = 1 } } },
    ["Soft-Soled Linen Boots"] = { spellId = 0, reagents = { { name = "Bolt of Linen Cloth", count = 5 }, { name = "Light Leather", count = 2 }, { name = "Fine Thread", count = 1 } } },
    ["Green Woolen Vest"] = { spellId = 0, reagents = { { name = "Bolt of Woolen Cloth", count = 2 }, { name = "Fine Thread", count = 2 }, { name = "Green Dye", count = 1 } } },
    ["Heavy Woolen Gloves"] = { spellId = 0, reagents = { { name = "Bolt of Woolen Cloth", count = 3 }, { name = "Fine Thread", count = 1 } } },
    ["Pearl-clasped Cloak"] = { spellId = 0, reagents = { { name = "Bolt of Woolen Cloth", count = 3 }, { name = "Fine Thread", count = 2 }, { name = "Small Lustrous Pearl", count = 1 } } },
    ["Woolen Boots"] = { spellId = 0, reagents = { { name = "Bolt of Woolen Cloth", count = 4 }, { name = "Fine Thread", count = 2 }, { name = "Light Leather", count = 2 } } },
    ["Green Woolen Bag"] = { spellId = 0, reagents = { { name = "Bolt of Woolen Cloth", count = 4 }, { name = "Green Dye", count = 1 }, { name = "Fine Thread", count = 1 } } },
    ["Red Woolen Boots"] = { spellId = 0, reagents = { { name = "Bolt of Woolen Cloth", count = 4 }, { name = "Light Leather", count = 2 }, { name = "Fine Thread", count = 2 }, { name = "Red Dye", count = 2 } } },
    ["Gray Woolen Shirt"] = { spellId = 0, reagents = { { name = "Bolt of Woolen Cloth", count = 2 }, { name = "Fine Thread", count = 1 }, { name = "Gray Dye", count = 1 } } },
    ["Heavy Woolen Cloak"] = { spellId = 0, reagents = { { name = "Bolt of Woolen Cloth", count = 3 }, { name = "Fine Thread", count = 2 }, { name = "Small Lustrous Pearl", count = 2 } } },
    ["Blue Overalls"] = { spellId = 0, reagents = { { name = "Bolt of Woolen Cloth", count = 4 }, { name = "Fine Thread", count = 2 }, { name = "Blue Dye", count = 2 } } },
    ["Gray Woolen Robe"] = { spellId = 0, reagents = { { name = "Bolt of Woolen Cloth", count = 4 }, { name = "Fine Thread", count = 3 }, { name = "Gray Dye", count = 1 } } },
    ["Double-Stitched Woolen Shoulders"] = { spellId = 0, reagents = { { name = "Bolt of Woolen Cloth", count = 3 }, { name = "Fine Thread", count = 2 } } },
    ["Heavy Woolen Pants"] = { spellId = 0, reagents = { { name = "Bolt of Woolen Cloth", count = 5 }, { name = "Fine Thread", count = 4 } } },
    ["Stylish Red Shirt"] = { spellId = 0, reagents = { { name = "Bolt of Woolen Cloth", count = 3 }, { name = "Red Dye", count = 2 }, { name = "Fine Thread", count = 1 } } },
    ["White Woolen Dress"] = { spellId = 0, reagents = { { name = "Bolt of Woolen Cloth", count = 3 }, { name = "Bleach", count = 4 }, { name = "Fine Thread", count = 1 } } },
    ["Red Woolen Bag"] = { spellId = 0, reagents = { { name = "Bolt of Woolen Cloth", count = 4 }, { name = "Red Dye", count = 1 }, { name = "Fine Thread", count = 1 } } },
    ["Greater Adept's Robe"] = { spellId = 0, reagents = { { name = "Bolt of Woolen Cloth", count = 5 }, { name = "Fine Thread", count = 3 }, { name = "Red Dye", count = 3 } } },
    ["Reinforced Woolen Shoulders"] = { spellId = 0, reagents = { { name = "Bolt of Woolen Cloth", count = 6 }, { name = "Medium Leather", count = 2 }, { name = "Fine Thread", count = 2 } } },
    ["Stylish Blue Shirt"] = { spellId = 0, reagents = { { name = "Bolt of Woolen Cloth", count = 4 }, { name = "Blue Dye", count = 2 }, { name = "Gray Dye", count = 1 }, { name = "Fine Thread", count = 1 } } },
    ["Stylish Green Shirt"] = { spellId = 0, reagents = { { name = "Bolt of Woolen Cloth", count = 4 }, { name = "Green Dye", count = 2 }, { name = "Gray Dye", count = 1 }, { name = "Fine Thread", count = 1 } } },
    ["Colorful Kilt"] = { spellId = 0, reagents = { { name = "Bolt of Woolen Cloth", count = 5 }, { name = "Red Dye", count = 3 }, { name = "Fine Thread", count = 1 } } },
    ["Bolt of Silk Cloth"] = { spellId = 0, reagents = { { name = "Silk Cloth", count = 4 } } },
    ["Phoenix Pants"] = { spellId = 0, reagents = { { name = "Bolt of Woolen Cloth", count = 6 }, { name = "Iridescent Pearl", count = 3 }, { name = "Fine Thread", count = 3 } } },
    ["Spidersilk Boots"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 2 }, { name = "Medium Leather", count = 4 }, { name = "Spider's Silk", count = 4 }, { name = "Iridescent Pearl", count = 2 } } },
    ["Spidersilk Drape"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 3 }, { name = "Spider's Silk", count = 6 }, { name = "Fine Thread", count = 2 } } },
    ["Phoenix Gloves"] = { spellId = 0, reagents = { { name = "Bolt of Woolen Cloth", count = 4 }, { name = "Iridescent Pearl", count = 4 }, { name = "Fine Thread", count = 4 }, { name = "Bleach", count = 2 } } },
    ["Gloves of Meditation"] = { spellId = 0, reagents = { { name = "Bolt of Woolen Cloth", count = 4 }, { name = "Fine Thread", count = 3 }, { name = "Elixir of Wisdom", count = 1 } } },
    ["Bright Yellow Shirt"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 1 }, { name = "Yellow Dye", count = 1 }, { name = "Fine Thread", count = 1 } } },
    ["Lesser Wizard's Robe"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 2 }, { name = "Fine Thread", count = 2 }, { name = "Spider's Silk", count = 2 } } },
    ["Spider Silk Slippers"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 3 }, { name = "Spider's Silk", count = 2 }, { name = "Fine Thread", count = 2 } } },
    ["Azure Silk Pants"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 4 }, { name = "Blue Dye", count = 2 }, { name = "Fine Thread", count = 3 } } },
    ["Azure Silk Hood"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 2 }, { name = "Blue Dye", count = 2 }, { name = "Fine Thread", count = 1 } } },
    ["Azure Silk Gloves"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 3 }, { name = "Heavy Leather", count = 2 }, { name = "Blue Dye", count = 2 }, { name = "Fine Thread", count = 2 } } },
    ["Hands of Darkness"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 3 }, { name = "Heavy Leather", count = 2 }, { name = "Shadow Protection Potion", count = 2 }, { name = "Fine Thread", count = 2 } } },
    ["Small Silk Pack"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 3 }, { name = "Heavy Leather", count = 2 }, { name = "Fine Thread", count = 3 } } },
    ["Azure Silk Vest"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 5 }, { name = "Blue Dye", count = 4 } } },
    ["Robes of Arcana"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 4 }, { name = "Fine Thread", count = 2 }, { name = "Spider's Silk", count = 2 } } },
    ["Truefaith Gloves"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 3 }, { name = "Heavy Leather", count = 2 }, { name = "Healing Potion", count = 4 }, { name = "Fine Thread", count = 1 } } },
    ["Dark Silk Shirt"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 2 }, { name = "Gray Dye", count = 2 }, { name = "Fine Thread", count = 1 } } },
    ["White Swashbuckler's Shirt"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 3 }, { name = "Bleach", count = 2 }, { name = "Silken Thread", count = 1 } } },
    ["Silk Headband"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 3 }, { name = "Fine Thread", count = 2 } } },
    ["Enchanter's Cowl"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 3 }, { name = "Fine Thread", count = 2 }, { name = "Thick Spider's Silk", count = 2 } } },
    ["Green Silk Armor"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 5 }, { name = "Green Dye", count = 2 }, { name = "Silken Thread", count = 1 } } },
    ["Formal White Shirt"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 3 }, { name = "Bleach", count = 2 }, { name = "Fine Thread", count = 1 } } },
    ["Shadow Hood"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 4 }, { name = "Silken Thread", count = 1 }, { name = "Shadow Oil", count = 1 } } },
    ["Earthen Vest"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 3 }, { name = "Elemental Earth", count = 2 }, { name = "Fine Thread", count = 2 } } },
    ["Bolt of Mageweave"] = { spellId = 0, reagents = { { name = "Mageweave Cloth", count = 5 } } },
    ["Red Swashbuckler's Shirt"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 3 }, { name = "Red Dye", count = 2 }, { name = "Silken Thread", count = 1 } } },
    ["Boots of the Enchanter"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 4 }, { name = "Silken Thread", count = 2 }, { name = "Thick Spider's Silk", count = 2 } } },
    ["Green Silk Pack"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 4 }, { name = "heavy Leather", count = 3 }, { name = "Fine Thread", count = 3 }, { name = "Green Dye", count = 1 } } },
    ["Azure Silk Belt"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 4 }, { name = "Elemental Water", count = 2 }, { name = "Blue Dye", count = 2 }, { name = "Fine Thread", count = 2 }, { name = "Iron Buckle", count = 1 } } },
    ["Crimson Silk Belt"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 4 }, { name = "Iron Buckle", count = 2 }, { name = "Red Dye", count = 2 }, { name = "Silken Thread", count = 1 } } },
    ["Azure Silk Cloak"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 3 }, { name = "Blue Dye", count = 2 }, { name = "Fine Thread", count = 2 } } },
    ["Spider Belt"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 4 }, { name = "Thick Spider's Silk", count = 2 }, { name = "Iron Buckle", count = 1 } } },
    ["Green Silken Shoulders"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 5 }, { name = "Silken Thread", count = 2 } } },
    ["Crimson Silk Cloak"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 5 }, { name = "Red Dye", count = 2 }, { name = "Fire Oil", count = 2 }, { name = "Silken Thread", count = 1 } } },
    ["Rich Purple Silk Shirt"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 4 }, { name = "Purple Dye", count = 1 }, { name = "Silken Thread", count = 1 } } },
    ["Long Silken Cloak"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 4 }, { name = "Mana Potion", count = 1 }, { name = "Silken Thread", count = 1 } } },
    ["Black Silk Pack"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 5 }, { name = "Black Dye", count = 4 }, { name = "Fine Thread", count = 4 } } },
    ["Crimson Silk Vest"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 4 }, { name = "Red Dye", count = 2 }, { name = "Fine Thread", count = 2 } } },
    ["Green Holiday Shirt"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 5 }, { name = "Green Dye", count = 4 }, { name = "Silken Thread", count = 1 } } },
    ["Robe of Power"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 2 }, { name = "Elemental Earth", count = 2 }, { name = "Elemental Water", count = 2 }, { name = "Elemental Fire", count = 2 }, { name = "Elemental Air", count = 2 }, { name = "Silken Thread", count = 2 } } },
    ["Crimson Silk Shoulders"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 5 }, { name = "Fire Oil", count = 2 }, { name = "Red Dye", count = 2 }, { name = "Silken Thread", count = 2 } } },
    ["Azure Shoulders"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 6 }, { name = "Naga Scale", count = 2 }, { name = "Blue Dye", count = 2 }, { name = "Silken Thread", count = 2 } } },
    ["Earthen Silk Belt"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 5 }, { name = "Elemental Earth", count = 4 }, { name = "heavy Leather", count = 4 }, { name = "Iron Buckle", count = 2 }, { name = "Silken Thread", count = 2 } } },
    ["Crimson Silk Pantaloons"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 4 }, { name = "Red Dye", count = 2 }, { name = "Silken Thread", count = 2 } } },
    ["Black Swashbuckler's Shirt"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 5 }, { name = "Black Dye", count = 1 }, { name = "Silken Thread", count = 1 } } },
    ["Icy Cloak"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 3 }, { name = "Silken Thread", count = 2 }, { name = "Frost Oil", count = 2 }, { name = "Thick Spider's Silk", count = 2 } } },
    ["Star Belt"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 4 }, { name = "heavy Leather", count = 4 }, { name = "Citrine", count = 1 }, { name = "Iron Buckle", count = 1 }, { name = "Silken Thread", count = 1 } } },
    ["Crimson Silk Robe"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 8 }, { name = "Elemental Fire", count = 4 }, { name = "Mana Potion", count = 2 }, { name = "Red Dye", count = 4 }, { name = "Silken Thread", count = 1 } } },
    ["Black Mageweave Vest"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 2 }, { name = "Silken Thread", count = 3 } } },
    ["Black Mageweave Leggings"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 2 }, { name = "Silken Thread", count = 3 } } },
    ["Crimson Silk Gloves"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 6 }, { name = "Elemental Fire", count = 2 }, { name = "Fire Oil", count = 2 }, { name = "Thick Leather", count = 2 }, { name = "Red Dye", count = 4 }, { name = "Silken Thread", count = 2 } } },
    ["Black Mageweave Robe"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 3 }, { name = "Silken Thread", count = 1 } } },
    ["Shadoweave Pants"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 3 }, { name = "Shadow Silk", count = 2 }, { name = "Silken Thread", count = 1 } } },
    ["White Bandit Mask"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 1 }, { name = "Bleach", count = 1 }, { name = "Heavy Silken Thread", count = 1 } } },
    ["Orange Mageweave Shirt"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 1 }, { name = "Orange Dye", count = 1 }, { name = "Heavy Silken Thread", count = 1 } } },
    ["Black Mageweave Gloves"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 2 }, { name = "Heavy Silken Thread", count = 2 } } },
    ["Shadoweave Robe"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 3 }, { name = "Shadow Silk", count = 2 }, { name = "Heavy Silken Thread", count = 1 } } },
    ["Red Mageweave Vest"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 3 }, { name = "Red Dye", count = 2 }, { name = "Heavy Silken Thread", count = 1 } } },
    ["Red Mageweave Pants"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 3 }, { name = "Red Dye", count = 2 }, { name = "Heavy Silken Thread", count = 1 } } },
    ["Orange Martial Shirt"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 2 }, { name = "Orange Dye", count = 2 }, { name = "Heavy Silken Thread", count = 1 } } },
    ["Mageweave Bag"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 4 }, { name = "Silken Thread", count = 2 } } },
    ["Red Mageweave Gloves"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 3 }, { name = "Red Dye", count = 2 }, { name = "Heavy Silken Thread", count = 2 } } },
    ["Dreamweave Gloves"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 4 }, { name = "Wildvine", count = 4 }, { name = "Heart of the Wild (crafting reagent)", count = 2 }, { name = "Heavy Silken Thread", count = 2 } } },
    ["Cindercloth Robe"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 5 }, { name = "Heart of Fire", count = 2 }, { name = "Heavy Silken Thread", count = 2 } } },
    ["Dreamweave Vest"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 6 }, { name = "Wildvine", count = 6 }, { name = "Heart of the Wild (crafting reagent)", count = 2 }, { name = "Heavy Silken Thread", count = 2 } } },
    ["Shadoweave Gloves"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 5 }, { name = "Shadow Silk", count = 5 }, { name = "Heavy Silken Thread", count = 2 } } },
    ["Enchanted Mageweave Pouch"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 4 }, { name = "Vision Dust", count = 4 }, { name = "Heavy Silken Thread", count = 2 } } },
    ["Black Swashbuckler's Shirt"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 5 }, { name = "Black Dye", count = 1 }, { name = "Silken Thread", count = 1 } } },
    ["Icy Cloak"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 3 }, { name = "Silken Thread", count = 2 }, { name = "Frost Oil", count = 1 }, { name = "Thick Spider's Silk", count = 2 } } },
    ["Star Belt"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 4 }, { name = "Heavy Leather", count = 4 }, { name = "Citrine", count = 1 }, { name = "Iron Buckle", count = 1 }, { name = "Silken Thread", count = 1 } } },
    ["Black Mageweave Leggings"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 2 }, { name = "Silken Thread", count = 3 } } },
    ["Black Mageweave Vest"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 2 }, { name = "Silken Thread", count = 3 } } },
    ["Crimson Silk Robe"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 8 }, { name = "Elemental Fire", count = 4 }, { name = "Mana Potion", count = 2 }, { name = "Red Dye", count = 4 }, { name = "Silken Thread", count = 1 } } },
    ["Black Mageweave Robe"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 3 }, { name = "Silken Thread", count = 1 } } },
    ["Crimson Silk Gloves"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 6 }, { name = "Elemental Fire", count = 2 }, { name = "Fire Oil", count = 2 }, { name = "Thick Leather", count = 2 }, { name = "Red Dye", count = 4 }, { name = "Silken Thread", count = 2 } } },
    ["Shadoweave Pants"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 3 }, { name = "Shadow Silk", count = 2 }, { name = "Heavy Silken Thread", count = 1 } } },
    ["White Bandit Mask"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 1 }, { name = "Bleach", count = 1 }, { name = "Heavy Silken Thread", count = 1 } } },
    ["Orange Mageweave Shirt"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 1 }, { name = "Orange Dye", count = 1 }, { name = "Heavy Silken Thread", count = 1 } } },
    ["Black Mageweave Gloves"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 2 }, { name = "Silken Thread", count = 2 } } },
    ["Red Mageweave Pants"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 3 }, { name = "Red Dye", count = 2 }, { name = "Heavy Silken Thread", count = 1 } } },
    ["Red Mageweave Vest"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 3 }, { name = "Red Dye", count = 2 }, { name = "Heavy Silken Thread", count = 1 } } },
    ["Shadoweave Robe"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 3 }, { name = "Shadow Silk", count = 2 }, { name = "Heavy Silken Thread", count = 1 } } },
    ["Orange Martial Shirt"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 2 }, { name = "Orange Dye", count = 2 }, { name = "Heavy Silken Thread", count = 1 } } },
    ["Dreamweave Gloves"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 4 }, { name = "Wildvine", count = 4 }, { name = "Heart of the Wild (crafting reagent)", count = 2 }, { name = "Heavy Silken Thread", count = 2 } } },
    ["Dreamweave Vest"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 6 }, { name = "Wildvine", count = 6 }, { name = "Heart of the Wild (crafting reagent)", count = 2 }, { name = "Heavy Silken Thread", count = 2 } } },
    ["Cindercloth Robe"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 5 }, { name = "Heart of Fire", count = 2 }, { name = "Heavy Silken Thread", count = 2 } } },
    ["Enchanted Mageweave Pouch"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 4 }, { name = "Vision Dust", count = 4 }, { name = "Heavy Silken Thread", count = 2 } } },
    ["Red Mageweave Gloves"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 3 }, { name = "Red Dye", count = 2 }, { name = "Heavy Silken Thread", count = 2 } } },
    ["Shadoweave Gloves"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 5 }, { name = "Shadow Silk", count = 5 }, { name = "Heavy Silken Thread", count = 2 } } },
    ["Mageweave Bag"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 4 }, { name = "Silken Thread", count = 2 } } },
    ["Lavender Mageweave Shirt"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 2 }, { name = "Purple Dye", count = 2 }, { name = "Heavy Silken Thread", count = 2 } } },
    ["Black Mageweave Boots"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 3 }, { name = "Heavy Silken Thread", count = 2 }, { name = "Thick Leather", count = 2 } } },
    ["Black Mageweave Headband"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 3 }, { name = "Heavy Silken Thread", count = 2 } } },
    ["Black Mageweave Shoulders"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 3 }, { name = "Heavy Silken Thread", count = 2 } } },
    ["Pink Mageweave Shirt"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 3 }, { name = "Pink Dye", count = 1 }, { name = "Heavy Silken Thread", count = 1 } } },
    ["Simple Black Dress"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 3 }, { name = "Black Dye", count = 1 }, { name = "Heavy Silken Thread", count = 1 }, { name = "Bleach", count = 1 } } },
    ["Red Mageweave Shoulders"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 4 }, { name = "Red Dye", count = 2 }, { name = "Heavy Silken Thread", count = 3 } } },
    ["Shadoweave Shoulders"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 5 }, { name = "Shadow Silk", count = 4 }, { name = "Heavy Silken Thread", count = 2 } } },
    ["Red Mageweave Bag"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 4 }, { name = "Red Dye", count = 2 }, { name = "Heavy Silken Thread", count = 2 } } },
    ["Tuxedo Shirt"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 4 }, { name = "Heavy Silken Thread", count = 2 } } },
    ["Admiral's Hat"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 5 }, { name = "Heavy Silken Thread", count = 2 } } },
    ["Red Mageweave Headband"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 4 }, { name = "Red Dye", count = 2 }, { name = "Heavy Silken Thread", count = 2 } } },
    ["Shadoweave Boots"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 6 }, { name = "Shadow Silk", count = 6 }, { name = "Heavy Silken Thread", count = 3 }, { name = "Thick Leather", count = 2 } } },
    ["Haliscan Pantaloons"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 4 }, { name = "Heavy Silken Thread", count = 3 }, { name = "Black Dye", count = 3 } } },
    ["Tuxedo Pants"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 4 }, { name = "Heavy Silken Thread", count = 3 } } },
    ["Cindercloth Boots"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 5 }, { name = "Heavy Silken Thread", count = 3 } } },
    ["Green Winter Clothes"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 4 }, { name = "Bolt of Woolen Cloth", count = 1 }, { name = "Green Dye", count = 2 }, { name = "Rune Thread", count = 1 } } },
    ["Red Winter Clothes"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 4 }, { name = "Bolt of Woolen Cloth", count = 1 }, { name = "Red Dye", count = 2 }, { name = "Rune Thread", count = 1 } } },
    ["Bolt of Runecloth"] = { spellId = 0, reagents = { { name = "Runecloth", count = 4 } } },
    ["White Wedding Dress"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 5 }, { name = "Heavy Silken Thread", count = 3 }, { name = "Bleach", count = 1 } } },
    ["Dress Shoes"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 4 }, { name = "Thick Leather", count = 2 } } },
    ["Dreamweave Circlet"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 8 }, { name = "Wildvine", count = 4 }, { name = "Heart of the Wild (crafting reagent)", count = 2 }, { name = "Heavy Silken Thread", count = 3 }, { name = "Truesilver Bar", count = 1 }, { name = "Jade", count = 1 } } },
    ["Festival Dress"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 4 }, { name = "Firebloom", count = 2 }, { name = "Red Dye", count = 2 }, { name = "Rune Thread", count = 1 } } },
    ["Festival Suit"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 4 }, { name = "Firebloom", count = 2 }, { name = "Red Dye", count = 2 }, { name = "Rune Thread", count = 1 } } },
    ["Haliscan Jacket"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 5 }, { name = "Black Dye", count = 2 }, { name = "Red Dye", count = 1 }, { name = "Heavy Silken Thread", count = 3 } } },
    ["Tuxedo Jacket"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 5 }, { name = "Heavy Silken Thread", count = 3 } } },
    ["Mooncloth"] = { spellId = 0, reagents = { { name = "Felcloth", count = 2 } } },
    ["Frostweave Robe"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 5 }, { name = "Globe of Water", count = 2 }, { name = "Rune Thread", count = 1 } } },
    ["Frostweave Tunic"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 5 }, { name = "Blue Dye", count = 2 }, { name = "Rune Thread", count = 1 } } },
    ["Runecloth Belt"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 3 }, { name = "Rune Thread", count = 1 } } },
    ["Cindercloth Vest"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 5 }, { name = "Heart of Fire", count = 2 }, { name = "Rune Thread", count = 1 } } },
    ["Runecloth Robe"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 5 }, { name = "Ironweb Spider Silk", count = 1 }, { name = "Rune Thread", count = 1 } } },
    ["Runecloth Tunic"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 5 }, { name = "Ironweb Spider Silk", count = 1 }, { name = "Rune Thread", count = 1 } } },
    ["Soul Pouch"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 6 }, { name = "Rugged Leather", count = 4 }, { name = "Ichor of Undeath", count = 2 }, { name = "Rune Thread", count = 1 } } },
    ["Runecloth Bag"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 5 }, { name = "Rugged Leather", count = 2 }, { name = "Rune Thread", count = 1 } } },
    ["Frostweave Gloves"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 5 }, { name = "Blue Dye", count = 2 }, { name = "Rune Thread", count = 1 } } },
    ["Ghostweave Belt"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 2 }, { name = "Ghost Dye", count = 1 } } },
    ["Runecloth Cloak"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 4 }, { name = "Ironweb Spider Silk", count = 1 } } },
    ["Brightcloth Gloves"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 4 }, { name = "Gold Bar", count = 2 } } },
    ["Brightcloth Robe"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 4 }, { name = "Gold Bar", count = 2 } } },
    ["Cindercloth Gloves"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 4 }, { name = "Heart of Fire", count = 2 }, { name = "Rune Thread", count = 1 } } },
    ["Ghostweave Gloves"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 2 }, { name = "Ghost Dye", count = 2 } } },
    ["Gordok Ogre Suit"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 2 }, { name = "Rugged Leather", count = 4 }, { name = "Ogre Tannin", count = 1 }, { name = "Rune Thread", count = 1 } } },
    ["Cloak of Fire"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 6 }, { name = "Essence of Fire", count = 4 }, { name = "Heart of Fire", count = 4 }, { name = "Elemental Fire", count = 4 }, { name = "Rune Thread", count = 1 } } },
    ["Brightcloth Cloak"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 4 }, { name = "Gold Bar", count = 2 } } },
    ["Cenarion Herb Bag"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 5 }, { name = "Purple Lotus", count = 10 }, { name = "Rune Thread", count = 2 } } },
    ["Cindercloth Cloak"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 5 }, { name = "Essence of Fire", count = 1 }, { name = "Rune Thread", count = 1 } } },
    ["Enchanted Runecloth Bag"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 5 }, { name = "Greater Eternal Essence", count = 2 }, { name = "Rune Thread", count = 1 } } },
    ["Felcloth Pants"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 5 }, { name = "Felcloth", count = 2 }, { name = "Rune Thread", count = 1 } } },
    ["Ghostweave Vest"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 2 }, { name = "Ghost Dye", count = 3 } } },
    ["Runecloth Gloves"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 5 }, { name = "Rune Thread", count = 2 } } },
    ["Wizardweave Leggings"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 4 }, { name = "Dream Dust", count = 1 }, { name = "Rune Thread", count = 1 } } },
    ["Cindercloth Pants"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 6 }, { name = "Essence of Fire", count = 1 }, { name = "Rune Thread", count = 1 } } },
    ["Frostweave Pants"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 6 }, { name = "Blue Dye", count = 2 }, { name = "Rune Thread", count = 1 } } },
    ["Runecloth Boots"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 4 }, { name = "Rugged Leather", count = 2 }, { name = "Rune Thread", count = 1 } } },
    ["Robe of Winter Night"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 10 }, { name = "Felcloth", count = 12 }, { name = "Essence of Undeath", count = 4 }, { name = "Essence of Water", count = 4 }, { name = "Rune Thread", count = 1 } } },
    ["Felcloth Boots"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 2 }, { name = "Felcloth", count = 2 }, { name = "Rugged Leather", count = 2 }, { name = "Rune Thread", count = 1 } } },
    ["Runecloth Pants"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 5 }, { name = "Ironweb Spider Silk", count = 2 }, { name = "Rune Thread", count = 1 } } },
    ["Mooncloth Boots"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 6 }, { name = "Mooncloth", count = 4 }, { name = "Black Pearl", count = 2 }, { name = "Rune Thread", count = 1 } } },
    ["Argent Boots"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 6 }, { name = "Enchanted Leather", count = 4 }, { name = "Golden Pearl", count = 2 }, { name = "Guardian Stone", count = 2 }, { name = "Ironweb Spider Silk", count = 2 } } },
    ["Mooncloth Leggings"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 6 }, { name = "Mooncloth", count = 4 }, { name = "Rune Thread", count = 1 } } },
    ["Wisdom of the Timbermaw"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 8 }, { name = "Essence of Earth", count = 3 }, { name = "Living Essence", count = 3 }, { name = "Ironweb Spider Silk", count = 2 } } },
    ["Brightcloth Pants"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 6 }, { name = "Gold Bar", count = 4 } } },
    ["Felcloth Hood"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 2 }, { name = "Felcloth", count = 2 }, { name = "Rune Thread", count = 1 } } },
    ["Ghostweave Pants"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 3 }, { name = "Ghost Dye", count = 4 } } },
    ["Runecloth Headband"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 6 }, { name = "Rune Thread", count = 2 } } },
    ["Big Bag of Enchantment"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 6 }, { name = "Large Brilliant Shard", count = 4 }, { name = "Enchanted Leather", count = 4 }, { name = "Ironweb Spider Silk", count = 4 } } },
    ["Felcloth Robe"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 8 }, { name = "Felcloth", count = 3 }, { name = "Demonic Rune", count = 2 }, { name = "Rune Thread", count = 2 } } },
    ["Felcloth Shoulders"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 7 }, { name = "Felcloth", count = 3 }, { name = "Demonic Rune", count = 2 }, { name = "Rugged Leather", count = 4 }, { name = "Rune Thread", count = 2 } } },
    ["Mooncloth Bag"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 4 }, { name = "Mooncloth", count = 1 }, { name = "Rune Thread", count = 1 } } },
    ["Runecloth Shoulders"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 7 }, { name = "Ironweb Spider Silk", count = 2 }, { name = "Rugged Leather", count = 4 }, { name = "Rune Thread", count = 1 } } },
    ["Satchel of Cenarius"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 6 }, { name = "Mooncloth", count = 2 }, { name = "Black Lotus", count = 1 }, { name = "Ironweb Spider Silk", count = 4 } } },
    ["Wizardweave Robe"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 8 }, { name = "Dream Dust", count = 2 }, { name = "Rune Thread", count = 1 } } },
    ["Wizardweave Turban"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 6 }, { name = "Dream Dust", count = 4 }, { name = "Star Ruby", count = 1 }, { name = "Rune Thread", count = 1 } } },
    ["Argent Shoulders"] = { spellId = 0, reagents = { { name = "Mooncloth", count = 5 }, { name = "Guardian Stone", count = 2 }, { name = "Ironweb Spider Silk", count = 2 } } },
    ["Bloodvine Boots"] = { spellId = 0, reagents = { { name = "Mooncloth", count = 4 }, { name = "Ironweb Spider Silk", count = 2 } } },
    ["Bloodvine Leggings"] = { spellId = 0, reagents = { { name = "Mooncloth", count = 4 }, { name = "Powerful Mojo", count = 4 }, { name = "Ironweb Spider Silk", count = 2 } } },
    ["Bloodvine Vest"] = { spellId = 0, reagents = { { name = "Mooncloth", count = 3 }, { name = "Powerful Mojo", count = 3 }, { name = "Ironweb Spider Silk", count = 2 } } },
    ["Bottomless Bag"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 8 }, { name = "Mooncloth", count = 12 }, { name = "Large Brilliant Shard", count = 2 }, { name = "Core Leather", count = 2 }, { name = "Rune Thread", count = 2 } } },
    ["Cloak of Warding"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 12 }, { name = "Guardian Stone", count = 4 }, { name = "Arcanite Bar", count = 1 }, { name = "Rune Thread", count = 2 } } },
    ["Felcloth Gloves"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 12 }, { name = "Felcloth", count = 20 }, { name = "Demonic Rune", count = 6 }, { name = "Essence of Undeath", count = 8 }, { name = "Rune Thread", count = 2 } } },
    ["Gaea's Embrace"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 3 }, { name = "Living Essence", count = 5 }, { name = "Ironweb Spider Silk", count = 4 } } },
    ["Inferno Gloves"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 12 }, { name = "Essence of Fire", count = 10 }, { name = "Star Ruby", count = 2 }, { name = "Rune Thread", count = 2 } } },
    ["Mantle of the Timbermaw"] = { spellId = 0, reagents = { { name = "Mooncloth", count = 5 }, { name = "Essence of Earth", count = 5 }, { name = "Living Essence", count = 5 }, { name = "Ironweb Spider Silk", count = 5 } } },
    ["Mooncloth Circlet"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 4 }, { name = "Mooncloth", count = 6 }, { name = "Azerothian Diamond", count = 1 }, { name = "Enchanted Leather", count = 2 }, { name = "Rune Thread", count = 2 } } },
    ["Mooncloth Gloves"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 12 }, { name = "Mooncloth", count = 6 }, { name = "Golden Pearl", count = 2 }, { name = "Rune Thread", count = 2 } } },
    ["Mooncloth Robe"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 6 }, { name = "Mooncloth", count = 4 }, { name = "Golden Pearl", count = 2 }, { name = "Rune Thread", count = 2 } } },
    ["Mooncloth Shoulders"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 5 }, { name = "Mooncloth", count = 5 }, { name = "Rune Thread", count = 1 } } },
    ["Mooncloth Vest"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 6 }, { name = "Mooncloth", count = 4 }, { name = "Rune Thread", count = 1 } } },
    ["Runed Stygian Belt"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 2 }, { name = "Dark Rune", count = 6 }, { name = "Felcloth", count = 2 }, { name = "Enchanted Leather", count = 2 }, { name = "Ironweb Spider Silk", count = 2 } } },
    ["Runed Stygian Boots"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 4 }, { name = "Dark Rune", count = 6 }, { name = "Felcloth", count = 4 }, { name = "Enchanted Leather", count = 2 }, { name = "Ironweb Spider Silk", count = 2 } } },
    ["Runed Stygian Leggings"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 5 }, { name = "Dark Rune", count = 8 }, { name = "Felcloth", count = 6 }, { name = "Ironweb Spider Silk", count = 2 } } },
    ["Sylvan Crown"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 4 }, { name = "Mooncloth", count = 2 }, { name = "Living Essence", count = 2 }, { name = "Ironweb Spider Silk", count = 2 } } },
    ["Sylvan Shoulders"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 2 }, { name = "Living Essence", count = 4 }, { name = "Ironweb Spider Silk", count = 2 } } },
    ["Sylvan Vest"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 4 }, { name = "Living Essence", count = 2 }, { name = "Ironweb Spider Silk", count = 2 } } },
    ["Belt of the Archmage"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 16 }, { name = "Ghost Dye", count = 10 }, { name = "Mooncloth", count = 10 }, { name = "Essence of Water", count = 12 }, { name = "Essence of Fire", count = 12 }, { name = "Large Brilliant Shard", count = 6 }, { name = "Rune Thread", count = 6 } } },
    ["Core Felcloth Bag"] = { spellId = 0, reagents = { { name = "Felcloth", count = 20 }, { name = "Core Leather", count = 16 }, { name = "Essence of Fire", count = 4 }, { name = "Ironweb Spider Silk", count = 4 } } },
    ["Flarecore Gloves"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 8 }, { name = "Fiery Core", count = 6 }, { name = "Essence of Fire", count = 4 }, { name = "Enchanted Leather", count = 2 }, { name = "Rune Thread", count = 2 } } },
    ["Flarecore Leggings"] = { spellId = 0, reagents = { { name = "Mooncloth", count = 8 }, { name = "Fiery Core", count = 5 }, { name = "Lava Core", count = 3 }, { name = "Essence of Fire", count = 10 }, { name = "Ironweb Spider Silk", count = 2 } } },
    ["Flarecore Mantle"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 12 }, { name = "Fiery Core", count = 4 }, { name = "Lava Core", count = 4 }, { name = "Enchanted Leather", count = 6 }, { name = "Rune Thread", count = 2 } } },
    ["Flarecore Robe"] = { spellId = 0, reagents = { { name = "Mooncloth", count = 10 }, { name = "Fiery Core", count = 2 }, { name = "Lava Core", count = 3 }, { name = "Essence of Fire", count = 6 }, { name = "Ironweb Spider Silk", count = 4 } } },
    ["Flarecore Wraps"] = { spellId = 0, reagents = { { name = "Mooncloth", count = 6 }, { name = "Fiery Core", count = 8 }, { name = "Essence of Fire", count = 2 }, { name = "Enchanted Leather", count = 6 }, { name = "Rune Thread", count = 4 } } },
    ["Gloves of Spell Mastery"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 10 }, { name = "Mooncloth", count = 10 }, { name = "Ghost Dye", count = 10 }, { name = "Golden Pearl", count = 6 }, { name = "Huge Emerald", count = 6 }, { name = "Enchanted Leather", count = 8 }, { name = "Rune Thread", count = 2 } } },
    ["Robe of the Archmage"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 12 }, { name = "Essence of Fire", count = 10 }, { name = "Essence of Air", count = 10 }, { name = "Essence of Earth", count = 10 }, { name = "Essence of Water", count = 10 }, { name = "Rune Thread", count = 2 } } },
    ["Robe of the Void"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 12 }, { name = "Demonic Rune", count = 20 }, { name = "Felcloth", count = 40 }, { name = "Essence of Fire", count = 12 }, { name = "Essence of Undeath", count = 12 }, { name = "Rune Thread", count = 2 } } },
    ["Truefaith Vestments"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 12 }, { name = "Mooncloth", count = 10 }, { name = "Righteous Orb", count = 4 }, { name = "Golden Pearl", count = 4 }, { name = "Ghost Dye", count = 10 }, { name = "Rune Thread", count = 2 } } },
}
