GuildShoppingList_TailoringPatterns  = {
    ["Pattern: Bolt of Linen Cloth"] = { spellId = 0, reagents = { { name = "Linen Cloth", count = 2 } } },
    ["Pattern: Brown Linen Shirt"] = { spellId = 0, reagents = { { name = "Bolt of Linen Cloth", count = 1 }, { name = "Coarse Thread", count = 1 } } },
    ["Pattern: Linen Cloak"] = { spellId = 0, reagents = { { name = "Bolt of Linen Cloth", count = 1 }, { name = "Coarse Thread", count = 1 } } },
    ["Pattern: Simple Linen Pants"] = { spellId = 0, reagents = { { name = "Bolt of Linen Cloth", count = 1 }, { name = "Coarse Thread", count = 1 } } },
    ["Pattern: White Linen Shirt"] = { spellId = 0, reagents = { { name = "Bolt of Linen Cloth", count = 1 }, { name = "Coarse Thread", count = 1 }, { name = "Bleach", count = 1 } } },
    ["Pattern: Brown Linen Vest"] = { spellId = 0, reagents = { { name = "Bolt of Linen Cloth", count = 1 }, { name = "Coarse Thread", count = 1 } } },
    ["Pattern: Linen Belt"] = { spellId = 0, reagents = { { name = "Bolt of Linen Cloth", count = 1 }, { name = "Coarse Thread", count = 1 } } },
    ["Pattern: Simple Linen Boots"] = { spellId = 0, reagents = { { name = "Bolt of Linen Cloth", count = 2 }, { name = "Light Leather", count = 1 }, { name = "Coarse Thread", count = 1 } } },
    ["Pattern: Brown Linen Pants"] = { spellId = 0, reagents = { { name = "Bolt of Linen Cloth", count = 2 }, { name = "Coarse Thread", count = 1 } } },
    ["Pattern: Brown Linen Robe"] = { spellId = 0, reagents = { { name = "Bolt of Linen Cloth", count = 3 }, { name = "Coarse Thread", count = 1 } } },
    ["Pattern: White Linen Robe"] = { spellId = 0, reagents = { { name = "Bolt of Linen Cloth", count = 3 }, { name = "Coarse Thread", count = 1 }, { name = "Bleach", count = 1 } } },
    ["Pattern: Heavy Linen Gloves"] = { spellId = 0, reagents = { { name = "Bolt of Linen Cloth", count = 2 }, { name = "Coarse Thread", count = 1 } } },
    ["Pattern: Red Linen Robe"] = { spellId = 0, reagents = { { name = "Bolt of Linen Cloth", count = 3 }, { name = "Coarse Thread", count = 2 }, { name = "Red Dye", count = 2 } } },
    ["Pattern: Red Linen Shirt"] = { spellId = 0, reagents = { { name = "Bolt of Linen Cloth", count = 2 }, { name = "Coarse Thread", count = 1 }, { name = "Red Dye", count = 1 } } },
    ["Pattern: Blue Linen Shirt"] = { spellId = 0, reagents = { { name = "Bolt of Linen Cloth", count = 2 }, { name = "Coarse Thread", count = 1 }, { name = "Blue Dye", count = 1 } } },
    ["Pattern: Simple Dress"] = { spellId = 0, reagents = { { name = "Bolt of Linen Cloth", count = 2 }, { name = "Coarse Thread", count = 1 }, { name = "Blue Dye", count = 1 }, { name = "Bleach", count = 1 } } },
    ["Pattern: Linen Bag"] = { spellId = 0, reagents = { { name = "Bolt of Linen Cloth", count = 3 }, { name = "Coarse Thread", count = 3 } } },
    ["Pattern: Red Linen Vest"] = { spellId = 0, reagents = { { name = "Bolt of Linen Cloth", count = 3 }, { name = "Coarse Thread", count = 1 }, { name = "Red Dye", count = 1 } } },
    ["Pattern: Blue Linen Vest"] = { spellId = 0, reagents = { { name = "Bolt of Linen Cloth", count = 3 }, { name = "Coarse Thread", count = 1 }, { name = "Blue Dye", count = 1 } } },
    ["Pattern: Reinforced Linen Cape"] = { spellId = 0, reagents = { { name = "Bolt of Linen Cloth", count = 2 }, { name = "Coarse Thread", count = 3 } } },
    ["Pattern: Green Linen Bracers"] = { spellId = 0, reagents = { { name = "Bolt of Linen Cloth", count = 3 }, { name = "Coarse Thread", count = 2 }, { name = "Green Dye", count = 1 } } },
    ["Pattern: Linen Boots"] = { spellId = 0, reagents = { { name = "Bolt of Linen Cloth", count = 3 }, { name = "Coarse Thread", count = 1 }, { name = "Light Leather", count = 1 } } },
    ["Pattern: Red Linen Bag"] = { spellId = 0, reagents = { { name = "Bolt of Linen Cloth", count = 4 }, { name = "Fine Thread", count = 1 }, { name = "Red Dye", count = 1 } } },
    ["Pattern: Blue Linen Robe"] = { spellId = 0, reagents = { { name = "Bolt of Linen Cloth", count = 4 }, { name = "Coarse Thread", count = 2 }, { name = "Blue Dye", count = 2 } } },
    ["Pattern: Simple Kilt"] = { spellId = 0, reagents = { { name = "Bolt of Linen Cloth", count = 4 }, { name = "Fine Thread", count = 1 } } },
    ["Pattern: Bolt of Woolen Cloth"] = { spellId = 0, reagents = { { name = "Wool Cloth", count = 2 } } },
    ["Pattern: Woolen Cape"] = { spellId = 0, reagents = { { name = "Bolt of Woolen Cloth", count = 1 }, { name = "Fine Thread", count = 1 } } },
    ["Pattern: Woolen Bag"] = { spellId = 0, reagents = { { name = "Bolt of Woolen Cloth", count = 3 }, { name = "Fine Thread", count = 1 } } },
    ["Pattern: Soft-Soled Linen Boots"] = { spellId = 0, reagents = { { name = "Bolt of Linen Cloth", count = 5 }, { name = "Light Leather", count = 2 }, { name = "Fine Thread", count = 1 } } },
    ["Pattern: Green Woolen Vest"] = { spellId = 0, reagents = { { name = "Bolt of Woolen Cloth", count = 2 }, { name = "Fine Thread", count = 2 }, { name = "Green Dye", count = 1 } } },
    ["Pattern: Heavy Woolen Gloves"] = { spellId = 0, reagents = { { name = "Bolt of Woolen Cloth", count = 3 }, { name = "Fine Thread", count = 1 } } },
    ["Pattern: Pearl-clasped Cloak"] = { spellId = 0, reagents = { { name = "Bolt of Woolen Cloth", count = 3 }, { name = "Fine Thread", count = 2 }, { name = "Small Lustrous Pearl", count = 1 } } },
    ["Pattern: Woolen Boots"] = { spellId = 0, reagents = { { name = "Bolt of Woolen Cloth", count = 4 }, { name = "Fine Thread", count = 2 }, { name = "Light Leather", count = 2 } } },
    ["Pattern: Green Woolen Bag"] = { spellId = 0, reagents = { { name = "Bolt of Woolen Cloth", count = 4 }, { name = "Green Dye", count = 1 }, { name = "Fine Thread", count = 1 } } },
    ["Pattern: Red Woolen Boots"] = { spellId = 0, reagents = { { name = "Bolt of Woolen Cloth", count = 4 }, { name = "Light Leather", count = 2 }, { name = "Fine Thread", count = 2 }, { name = "Red Dye", count = 2 } } },
    ["Pattern: Gray Woolen Shirt"] = { spellId = 0, reagents = { { name = "Bolt of Woolen Cloth", count = 2 }, { name = "Fine Thread", count = 1 }, { name = "Gray Dye", count = 1 } } },
    ["Pattern: Heavy Woolen Cloak"] = { spellId = 0, reagents = { { name = "Bolt of Woolen Cloth", count = 3 }, { name = "Fine Thread", count = 2 }, { name = "Small Lustrous Pearl", count = 2 } } },
    ["Pattern: Blue Overalls"] = { spellId = 0, reagents = { { name = "Bolt of Woolen Cloth", count = 4 }, { name = "Fine Thread", count = 2 }, { name = "Blue Dye", count = 2 } } },
    ["Pattern: Gray Woolen Robe"] = { spellId = 0, reagents = { { name = "Bolt of Woolen Cloth", count = 4 }, { name = "Fine Thread", count = 3 }, { name = "Gray Dye", count = 1 } } },
    ["Pattern: Double-Stitched Woolen Shoulders"] = { spellId = 0, reagents = { { name = "Bolt of Woolen Cloth", count = 3 }, { name = "Fine Thread", count = 2 } } },
    ["Pattern: Heavy Woolen Pants"] = { spellId = 0, reagents = { { name = "Bolt of Woolen Cloth", count = 5 }, { name = "Fine Thread", count = 4 } } },
    ["Pattern: Stylish Red Shirt"] = { spellId = 0, reagents = { { name = "Bolt of Woolen Cloth", count = 3 }, { name = "Red Dye", count = 2 }, { name = "Fine Thread", count = 1 } } },
    ["Pattern: White Woolen Dress"] = { spellId = 0, reagents = { { name = "Bolt of Woolen Cloth", count = 3 }, { name = "Bleach", count = 4 }, { name = "Fine Thread", count = 1 } } },
    ["Pattern: Red Woolen Bag"] = { spellId = 0, reagents = { { name = "Bolt of Woolen Cloth", count = 4 }, { name = "Red Dye", count = 1 }, { name = "Fine Thread", count = 1 } } },
    ["Pattern: Greater Adept's Robe"] = { spellId = 0, reagents = { { name = "Bolt of Woolen Cloth", count = 5 }, { name = "Fine Thread", count = 3 }, { name = "Red Dye", count = 3 } } },
    ["Pattern: Reinforced Woolen Shoulders"] = { spellId = 0, reagents = { { name = "Bolt of Woolen Cloth", count = 6 }, { name = "Medium Leather", count = 2 }, { name = "Fine Thread", count = 2 } } },
    ["Pattern: Stylish Blue Shirt"] = { spellId = 0, reagents = { { name = "Bolt of Woolen Cloth", count = 4 }, { name = "Blue Dye", count = 2 }, { name = "Gray Dye", count = 1 }, { name = "Fine Thread", count = 1 } } },
    ["Pattern: Stylish Green Shirt"] = { spellId = 0, reagents = { { name = "Bolt of Woolen Cloth", count = 4 }, { name = "Green Dye", count = 2 }, { name = "Gray Dye", count = 1 }, { name = "Fine Thread", count = 1 } } },
    ["Pattern: Colorful Kilt"] = { spellId = 0, reagents = { { name = "Bolt of Woolen Cloth", count = 5 }, { name = "Red Dye", count = 3 }, { name = "Fine Thread", count = 1 } } },
    ["Pattern: Bolt of Silk Cloth"] = { spellId = 0, reagents = { { name = "Silk Cloth", count = 4 } } },
    ["Pattern: Phoenix Pants"] = { spellId = 0, reagents = { { name = "Bolt of Woolen Cloth", count = 6 }, { name = "Iridescent Pearl", count = 3 }, { name = "Fine Thread", count = 3 } } },
    ["Pattern: Spidersilk Boots"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 2 }, { name = "Medium Leather", count = 4 }, { name = "Spider's Silk", count = 4 }, { name = "Iridescent Pearl", count = 2 } } },
    ["Pattern: Spidersilk Drape"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 3 }, { name = "Spider's Silk", count = 6 }, { name = "Fine Thread", count = 2 } } },
    ["Pattern: Phoenix Gloves"] = { spellId = 0, reagents = { { name = "Bolt of Woolen Cloth", count = 4 }, { name = "Iridescent Pearl", count = 4 }, { name = "Fine Thread", count = 4 }, { name = "Bleach", count = 2 } } },
    ["Pattern: Gloves of Meditation"] = { spellId = 0, reagents = { { name = "Bolt of Woolen Cloth", count = 4 }, { name = "Fine Thread", count = 3 }, { name = "Elixir of Wisdom", count = 1 } } },
    ["Pattern: Bright Yellow Shirt"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 1 }, { name = "Yellow Dye", count = 1 }, { name = "Fine Thread", count = 1 } } },
    ["Pattern: Lesser Wizard's Robe"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 2 }, { name = "Fine Thread", count = 2 }, { name = "Spider's Silk", count = 2 } } },
    ["Pattern: Spider Silk Slippers"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 3 }, { name = "Spider's Silk", count = 2 }, { name = "Fine Thread", count = 2 } } },
    ["Pattern: Azure Silk Pants"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 4 }, { name = "Blue Dye", count = 2 }, { name = "Fine Thread", count = 3 } } },
    ["Pattern: Azure Silk Hood"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 2 }, { name = "Blue Dye", count = 2 }, { name = "Fine Thread", count = 1 } } },
    ["Pattern: Azure Silk Gloves"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 3 }, { name = "Heavy Leather", count = 2 }, { name = "Blue Dye", count = 2 }, { name = "Fine Thread", count = 2 } } },
    ["Pattern: Hands of Darkness"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 3 }, { name = "Heavy Leather", count = 2 }, { name = "Shadow Protection Potion", count = 2 }, { name = "Fine Thread", count = 2 } } },
    ["Pattern: Small Silk Pack"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 3 }, { name = "Heavy Leather", count = 2 }, { name = "Fine Thread", count = 3 } } },
    ["Pattern: Azure Silk Vest"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 5 }, { name = "Blue Dye", count = 4 } } },
    ["Pattern: Robes of Arcana"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 4 }, { name = "Fine Thread", count = 2 }, { name = "Spider's Silk", count = 2 } } },
    ["Pattern: Truefaith Gloves"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 3 }, { name = "Heavy Leather", count = 2 }, { name = "Healing Potion", count = 4 }, { name = "Fine Thread", count = 1 } } },
    ["Pattern: Dark Silk Shirt"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 2 }, { name = "Gray Dye", count = 2 }, { name = "Fine Thread", count = 1 } } },
    ["Pattern: White Swashbuckler's Shirt"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 3 }, { name = "Bleach", count = 2 }, { name = "Silken Thread", count = 1 } } },
    ["Pattern: Silk Headband"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 3 }, { name = "Fine Thread", count = 2 } } },
    ["Pattern: Enchanter's Cowl"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 3 }, { name = "Fine Thread", count = 2 }, { name = "Thick Spider's Silk", count = 2 } } },
    ["Pattern: Green Silk Armor"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 5 }, { name = "Green Dye", count = 2 }, { name = "Silken Thread", count = 1 } } },
    ["Pattern: Formal White Shirt"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 3 }, { name = "Bleach", count = 2 }, { name = "Fine Thread", count = 1 } } },
    ["Pattern: Shadow Hood"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 4 }, { name = "Silken Thread", count = 1 }, { name = "Shadow Oil", count = 1 } } },
    ["Pattern: Earthen Vest"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 3 }, { name = "Elemental Earth", count = 2 }, { name = "Fine Thread", count = 2 } } },
    ["Pattern: Bolt of Mageweave"] = { spellId = 0, reagents = { { name = "Mageweave Cloth", count = 5 } } },
    ["Pattern: Red Swashbuckler's Shirt"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 3 }, { name = "Red Dye", count = 2 }, { name = "Silken Thread", count = 1 } } },
    ["Pattern: Boots of the Enchanter"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 4 }, { name = "Silken Thread", count = 2 }, { name = "Thick Spider's Silk", count = 2 } } },
    ["Pattern: Green Silk Pack"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 4 }, { name = "heavy Leather", count = 3 }, { name = "Fine Thread", count = 3 }, { name = "Green Dye", count = 1 } } },
    ["Pattern: Azure Silk Belt"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 4 }, { name = "Elemental Water", count = 2 }, { name = "Blue Dye", count = 2 }, { name = "Fine Thread", count = 2 }, { name = "Iron Buckle", count = 1 } } },
    ["Pattern: Crimson Silk Belt"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 4 }, { name = "Iron Buckle", count = 2 }, { name = "Red Dye", count = 2 }, { name = "Silken Thread", count = 1 } } },
    ["Pattern: Azure Silk Cloak"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 3 }, { name = "Blue Dye", count = 2 }, { name = "Fine Thread", count = 2 } } },
    ["Pattern: Spider Belt"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 4 }, { name = "Thick Spider's Silk", count = 2 }, { name = "Iron Buckle", count = 1 } } },
    ["Pattern: Green Silken Shoulders"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 5 }, { name = "Silken Thread", count = 2 } } },
    ["Pattern: Crimson Silk Cloak"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 5 }, { name = "Red Dye", count = 2 }, { name = "Fire Oil", count = 2 }, { name = "Silken Thread", count = 1 } } },
    ["Pattern: Rich Purple Silk Shirt"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 4 }, { name = "Purple Dye", count = 1 }, { name = "Silken Thread", count = 1 } } },
    ["Pattern: Long Silken Cloak"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 4 }, { name = "Mana Potion", count = 1 }, { name = "Silken Thread", count = 1 } } },
    ["Pattern: Black Silk Pack"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 5 }, { name = "Black Dye", count = 4 }, { name = "Fine Thread", count = 4 } } },
    ["Pattern: Crimson Silk Vest"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 4 }, { name = "Red Dye", count = 2 }, { name = "Fine Thread", count = 2 } } },
    ["Pattern: Green Holiday Shirt"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 5 }, { name = "Green Dye", count = 4 }, { name = "Silken Thread", count = 1 } } },
    ["Pattern: Robe of Power"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 2 }, { name = "Elemental Earth", count = 2 }, { name = "Elemental Water", count = 2 }, { name = "Elemental Fire", count = 2 }, { name = "Elemental Air", count = 2 }, { name = "Silken Thread", count = 2 } } },
    ["Pattern: Crimson Silk Shoulders"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 5 }, { name = "Fire Oil", count = 2 }, { name = "Red Dye", count = 2 }, { name = "Silken Thread", count = 2 } } },
    ["Pattern: Azure Shoulders"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 6 }, { name = "Naga Scale", count = 2 }, { name = "Blue Dye", count = 2 }, { name = "Silken Thread", count = 2 } } },
    ["Pattern: Earthen Silk Belt"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 5 }, { name = "Elemental Earth", count = 4 }, { name = "heavy Leather", count = 4 }, { name = "Iron Buckle", count = 2 }, { name = "Silken Thread", count = 2 } } },
    ["Pattern: Crimson Silk Pantaloons"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 4 }, { name = "Red Dye", count = 2 }, { name = "Silken Thread", count = 2 } } },
    ["Pattern: Black Swashbuckler's Shirt"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 5 }, { name = "Black Dye", count = 1 }, { name = "Silken Thread", count = 1 } } },
    ["Pattern: Icy Cloak"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 3 }, { name = "Silken Thread", count = 2 }, { name = "Frost Oil", count = 2 }, { name = "Thick Spider's Silk", count = 2 } } },
    ["Pattern: Star Belt"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 4 }, { name = "heavy Leather", count = 4 }, { name = "Citrine", count = 1 }, { name = "Iron Buckle", count = 1 }, { name = "Silken Thread", count = 1 } } },
    ["Pattern: Crimson Silk Robe"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 8 }, { name = "Elemental Fire", count = 4 }, { name = "Mana Potion", count = 2 }, { name = "Red Dye", count = 4 }, { name = "Silken Thread", count = 1 } } },
    ["Pattern: Black Mageweave Vest"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 2 }, { name = "Silken Thread", count = 3 } } },
    ["Pattern: Black Mageweave Leggings"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 2 }, { name = "Silken Thread", count = 3 } } },
    ["Pattern: Crimson Silk Gloves"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 6 }, { name = "Elemental Fire", count = 2 }, { name = "Fire Oil", count = 2 }, { name = "Thick Leather", count = 2 }, { name = "Red Dye", count = 4 }, { name = "Silken Thread", count = 2 } } },
    ["Pattern: Black Mageweave Robe"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 3 }, { name = "Silken Thread", count = 1 } } },
    ["Pattern: Shadoweave Pants"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 3 }, { name = "Shadow Silk", count = 2 }, { name = "Silken Thread", count = 1 } } },
    ["Pattern: White Bandit Mask"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 1 }, { name = "Bleach", count = 1 }, { name = "Heavy Silken Thread", count = 1 } } },
    ["Pattern: Orange Mageweave Shirt"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 1 }, { name = "Orange Dye", count = 1 }, { name = "Heavy Silken Thread", count = 1 } } },
    ["Pattern: Black Mageweave Gloves"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 2 }, { name = "Heavy Silken Thread", count = 2 } } },
    ["Pattern: Shadoweave Robe"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 3 }, { name = "Shadow Silk", count = 2 }, { name = "Heavy Silken Thread", count = 1 } } },
    ["Pattern: Red Mageweave Vest"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 3 }, { name = "Red Dye", count = 2 }, { name = "Heavy Silken Thread", count = 1 } } },
    ["Pattern: Red Mageweave Pants"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 3 }, { name = "Red Dye", count = 2 }, { name = "Heavy Silken Thread", count = 1 } } },
    ["Pattern: Orange Martial Shirt"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 2 }, { name = "Orange Dye", count = 2 }, { name = "Heavy Silken Thread", count = 1 } } },
    ["Pattern: Mageweave Bag"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 4 }, { name = "Silken Thread", count = 2 } } },
    ["Pattern: Red Mageweave Gloves"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 3 }, { name = "Red Dye", count = 2 }, { name = "Heavy Silken Thread", count = 2 } } },
    ["Pattern: Dreamweave Gloves"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 4 }, { name = "Wildvine", count = 4 }, { name = "Heart of the Wild (crafting reagent)", count = 2 }, { name = "Heavy Silken Thread", count = 2 } } },
    ["Pattern: Cindercloth Robe"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 5 }, { name = "Heart of Fire", count = 2 }, { name = "Heavy Silken Thread", count = 2 } } },
    ["Pattern: Dreamweave Vest"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 6 }, { name = "Wildvine", count = 6 }, { name = "Heart of the Wild (crafting reagent)", count = 2 }, { name = "Heavy Silken Thread", count = 2 } } },
    ["Pattern: Shadoweave Gloves"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 5 }, { name = "Shadow Silk", count = 5 }, { name = "Heavy Silken Thread", count = 2 } } },
    ["Pattern: Enchanted Mageweave Pouch"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 4 }, { name = "Vision Dust", count = 4 }, { name = "Heavy Silken Thread", count = 2 } } },
    ["Pattern: Black Swashbuckler's Shirt"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 5 }, { name = "Black Dye", count = 1 }, { name = "Silken Thread", count = 1 } } },
    ["Pattern: Icy Cloak"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 3 }, { name = "Silken Thread", count = 2 }, { name = "Frost Oil", count = 1 }, { name = "Thick Spider's Silk", count = 2 } } },
    ["Pattern: Star Belt"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 4 }, { name = "Heavy Leather", count = 4 }, { name = "Citrine", count = 1 }, { name = "Iron Buckle", count = 1 }, { name = "Silken Thread", count = 1 } } },
    ["Pattern: Black Mageweave Leggings"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 2 }, { name = "Silken Thread", count = 3 } } },
    ["Pattern: Black Mageweave Vest"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 2 }, { name = "Silken Thread", count = 3 } } },
    ["Pattern: Crimson Silk Robe"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 8 }, { name = "Elemental Fire", count = 4 }, { name = "Mana Potion", count = 2 }, { name = "Red Dye", count = 4 }, { name = "Silken Thread", count = 1 } } },
    ["Pattern: Black Mageweave Robe"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 3 }, { name = "Silken Thread", count = 1 } } },
    ["Pattern: Crimson Silk Gloves"] = { spellId = 0, reagents = { { name = "Bolt of Silk Cloth", count = 6 }, { name = "Elemental Fire", count = 2 }, { name = "Fire Oil", count = 2 }, { name = "Thick Leather", count = 2 }, { name = "Red Dye", count = 4 }, { name = "Silken Thread", count = 2 } } },
    ["Pattern: Shadoweave Pants"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 3 }, { name = "Shadow Silk", count = 2 }, { name = "Heavy Silken Thread", count = 1 } } },
    ["Pattern: White Bandit Mask"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 1 }, { name = "Bleach", count = 1 }, { name = "Heavy Silken Thread", count = 1 } } },
    ["Pattern: Orange Mageweave Shirt"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 1 }, { name = "Orange Dye", count = 1 }, { name = "Heavy Silken Thread", count = 1 } } },
    ["Pattern: Black Mageweave Gloves"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 2 }, { name = "Silken Thread", count = 2 } } },
    ["Pattern: Red Mageweave Pants"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 3 }, { name = "Red Dye", count = 2 }, { name = "Heavy Silken Thread", count = 1 } } },
    ["Pattern: Red Mageweave Vest"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 3 }, { name = "Red Dye", count = 2 }, { name = "Heavy Silken Thread", count = 1 } } },
    ["Pattern: Shadoweave Robe"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 3 }, { name = "Shadow Silk", count = 2 }, { name = "Heavy Silken Thread", count = 1 } } },
    ["Pattern: Orange Martial Shirt"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 2 }, { name = "Orange Dye", count = 2 }, { name = "Heavy Silken Thread", count = 1 } } },
    ["Pattern: Dreamweave Gloves"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 4 }, { name = "Wildvine", count = 4 }, { name = "Heart of the Wild (crafting reagent)", count = 2 }, { name = "Heavy Silken Thread", count = 2 } } },
    ["Pattern: Dreamweave Vest"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 6 }, { name = "Wildvine", count = 6 }, { name = "Heart of the Wild (crafting reagent)", count = 2 }, { name = "Heavy Silken Thread", count = 2 } } },
    ["Pattern: Cindercloth Robe"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 5 }, { name = "Heart of Fire", count = 2 }, { name = "Heavy Silken Thread", count = 2 } } },
    ["Pattern: Enchanted Mageweave Pouch"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 4 }, { name = "Vision Dust", count = 4 }, { name = "Heavy Silken Thread", count = 2 } } },
    ["Pattern: Red Mageweave Gloves"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 3 }, { name = "Red Dye", count = 2 }, { name = "Heavy Silken Thread", count = 2 } } },
    ["Pattern: Shadoweave Gloves"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 5 }, { name = "Shadow Silk", count = 5 }, { name = "Heavy Silken Thread", count = 2 } } },
    ["Pattern: Mageweave Bag"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 4 }, { name = "Silken Thread", count = 2 } } },
    ["Pattern: Lavender Mageweave Shirt"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 2 }, { name = "Purple Dye", count = 2 }, { name = "Heavy Silken Thread", count = 2 } } },
    ["Pattern: Black Mageweave Boots"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 3 }, { name = "Heavy Silken Thread", count = 2 }, { name = "Thick Leather", count = 2 } } },
    ["Pattern: Black Mageweave Headband"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 3 }, { name = "Heavy Silken Thread", count = 2 } } },
    ["Pattern: Black Mageweave Shoulders"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 3 }, { name = "Heavy Silken Thread", count = 2 } } },
    ["Pattern: Pink Mageweave Shirt"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 3 }, { name = "Pink Dye", count = 1 }, { name = "Heavy Silken Thread", count = 1 } } },
    ["Pattern: Simple Black Dress"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 3 }, { name = "Black Dye", count = 1 }, { name = "Heavy Silken Thread", count = 1 }, { name = "Bleach", count = 1 } } },
    ["Pattern: Red Mageweave Shoulders"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 4 }, { name = "Red Dye", count = 2 }, { name = "Heavy Silken Thread", count = 3 } } },
    ["Pattern: Shadoweave Shoulders"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 5 }, { name = "Shadow Silk", count = 4 }, { name = "Heavy Silken Thread", count = 2 } } },
    ["Pattern: Red Mageweave Bag"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 4 }, { name = "Red Dye", count = 2 }, { name = "Heavy Silken Thread", count = 2 } } },
    ["Pattern: Tuxedo Shirt"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 4 }, { name = "Heavy Silken Thread", count = 2 } } },
    ["Pattern: Admiral's Hat"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 5 }, { name = "Heavy Silken Thread", count = 2 } } },
    ["Pattern: Red Mageweave Headband"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 4 }, { name = "Red Dye", count = 2 }, { name = "Heavy Silken Thread", count = 2 } } },
    ["Pattern: Shadoweave Boots"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 6 }, { name = "Shadow Silk", count = 6 }, { name = "Heavy Silken Thread", count = 3 }, { name = "Thick Leather", count = 2 } } },
    ["Pattern: Haliscan Pantaloons"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 4 }, { name = "Heavy Silken Thread", count = 3 }, { name = "Black Dye", count = 3 } } },
    ["Pattern: Tuxedo Pants"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 4 }, { name = "Heavy Silken Thread", count = 3 } } },
    ["Pattern: Cindercloth Boots"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 5 }, { name = "Heavy Silken Thread", count = 3 } } },
    ["Pattern: Green Winter Clothes"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 4 }, { name = "Bolt of Woolen Cloth", count = 1 }, { name = "Green Dye", count = 2 }, { name = "Rune Thread", count = 1 } } },
    ["Pattern: Red Winter Clothes"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 4 }, { name = "Bolt of Woolen Cloth", count = 1 }, { name = "Red Dye", count = 2 }, { name = "Rune Thread", count = 1 } } },
    ["Pattern: Bolt of Runecloth"] = { spellId = 0, reagents = { { name = "Runecloth", count = 4 } } },
    ["Pattern: White Wedding Dress"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 5 }, { name = "Heavy Silken Thread", count = 3 }, { name = "Bleach", count = 1 } } },
    ["Pattern: Dress Shoes"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 4 }, { name = "Thick Leather", count = 2 } } },
    ["Pattern: Dreamweave Circlet"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 8 }, { name = "Wildvine", count = 4 }, { name = "Heart of the Wild (crafting reagent)", count = 2 }, { name = "Heavy Silken Thread", count = 3 }, { name = "Truesilver Bar", count = 1 }, { name = "Jade", count = 1 } } },
    ["Pattern: Festival Dress"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 4 }, { name = "Firebloom", count = 2 }, { name = "Red Dye", count = 2 }, { name = "Rune Thread", count = 1 } } },
    ["Pattern: Festival Suit"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 4 }, { name = "Firebloom", count = 2 }, { name = "Red Dye", count = 2 }, { name = "Rune Thread", count = 1 } } },
    ["Pattern: Haliscan Jacket"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 5 }, { name = "Black Dye", count = 2 }, { name = "Red Dye", count = 1 }, { name = "Heavy Silken Thread", count = 3 } } },
    ["Pattern: Tuxedo Jacket"] = { spellId = 0, reagents = { { name = "Bolt of Mageweave", count = 5 }, { name = "Heavy Silken Thread", count = 3 } } },
    ["Pattern: Mooncloth"] = { spellId = 0, reagents = { { name = "Felcloth", count = 2 } } },
    ["Pattern: Frostweave Robe"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 5 }, { name = "Globe of Water", count = 2 }, { name = "Rune Thread", count = 1 } } },
    ["Pattern: Frostweave Tunic"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 5 }, { name = "Blue Dye", count = 2 }, { name = "Rune Thread", count = 1 } } },
    ["Pattern: Runecloth Belt"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 3 }, { name = "Rune Thread", count = 1 } } },
    ["Pattern: Cindercloth Vest"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 5 }, { name = "Heart of Fire", count = 2 }, { name = "Rune Thread", count = 1 } } },
    ["Pattern: Runecloth Robe"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 5 }, { name = "Ironweb Spider Silk", count = 1 }, { name = "Rune Thread", count = 1 } } },
    ["Pattern: Runecloth Tunic"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 5 }, { name = "Ironweb Spider Silk", count = 1 }, { name = "Rune Thread", count = 1 } } },
    ["Pattern: Soul Pouch"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 6 }, { name = "Rugged Leather", count = 4 }, { name = "Ichor of Undeath", count = 2 }, { name = "Rune Thread", count = 1 } } },
    ["Pattern: Runecloth Bag"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 5 }, { name = "Rugged Leather", count = 2 }, { name = "Rune Thread", count = 1 } } },
    ["Pattern: Frostweave Gloves"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 5 }, { name = "Blue Dye", count = 2 }, { name = "Rune Thread", count = 1 } } },
    ["Pattern: Ghostweave Belt"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 2 }, { name = "Ghost Dye", count = 1 } } },
    ["Pattern: Runecloth Cloak"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 4 }, { name = "Ironweb Spider Silk", count = 1 } } },
    ["Pattern: Brightcloth Gloves"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 4 }, { name = "Gold Bar", count = 2 } } },
    ["Pattern: Brightcloth Robe"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 4 }, { name = "Gold Bar", count = 2 } } },
    ["Pattern: Cindercloth Gloves"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 4 }, { name = "Heart of Fire", count = 2 }, { name = "Rune Thread", count = 1 } } },
    ["Pattern: Ghostweave Gloves"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 2 }, { name = "Ghost Dye", count = 2 } } },
    ["Pattern: Gordok Ogre Suit"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 2 }, { name = "Rugged Leather", count = 4 }, { name = "Ogre Tannin", count = 1 }, { name = "Rune Thread", count = 1 } } },
    ["Pattern: Cloak of Fire"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 6 }, { name = "Essence of Fire", count = 4 }, { name = "Heart of Fire", count = 4 }, { name = "Elemental Fire", count = 4 }, { name = "Rune Thread", count = 1 } } },
    ["Pattern: Brightcloth Cloak"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 4 }, { name = "Gold Bar", count = 2 } } },
    ["Pattern: Cenarion Herb Bag"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 5 }, { name = "Purple Lotus", count = 10 }, { name = "Rune Thread", count = 2 } } },
    ["Pattern: Cindercloth Cloak"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 5 }, { name = "Essence of Fire", count = 1 }, { name = "Rune Thread", count = 1 } } },
    ["Pattern: Enchanted Runecloth Bag"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 5 }, { name = "Greater Eternal Essence", count = 2 }, { name = "Rune Thread", count = 1 } } },
    ["Pattern: Felcloth Pants"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 5 }, { name = "Felcloth", count = 2 }, { name = "Rune Thread", count = 1 } } },
    ["Pattern: Ghostweave Vest"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 2 }, { name = "Ghost Dye", count = 3 } } },
    ["Pattern: Runecloth Gloves"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 5 }, { name = "Rune Thread", count = 2 } } },
    ["Pattern: Wizardweave Leggings"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 4 }, { name = "Dream Dust", count = 1 }, { name = "Rune Thread", count = 1 } } },
    ["Pattern: Cindercloth Pants"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 6 }, { name = "Essence of Fire", count = 1 }, { name = "Rune Thread", count = 1 } } },
    ["Pattern: Frostweave Pants"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 6 }, { name = "Blue Dye", count = 2 }, { name = "Rune Thread", count = 1 } } },
    ["Pattern: Runecloth Boots"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 4 }, { name = "Rugged Leather", count = 2 }, { name = "Rune Thread", count = 1 } } },
    ["Pattern: Robe of Winter Night"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 10 }, { name = "Felcloth", count = 12 }, { name = "Essence of Undeath", count = 4 }, { name = "Essence of Water", count = 4 }, { name = "Rune Thread", count = 1 } } },
    ["Pattern: Felcloth Boots"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 2 }, { name = "Felcloth", count = 2 }, { name = "Rugged Leather", count = 2 }, { name = "Rune Thread", count = 1 } } },
    ["Pattern: Runecloth Pants"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 5 }, { name = "Ironweb Spider Silk", count = 2 }, { name = "Rune Thread", count = 1 } } },
    ["Pattern: Mooncloth Boots"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 6 }, { name = "Mooncloth", count = 4 }, { name = "Black Pearl", count = 2 }, { name = "Rune Thread", count = 1 } } },
    ["Pattern: Argent Boots"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 6 }, { name = "Enchanted Leather", count = 4 }, { name = "Golden Pearl", count = 2 }, { name = "Guardian Stone", count = 2 }, { name = "Ironweb Spider Silk", count = 2 } } },
    ["Pattern: Mooncloth Leggings"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 6 }, { name = "Mooncloth", count = 4 }, { name = "Rune Thread", count = 1 } } },
    ["Pattern: Wisdom of the Timbermaw"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 8 }, { name = "Essence of Earth", count = 3 }, { name = "Living Essence", count = 3 }, { name = "Ironweb Spider Silk", count = 2 } } },
    ["Pattern: Brightcloth Pants"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 6 }, { name = "Gold Bar", count = 4 } } },
    ["Pattern: Felcloth Hood"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 2 }, { name = "Felcloth", count = 2 }, { name = "Rune Thread", count = 1 } } },
    ["Pattern: Ghostweave Pants"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 3 }, { name = "Ghost Dye", count = 4 } } },
    ["Pattern: Runecloth Headband"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 6 }, { name = "Rune Thread", count = 2 } } },
    ["Pattern: Big Bag of Enchantment"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 6 }, { name = "Large Brilliant Shard", count = 4 }, { name = "Enchanted Leather", count = 4 }, { name = "Ironweb Spider Silk", count = 4 } } },
    ["Pattern: Felcloth Robe"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 8 }, { name = "Felcloth", count = 3 }, { name = "Demonic Rune", count = 2 }, { name = "Rune Thread", count = 2 } } },
    ["Pattern: Felcloth Shoulders"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 7 }, { name = "Felcloth", count = 3 }, { name = "Demonic Rune", count = 2 }, { name = "Rugged Leather", count = 4 }, { name = "Rune Thread", count = 2 } } },
    ["Pattern: Mooncloth Bag"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 4 }, { name = "Mooncloth", count = 1 }, { name = "Rune Thread", count = 1 } } },
    ["Pattern: Runecloth Shoulders"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 7 }, { name = "Ironweb Spider Silk", count = 2 }, { name = "Rugged Leather", count = 4 }, { name = "Rune Thread", count = 1 } } },
    ["Pattern: Satchel of Cenarius"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 6 }, { name = "Mooncloth", count = 2 }, { name = "Black Lotus", count = 1 }, { name = "Ironweb Spider Silk", count = 4 } } },
    ["Pattern: Wizardweave Robe"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 8 }, { name = "Dream Dust", count = 2 }, { name = "Rune Thread", count = 1 } } },
    ["Pattern: Wizardweave Turban"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 6 }, { name = "Dream Dust", count = 4 }, { name = "Star Ruby", count = 1 }, { name = "Rune Thread", count = 1 } } },
    ["Pattern: Argent Shoulders"] = { spellId = 0, reagents = { { name = "Mooncloth", count = 5 }, { name = "Guardian Stone", count = 2 }, { name = "Ironweb Spider Silk", count = 2 } } },
    ["Pattern: Bloodvine Boots"] = { spellId = 0, reagents = { { name = "Mooncloth", count = 4 }, { name = "Ironweb Spider Silk", count = 2 } } },
    ["Pattern: Bloodvine Leggings"] = { spellId = 0, reagents = { { name = "Mooncloth", count = 4 }, { name = "Powerful Mojo", count = 4 }, { name = "Ironweb Spider Silk", count = 2 } } },
    ["Pattern: Bloodvine Vest"] = { spellId = 0, reagents = { { name = "Mooncloth", count = 3 }, { name = "Powerful Mojo", count = 3 }, { name = "Ironweb Spider Silk", count = 2 } } },
    ["Pattern: Bottomless Bag"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 8 }, { name = "Mooncloth", count = 12 }, { name = "Large Brilliant Shard", count = 2 }, { name = "Core Leather", count = 2 }, { name = "Rune Thread", count = 2 } } },
    ["Pattern: Cloak of Warding"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 12 }, { name = "Guardian Stone", count = 4 }, { name = "Arcanite Bar", count = 1 }, { name = "Rune Thread", count = 2 } } },
    ["Pattern: Felcloth Gloves"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 12 }, { name = "Felcloth", count = 20 }, { name = "Demonic Rune", count = 6 }, { name = "Essence of Undeath", count = 8 }, { name = "Rune Thread", count = 2 } } },
    ["Pattern: Gaea's Embrace"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 3 }, { name = "Living Essence", count = 5 }, { name = "Ironweb Spider Silk", count = 4 } } },
    ["Pattern: Inferno Gloves"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 12 }, { name = "Essence of Fire", count = 10 }, { name = "Star Ruby", count = 2 }, { name = "Rune Thread", count = 2 } } },
    ["Pattern: Mantle of the Timbermaw"] = { spellId = 0, reagents = { { name = "Mooncloth", count = 5 }, { name = "Essence of Earth", count = 5 }, { name = "Living Essence", count = 5 }, { name = "Ironweb Spider Silk", count = 5 } } },
    ["Pattern: Mooncloth Circlet"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 4 }, { name = "Mooncloth", count = 6 }, { name = "Azerothian Diamond", count = 1 }, { name = "Enchanted Leather", count = 2 }, { name = "Rune Thread", count = 2 } } },
    ["Pattern: Mooncloth Gloves"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 12 }, { name = "Mooncloth", count = 6 }, { name = "Golden Pearl", count = 2 }, { name = "Rune Thread", count = 2 } } },
    ["Pattern: Mooncloth Robe"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 6 }, { name = "Mooncloth", count = 4 }, { name = "Golden Pearl", count = 2 }, { name = "Rune Thread", count = 2 } } },
    ["Pattern: Mooncloth Shoulders"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 5 }, { name = "Mooncloth", count = 5 }, { name = "Rune Thread", count = 1 } } },
    ["Pattern: Mooncloth Vest"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 6 }, { name = "Mooncloth", count = 4 }, { name = "Rune Thread", count = 1 } } },
    ["Pattern: Runed Stygian Belt"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 2 }, { name = "Dark Rune", count = 6 }, { name = "Felcloth", count = 2 }, { name = "Enchanted Leather", count = 2 }, { name = "Ironweb Spider Silk", count = 2 } } },
    ["Pattern: Runed Stygian Boots"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 4 }, { name = "Dark Rune", count = 6 }, { name = "Felcloth", count = 4 }, { name = "Enchanted Leather", count = 2 }, { name = "Ironweb Spider Silk", count = 2 } } },
    ["Pattern: Runed Stygian Leggings"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 5 }, { name = "Dark Rune", count = 8 }, { name = "Felcloth", count = 6 }, { name = "Ironweb Spider Silk", count = 2 } } },
    ["Pattern: Sylvan Crown"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 4 }, { name = "Mooncloth", count = 2 }, { name = "Living Essence", count = 2 }, { name = "Ironweb Spider Silk", count = 2 } } },
    ["Pattern: Sylvan Shoulders"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 2 }, { name = "Living Essence", count = 4 }, { name = "Ironweb Spider Silk", count = 2 } } },
    ["Pattern: Sylvan Vest"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 4 }, { name = "Living Essence", count = 2 }, { name = "Ironweb Spider Silk", count = 2 } } },
    ["Pattern: Belt of the Archmage"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 16 }, { name = "Ghost Dye", count = 10 }, { name = "Mooncloth", count = 10 }, { name = "Essence of Water", count = 12 }, { name = "Essence of Fire", count = 12 }, { name = "Large Brilliant Shard", count = 6 }, { name = "Rune Thread", count = 6 } } },
    ["Pattern: Core Felcloth Bag"] = { spellId = 0, reagents = { { name = "Felcloth", count = 20 }, { name = "Core Leather", count = 16 }, { name = "Essence of Fire", count = 4 }, { name = "Ironweb Spider Silk", count = 4 } } },
    ["Pattern: Flarecore Gloves"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 8 }, { name = "Fiery Core", count = 6 }, { name = "Essence of Fire", count = 4 }, { name = "Enchanted Leather", count = 2 }, { name = "Rune Thread", count = 2 } } },
    ["Pattern: Flarecore Leggings"] = { spellId = 0, reagents = { { name = "Mooncloth", count = 8 }, { name = "Fiery Core", count = 5 }, { name = "Lava Core", count = 3 }, { name = "Essence of Fire", count = 10 }, { name = "Ironweb Spider Silk", count = 2 } } },
    ["Pattern: Flarecore Mantle"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 12 }, { name = "Fiery Core", count = 4 }, { name = "Lava Core", count = 4 }, { name = "Enchanted Leather", count = 6 }, { name = "Rune Thread", count = 2 } } },
    ["Pattern: Flarecore Robe"] = { spellId = 0, reagents = { { name = "Mooncloth", count = 10 }, { name = "Fiery Core", count = 2 }, { name = "Lava Core", count = 3 }, { name = "Essence of Fire", count = 6 }, { name = "Ironweb Spider Silk", count = 4 } } },
    ["Pattern: Flarecore Wraps"] = { spellId = 0, reagents = { { name = "Mooncloth", count = 6 }, { name = "Fiery Core", count = 8 }, { name = "Essence of Fire", count = 2 }, { name = "Enchanted Leather", count = 6 }, { name = "Rune Thread", count = 4 } } },
    ["Pattern: Gloves of Spell Mastery"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 10 }, { name = "Mooncloth", count = 10 }, { name = "Ghost Dye", count = 10 }, { name = "Golden Pearl", count = 6 }, { name = "Huge Emerald", count = 6 }, { name = "Enchanted Leather", count = 8 }, { name = "Rune Thread", count = 2 } } },
    ["Pattern: Robe of the Archmage"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 12 }, { name = "Essence of Fire", count = 10 }, { name = "Essence of Air", count = 10 }, { name = "Essence of Earth", count = 10 }, { name = "Essence of Water", count = 10 }, { name = "Rune Thread", count = 2 } } },
    ["Pattern: Robe of the Void"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 12 }, { name = "Demonic Rune", count = 20 }, { name = "Felcloth", count = 40 }, { name = "Essence of Fire", count = 12 }, { name = "Essence of Undeath", count = 12 }, { name = "Rune Thread", count = 2 } } },
    ["Pattern: Truefaith Vestments"] = { spellId = 0, reagents = { { name = "Bolt of Runecloth", count = 12 }, { name = "Mooncloth", count = 10 }, { name = "Righteous Orb", count = 4 }, { name = "Golden Pearl", count = 4 }, { name = "Ghost Dye", count = 10 }, { name = "Rune Thread", count = 2 } } },
}
